// 服务 / 商品: categories (home grid, icons, colours, order), every service field in both languages, shelving, CSV import/export, reviews.
export default {
  menu: 'catalog',
  order: 25,
  icon: 'Goods',
  title: { zh: '服务 / 商品', en: 'Catalogue' },
  routes: [
    { path: '/catalog/services', component: () => import('./ServiceList.vue'), meta: { title: { zh: '服务列表', en: 'Listings' }, perm: 'catalog.view' }, menu: true },
    { path: '/catalog/services/:id', component: () => import('./ServiceEdit.vue'), meta: { title: { zh: '编辑服务', en: 'Edit listing' }, perm: 'catalog.view' } },
    { path: '/catalog/categories', component: () => import('./Categories.vue'), meta: { title: { zh: '分类管理', en: 'Categories' }, perm: 'catalog.view' }, menu: true },
    { path: '/catalog/reviews', component: () => import('./Reviews.vue'), meta: { title: { zh: '评价管理', en: 'Reviews' }, perm: 'catalog.reviews' }, menu: true },
  ],
  messages: {
    zh: {
      cat: {
        services: '服务列表', myProducts: '我的商品', q: '名称 / 编码 / 店铺', newService: '新增服务 / 商品', service: '服务 / 商品', type: '类型',
        types: { service: '预约服务', goods: '商品', job: '招聘' }, onShelf: '上架', offShelf: '下架', lowStock: '库存 ≤ 5', selected: '已选 {n} 项',
        putOn: '上架', takeOff: '下架', moveTo: '移到分类…', deleteConfirm: '删除选中的 {n} 项？删除后 App 不再显示，已有订单不受影响。', bulkDone: '已处理 {n} 项',
        price: '价格（RM）', stock: '库存', rating: '评分', soldCol: '已售', importResult: '导入结果', importLine: '新增 {created} 条，更新 {updated} 条，失败 {errors} 条',
        line: '行', error: '错误', importHint: '表头与导出文件一致；已有编码只更新填写的列，列表字段（包含 / 不含）用 “ | ” 分隔。',
        soldLine: '{orders} 单 · 成交 {gmv} · 已售 {sold} · 真实评价 {reviews}', openInApp: '在 App 中查看',
        tabBasic: '基本信息', tabDetail: '详情（中 / 英）', tabEnglish: '英文卡片', serviceId: '服务编码', serviceIdHint: '留空自动生成；小写字母、数字和 -',
        name: '名称', sub: '副标题', unit: '单位', unitHint: '次 / 次起 / 小时 / 份…（带「起」表示起步价）', unlimited: '不限库存',
        area: '区域', country: '国家代码', badge: '角标', store: '店铺显示名', storeHint: '留空使用商家名称', sortOrder: '推荐权重（越大越靠前）',
        ratingVotes: '基础评分权重', sales: '销量文案', salesHint: '如：累计服务 120 次', image: '主图', phoneBlock: '话费充值', phoneKind: '充值类型',
        jobBlock: '招聘信息', salaryMin: '最低月薪', salaryMax: '最高月薪', employment: '工作性质',
        detailHint: '左边中文、右边英文（英文留空时 App 显示中文）。', onePerLine: '每行一项',
        fields: { description: '介绍', duration: '时长', availability: '可预约时间', pricingNote: '价格说明', notice: '注意事项', includes: '包含', excludes: '不含', requirements: '任职要求', benefits: '福利', languages: '服务语言', details: '规格参数' },
        label: '名称', value: '内容', question: '问题', answer: '回答', sampleReviews: '示例评价', sampleReviewsHint: '展示在详情页的示例评价；会员的真实评价在「评价管理」。',
        author: '昵称', stars: '星级', reviewText: '评价内容', englishHint: '列表卡片和详情页标题的英文。', categories: '分类管理',
        categoriesSub: '首页宫格（上首页）与「全部服务」里的分类；顺序、图标、颜色和角标修改后 App 立即生效。', newCategory: '新增分类', editCategory: '编辑分类',
        order: '排序', position: '位置', homeGrid: '首页宫格', moreList: '更多分类', count: '上架 / 全部', categoryId: '分类编码', categoryIdHint: '小写字母，如 pets（创建后不能修改）',
        hint: '一句话介绍', icon: '图标', colors: '颜色', iconColor: '图标色', bgColor: '背景色', fallbackImage: '默认图片',
        reviews: '评价管理', shopReviews: '店铺评价', reviewQ: '评价内容 / 服务 / 用户', review: '评价', visible: '显示中', hidden: '已隐藏', reply: '回复', hide: '隐藏', show: '显示',
        replyHint: '回复会显示在 App 的评价下方',
      },
    },
    en: {
      cat: {
        services: 'Listings', myProducts: 'My products', q: 'Name / code / shop', newService: 'New listing', service: 'Listing', type: 'Type',
        types: { service: 'Service', goods: 'Goods', job: 'Job' }, onShelf: 'Listed', offShelf: 'Unlisted', lowStock: 'Stock ≤ 5', selected: '{n} selected',
        putOn: 'List', takeOff: 'Unlist', moveTo: 'Move to…', deleteConfirm: 'Delete {n} listings? They disappear from the app; existing orders are kept.', bulkDone: '{n} updated',
        price: 'Price (RM)', stock: 'Stock', rating: 'Rating', soldCol: 'Sold', importResult: 'Import result', importLine: '{created} created, {updated} updated, {errors} failed',
        line: 'Line', error: 'Error', importHint: 'Same columns as the export. Existing codes only change filled cells; list fields use " | ".',
        soldLine: '{orders} orders · {gmv} · {sold} sold · {reviews} real reviews', openInApp: 'Open in app',
        tabBasic: 'Basics', tabDetail: 'Details (zh / en)', tabEnglish: 'English card', serviceId: 'Code', serviceIdHint: 'Empty = generated; lower-case letters, digits and -',
        name: 'Name', sub: 'Subtitle', unit: 'Unit', unitHint: '次 / 次起 / 小时 … ("起" = starting price)', unlimited: 'Unlimited',
        area: 'Area', country: 'Country code', badge: 'Badge', store: 'Shop display name', storeHint: 'Empty = merchant name', sortOrder: 'Boost (higher first)',
        ratingVotes: 'Base rating weight', sales: 'Sales text', salesHint: 'e.g. 累计服务 120 次', image: 'Main image', phoneBlock: 'Mobile top-up', phoneKind: 'Top-up type',
        jobBlock: 'Job', salaryMin: 'Min salary', salaryMax: 'Max salary', employment: 'Employment',
        detailHint: 'Chinese on the left, English on the right (empty English shows the Chinese).', onePerLine: 'one per line',
        fields: { description: 'Description', duration: 'Duration', availability: 'Availability', pricingNote: 'Pricing note', notice: 'Notice', includes: 'Includes', excludes: 'Excludes', requirements: 'Requirements', benefits: 'Benefits', languages: 'Languages', details: 'Specifications' },
        label: 'Label', value: 'Value', question: 'Question', answer: 'Answer', sampleReviews: 'Sample reviews', sampleReviewsHint: 'Shown on the detail page; members’ real reviews are under Reviews.',
        author: 'Name', stars: 'Stars', reviewText: 'Review', englishHint: 'English for the list card and detail title.', categories: 'Categories',
        categoriesSub: 'Home grid and "all services" categories; order, icons, colours and badges apply to the app at once.', newCategory: 'New category', editCategory: 'Edit category',
        order: 'Order', position: 'Position', homeGrid: 'Home grid', moreList: 'More', count: 'Listed / all', categoryId: 'Code', categoryIdHint: 'lower-case letters, e.g. pets (fixed)',
        hint: 'Tagline', icon: 'Icon', colors: 'Colours', iconColor: 'Icon', bgColor: 'Background', fallbackImage: 'Default image',
        reviews: 'Reviews', shopReviews: 'Shop reviews', reviewQ: 'Text / listing / member', review: 'Review', visible: 'Visible', hidden: 'Hidden', reply: 'Reply', hide: 'Hide', show: 'Show',
        replyHint: 'Replies show under the review in the app',
      },
    },
  },
};
