'use strict';
let callTimer,activeCallOrder=null,activeRoom='p1',uploadData='',selectedAmount=20;
const cities=['吉隆坡','八打灵再也','槟城','新山','马六甲','怡保'];
function field(label,name,type='text',placeholder='',required=false,value=''){return `<label class="form-group"><span class="form-label">${label}${required?'<span class="required">*</span>':''}</span>${type==='textarea'?`<textarea class="field" name="${name}" placeholder="${placeholder}" maxlength="1000" ${required?'required':''}>${esc(value)}</textarea>`:`<input class="field" type="${type}" name="${name}" placeholder="${placeholder}" value="${esc(value)}" ${required?'required':''} ${type==='date'?`min="${localDate()}"`:''} ${type==='tel'?'title="请输入有效的联系电话" inputmode="tel"':''} ${type==='number'?'min="1" max="99"':''} ${type==='text'?'maxlength="120"':''}>`}</label>`}
function selectField(label,name,items,selected=''){
 if(name==='city'&&window.ShizhongRegions?.field)return window.ShizhongRegions.field(label,name,selected);
 const current=selected&&typeof selected==='object'?selected.cityName:selected;
 const options=current!==''&&current!=null&&!items.includes(current)?[current,...items]:items;
 return `<label class="form-group"><span class="form-label">${label}</span><select class="field" name="${name}">${options.map(s=>`<option ${s===current?'selected':''}>${esc(s)}</option>`).join('')}</select></label>`;
}
function flowLegacyLocation(city){return {countryCode:'MY',countryName:'马来西亚',cityId:'',cityName:city||'',stateId:'',stateName:'',custom:!cities.includes(city)}}
function flowFormLocation(form){
 if(window.ShizhongRegions?.readForm)return window.ShizhongRegions.readForm(form);
 const city=form.querySelector('[name="city"]')?.value||state.city;
 const saved=form.dataset.form==='address'&&form.dataset.address!=='new'?state.address[Number(form.dataset.address)]:null;
 if(saved&&(saved.location?.cityName||saved.city)===city)return {...(saved.location||flowLegacyLocation(city))};
 if(state.location?.cityName===city)return {...state.location};
 return flowLegacyLocation(city);
}
function flowApplyLocation(location,city){
 if(location&&window.ShizhongRegions?.applyLocation)window.ShizhongRegions.applyLocation(location);
 else if(location){state.location={...location};state.city=location.cityName||city||state.city}
 else if(city)state.city=city;
}
function flowDefaultAddress(service){
 const saved=state.address[0];if(!saved)return '';
 const addressLocation=saved.location||flowLegacyLocation(saved.city);
 const target=service?(service.location||{countryCode:service.countryCode||'MY',cityName:service.city||state.city}):(state.location||flowLegacyLocation(state.city));
 const sameCountry=String(addressLocation.countryCode||'MY').toUpperCase()===String(target.countryCode||'MY').toUpperCase();
 const sameCity=addressLocation.cityId&&target.cityId?String(addressLocation.cityId)===String(target.cityId):(addressLocation.cityName||saved.city)===(target.cityName||state.city);
 return sameCountry&&sameCity?saved.address||'':'';
}
function uploadField(label='添加一张照片',options={}){
 const avatar=Boolean(options.avatar), preview=options.preview?asset(options.preview):'';
 return `<label class="upload-box ${avatar?'avatar-upload-box':''}">${avatar?`<img class="upload-preview avatar-upload-preview" src="${esc(preview)}" alt="当前头像预览" style="display:block">`:icon('image')}<span>${label}</span><input type="file" name="photo" ${avatar?'data-avatar-upload="true"':''} accept="${avatar?'image/png,image/jpeg,image/gif,image/webp':'image/png,image/jpeg,image/webp'}">${avatar?'':'<img class="upload-preview" alt="已选图片预览"> '}</label>`;
}
function summary(rows){return rows.map(([label,value])=>`<div class="summary-row"><span>${label}</span><strong>${esc(value)}</strong></div>`).join('')}
function submitButton(text){return `<button class="primary-button" type="submit">${text}</button>`}
function formNote(){return '<p class="form-note">当前为设计体验，提交的信息仅保存在本机，不会产生真实订单或费用。</p>'}
function legacyRequestForm(id,serviceId=''){const c=[...categories,...moreCategories].find(x=>x.id===id)||categories[0];const s=services.find(x=>x.id===serviceId);let content='';let contactRequired=true;const address=flowDefaultAddress(s);
 if(['clean','repair','beauty'].includes(id)){content=selectField('需要什么服务','project',id==='clean'?['日常保洁','空调清洗','深度清洁','搬家清洁']:id==='repair'?['家电维修','手机 / 电脑维修','宽带安装','其他维修']:['美甲','美发','日常护理'])+field('服务地址','address','text','街道、公寓名称及单元号',true,address)+field('期望日期','date','date','',true)}
 else if(id==='guide'){content=selectField('想去的城市','city',cities,state.city)+`<div class="form-grid">${field('出游日期','date','date','',true)}${selectField('出游人数','people',['1 人','2 人','3–4 人','5 人以上'])}</div>`+selectField('沟通语言','language',['中文','English','Bahasa Melayu'])}
 else if(['market','food','flower'].includes(id)){content=s?'':field('想买什么','project','text',id==='flower'?'例如：一束鲜花，生日蛋糕':'例如：牛奶、水果、两份椰浆饭',true);content+=field('送达地址','address','text','收货地址、楼栋与单元号',true,address)+selectField('送达时间','time',['尽快送达','今天下午','今天晚上','明天上午']);if(s)content+=`<div class="count-control">${act('quantity','-1','−','', 'aria-label="减少数量"')}<output id="quantity">${ui.quantity}</output>${act('quantity','1','+','','aria-label="增加数量"')}</div><div class="summary-row"><span>商品小计</span><strong id="goods-total">RM ${(s.price*ui.quantity).toFixed(2)}</strong></div>`}
 else if(id==='jobs'){content=selectField('我想','intent',['找工作','招人才'])+field('职位','project','text','例如：中文客服 / 餐厅店员',true)+selectField('工作城市','city',cities,state.city)+field('薪资范围','salary','text','选填，例如：RM 3,000–4,000 / 月')}
 else if(id==='car'){content=field('上车地点','from','text','机场、酒店或地址',true)+field('目的地','to','text','想去哪里',true)+`<div class="form-grid">${field('用车日期','date','date','',true)}${field('用车时间','time','time','',true)}</div>`+field('航班号','flight','text','接机可填写，例如 MH 123')}
 else if(id==='delivery'){content=field('从哪里取','from','text','取件地址',true)+field('送到哪里','to','text','收件地址',true)+field('配送物品','project','text','物品名称和大约大小',true)}
 else if(id==='phone'){content=field('充值号码','number','tel','+60 手机号码',true)+selectField('运营商','provider',['Maxis / Hotlink','CelcomDigi','U Mobile','Yes','其他'])+selectField('充值金额','amount',['RM 10','RM 20','RM 50','RM 100']);contactRequired=false}
 else{content=field(id==='visa'?'目的地与咨询事项':'想去哪里','project','text',id==='visa'?'例如：旅游签证，材料咨询':'国家、城市或景点',true)+field('预计日期','date','date','',true)+selectField('人数','people',['1 人','2 人','3–4 人','5 人以上'])}
 if(!s&&!['guide','jobs'].includes(id))content=selectField('服务国家 / 城市','city',cities,state.location||state.city)+content;
 showSheet(s?s.name:'发布'+c.name+'需求',`<form data-form="request" data-category="${id}" data-service="${serviceId}">${s?`<div class="form-summary"><img src="${asset(s.image)}" alt="${s.name}"><div><h3>${s.store}</h3><p>RM ${s.price} / ${s.unit}</p></div></div>`:''}${content}${contactRequired?field('联系电话','phone','tel',s?'+60 手机号，方便确认需求':'国家 / 地区代码与手机号',true,state.profile.phone):''}${field('补充说明','note','textarea','选填，告诉我们一点你的偏好')}${formNote()}${submitButton(s?.type==='goods'?'确认演示订单':'提交需求')}</form>`)}
function orderSuccess(order){showSheet('提交成功',`<div class="success-icon">${icon('check')}</div><h3 class="success-title">好生活，已安排</h3><p class="success-text">你的需求已保存，随时可以在「我的订单」查看。<br>当前为本地演示，不会发送给真实商家。</p><div class="panel" style="margin-bottom:21px">${summary([['需求编号',order.id],['服务内容',order.title],['当前状态',order.status],...(order.total?[['参考合计','RM '+order.total.toFixed(2)]]:[])])}</div>${act('order-detail',order.id,'查看订单','primary-button')}<div style="margin-top:10px">${act('close','','继续逛逛','secondary-button')}</div>`)}
const fieldNames={candidate:'应聘人',experience:'相关经验',project:'需求项目',address:'服务地址',date:'预约日期',time:'预约时间',phone:'联系电话',city:'服务城市',people:'人数',language:'沟通语言',intent:'需求类型',salary:'薪资范围',from:'出发 / 取件地址',to:'目的 / 送达地址',flight:'航班号',number:'充值号码',provider:'运营商',amount:'充值金额',note:'补充说明',duration:'时长',mode:'连线方式',topic:'聊天话题',host:'预约对象'};
function greet(id){const p=people.find(x=>x.id===id);if(!p)return;if(state.greeted.includes(id))return openChat(id);showSheet('向 '+p.name+' 打招呼',`<form data-form="greet" data-person="${id}"><div class="form-summary"><img class="avatar" src="${asset(p.photo)}" alt="${p.name}"><div><h3>${p.name}</h3><p>${p.tags.join(' · ')}</p></div></div><div class="selection-list">${['你好，很高兴认识你！','你也喜欢探店吗？','周末有出去走走的计划吗？'].map(t=>act('greeting-text',t,t,'chip outline')).join('')}</div>${field('想说的话','message','textarea','一句真诚的问候，就是好的开始',true,'你好，很高兴认识你！')}<p class="form-note">此处为本地聊天演示，对方不会收到真实消息。</p>${submitButton('发送问候')}</form>`)}
function sendChat(id,text,self=true){if(!state.messages[id])state.messages[id]=[];state.messages[id].push({text,self,time:Date.now()});save()}
function composer(){uploadData='';showSheet('分享此刻的生活',`<form data-form="post">${field('今天想分享什么','text','textarea','一个小发现、一杯好咖啡，或一个好心情…',true)}${uploadField()}<div style="margin-top:17px">${field('所在地点','place','text','例如：Bukit Bintang',false,state.city)}</div><div class="form-grid">${selectField('话题','topic',['记录生活','周末不宅家','大马日常','我的城市有点美'])}${selectField('谁可以看','visibility',['公开','仅自己'])}</div>${formNote()}${submitButton('发布动态')}</form>`)}
function giftPanel(){const gifts=[['flower','flower','心意鲜花',10],['coffee','food','暖心咖啡',20],['crown','crown','闪耀皇冠',100]];showSheet('送一份小心意',`<p>送给 ${people.find(p=>p.id===activeRoom).name}</p><div class="gift-grid">${gifts.map(([id,ico,name,price])=>act('select-gift',id,`${icon(ico)}<h3>${name}</h3><p>${price} 金豆</p>`,`gift-item ${ui.gift===id?'active':''}`)).join('')}</div><div class="balance-strip"><span>我的金豆 <b>${state.points}</b></span>${act('points','','去领取金豆 ›')}</div><p class="form-note">礼物是本地演示效果，仅扣除体验金豆。</p>${act('send-gift','','送出礼物','primary-button')}<div style="margin-top:10px">${act('room',activeRoom,'返回直播间','secondary-button')}</div>`)}
function callBooking(id){const p=people.find(x=>x.id===id);showSheet('预约面对面',`<form data-form="book-call" data-person="${id}"><div class="form-summary"><img class="avatar" src="${asset(p.photo)}" alt="${p.name}"><div><h3>${p.name}</h3><p>${p.theme} · RM ${p.price}/10 分钟</p></div></div><div class="form-grid">${field('预约日期','date','date','',true,nextDate())}${selectField('预约时间','time',['10:00','14:00','16:00','19:00','20:00','21:00'])}</div><div class="form-grid">${selectField('连线时长','duration',['10 分钟','20 分钟','30 分钟'])}${selectField('连线方式','mode',['视频聊天','语音聊天'])}</div>${field('想聊的话题','topic','textarea','选填：旅行、城市生活，或随便聊聊…')}<div class="summary-row"><span>预约参考合计</span><strong id="call-total">RM ${p.price.toFixed(2)}</strong></div>${formNote()}${submitButton('确认预约')}</form>`)}
function connectCall(id,orderId=null){activeCallOrder=orderId;const p=people.find(x=>x.id===id);if(!p)return;clearInterval(callTimer);currentOverlay={kind:'call',title:'面对面连线'};document.body.style.overflow='hidden';document.querySelector('#overlay-root').innerHTML=`<section class="full-screen call-room" role="dialog" aria-modal="true" aria-label="面对面体验"><div class="live-pill" style="margin-bottom:40px;background:#ffffff13">面对面 · 模拟连线</div><img class="avatar" src="${asset(p.photo)}" alt="${p.name}"><h2>${p.name}</h2><p>${p.theme}</p><p id="call-timer" style="font-size:24px;letter-spacing:3px;margin-top:28px">00:00</p><span class="small-remark">当前为界面演示，未启用摄像头与麦克风。</span><div class="call-controls"><button class="call-control" data-action="call-toggle" aria-pressed="false" aria-label="静音"><span class="icon-button">${icon('mic')}</span><span>静音</span></button><button class="call-control end" data-action="end-call"><span class="icon-button">${icon('phone')}</span><span>结束</span></button><button class="call-control" data-action="call-toggle" aria-pressed="false" aria-label="扬声器"><span class="icon-button">${icon('volume')}</span><span>扬声器</span></button></div></section>`;let secs=0;callTimer=setInterval(()=>{secs++;const el=document.querySelector('#call-timer');if(el)el.textContent=String(Math.floor(secs/60)).padStart(2,'0')+':'+String(secs%60).padStart(2,'0')},1000);focusOverlay()}
function editProfile(){uploadData='';showSheet('编辑个人资料',`<form data-form="profile">${uploadField('上传头像 · 可选动态图片',{avatar:true,preview:state.profile.photo})}<p class="form-note">支持 JPG、PNG/APNG、GIF、WebP；动态图片会在个人主页与聊天头像中播放。建议方形图片，文件不超过 2 MB。</p><div style="margin-top:18px">${field('昵称','name','text','你希望大家怎么称呼你',true,state.profile.name)}</div>${field('个人介绍','bio','textarea','简单介绍自己',false,state.profile.bio)}<div class="form-grid">${selectField('所在城市','city',cities,state.city)}${selectField('沟通语言','language',['中文','English','Bahasa Melayu','中文 / English'],state.profile.language)}</div>${field('联系电话','phone','tel','选填，填写国家 / 地区代码与手机号',false,state.profile.phone)}${submitButton('保存资料')}</form>`)}
function settings(){showScreen('设置',`<div class="detail-content"><div class="panel list-panel" style="margin:0">${listRow('user','个人资料','edit-profile')}${listRow('pin','常用地址','addresses')}${listRow('globe','语言与地区','language','中文 · '+(window.ShizhongRegions?.locationLabel()||'马来西亚'))}<div class="list-row">${icon('bell')}<span>接收站内提醒</span>${act('toggle-setting','notifications','',`toggle ${state.settings.notifications?'on':''}`,`role="switch" aria-checked="${state.settings.notifications}" aria-label="接收站内提醒"`)}</div><div class="list-row">${icon('pin')}<span>在附近的人中可见</span>${act('toggle-setting','nearby','',`toggle ${state.settings.nearby?'on':''}`,`role="switch" aria-checked="${state.settings.nearby}" aria-label="附近的人可见"`)}</div>${listRow('shield','隐私与使用说明','privacy')}${listRow('help','关于适中','about','v1.0 原稿')}</div><h3 class="subsection-title">我的体验数据</h3><p class="detail-description">订单、动态、聊天与资料保存在当前浏览器。照片仅保存在本机，不会自动上传。</p><div class="button-row">${act('export-data','','导出演示数据','secondary-button')}${act('reset-data','','重置体验','secondary-button')}</div></div>`)}
function wallet(){showSheet('我的钱包',`<div style="text-align:center;padding:15px"><p style="font-size:12px;color:#a18ca8">体验余额</p><h3 style="font-size:clamp(20px,6vw,30px);margin:12px 0 7px"><small style="font-size:18px">RM </small>${state.wallet.toLocaleString('en-MY',{minimumFractionDigits:2,maximumFractionDigits:2})}</h3><p class="small-remark">用于展示钱包操作，不是真实资金</p></div><div class="button-row">${act('recharge','','体验充值','primary-button')}${act('bills','','查看账单','secondary-button')}</div>`)}
function recharge(){showSheet('体验充值',`<p>选择一个金额，查看充值完成后的效果。</p><div class="payment-options">${[20,50,100].map(n=>act('recharge-amount',n,`<strong>${n}</strong>RM`, `payment-option ${n===selectedAmount?'active':''}`)).join('')}</div><form data-form="recharge">${selectField('支付方式','method',["Touch 'n Go eWallet",'DuitNow','银行卡'])}${formNote()}${submitButton('模拟充值 RM '+selectedAmount)}</form>`)}
function checkin(){const done=state.checkin===localDate();showSheet('每日签到',`<div style="text-align:center"><span class="mini-label">LITTLE THINGS, EVERY DAY</span><h3 style="font-size:24px;margin-top:10px">把小确幸，攒起来</h3><p class="small-remark">每天见面，送你 10 金豆</p></div><div class="date-chips">${Array.from({length:7},(_,i)=>`<div class="day-box ${i===0&&done?'done':''}">${i===0?'今天':'第 '+(i+1)+' 天'}<strong>${i===0&&done?'✓':'+10'}</strong></div>`).join('')}</div><div class="info-highlight">当前拥有 <b>${state.points}</b> 金豆，可以在直播间送出一份小心意。</div>${act('do-checkin','',done?'今日已签到，明天再来':'领取今日 10 金豆','primary-button yellow',done?'disabled':'')}`)}
function coupons(){showScreen('我的优惠券',`<div class="detail-content">${state.coupons.length?state.coupons.map((c,i)=>`<div class="coupon"><div class="coupon-value"><small>RM</small>${c==='welcome'?'10':'5'}</div><div><h3>${c==='welcome'?'新人见面礼':'城市生活优惠券'}</h3><p>生活服务满 RM 80 可用<br>本地原稿展示券</p>${act('use-coupon','','去逛逛')}</div></div>`).join(''):empty('优惠正在路上','继续发现你喜欢的城市生活。','go-home','去逛逛')}<p class="form-note">原稿中展示优惠券样式，参考价格未扣减优惠。</p></div>`)}
function addresses(){showScreen('常用地址',`<div class="detail-content">${state.address.length?state.address.map((a,i)=>`<div class="address-card"><h3>${esc(a.name)} <small style="color:#a69aac">${esc(a.phone)}</small></h3><p>${esc(a.address)}<br>${esc(a.location?.countryName||'马来西亚')} · ${esc(a.location?.cityName||a.city)} ${esc(a.postcode||'')}</p><div class="order-actions">${i===0?'<span class="tag">默认地址</span>':act('default-address',i,'设为默认')}${act('edit-address',i,'编辑')}${act('remove-address',i,'删除')}</div></div>`).join(''):empty('把常用地址存起来','下次预约，就能少填一步。')}${act('edit-address','new','+ 添加新地址','primary-button')}</div>`)}
function addressForm(id){const a=state.address[Number(id)]||{};showSheet(id==='new'?'添加地址':'编辑地址',`<form data-form="address" data-address="${id}"><div class="form-grid">${field('联系人','name','text','怎么称呼你',true,a.name||'')}${field('联系电话','phone','tel','国家 / 地区代码与手机号',true,a.phone||'')}</div>${selectField('城市','city',cities,a.location||(a.city?flowLegacyLocation(a.city):(state.location||state.city)))}${field('详细地址','address','textarea','街道、楼栋与单元号',true,a.address||'')}${field('邮编','postcode','text','马来西亚需填写 5 位；其他地区选填',false,a.postcode||'').replace('maxlength="120"','maxlength="20"')}${submitButton('保存地址')}</form>`)}
function showHelp(){showScreen('帮助与反馈',`<div class="detail-content">${[['如何预约生活服务？','在首页选择服务，填写地点、时间和联系方式。提交后，可在「我的订单」查看需求进度。'],['如何开始一对一聊天？','在直播页切换到一对一聊天，选择在线等候的主播即可直接进入。连线中可发消息、赠送礼物、控制镜头和结束聊天；本原稿提供免费演示连线。'],['支付和退款如何处理？','当前为 HTML 交互设计原稿，钱包、订单与支付均为演示状态，不会产生真实扣款。'],['如何保护我的隐私？','在设置中管理附近可见和站内提醒。当前原稿的数据仅保存在本机浏览器，可导出或重置。']].map(([q,a])=>`<details class="faq"><summary>${q}</summary><p>${a}</p></details>`).join('')}<div class="button-row">${act('chat','support','联系小助手','primary-button')}${act('feedback','','意见反馈','secondary-button')}</div></div>`)}
function notifications(){showScreen('消息通知',`<div class="detail-content"><div class="notice-card"><h3>欢迎来到适中</h3><p>给你准备了一份新人见面礼。到「我的优惠」看看，一起开启大马好生活。</p><time>今天 09:41</time>${act('coupons','','查看新人礼','small-primary','style="margin-top:12px"')}</div>${state.orders.slice(0,5).map(o=>`<div class="notice-card"><h3>你的${esc(o.title)} · ${o.status}</h3><p>需求编号 ${o.id}，点击查看详细信息。</p><time>${esc(o.created)}</time>${act('order-detail',o.id,'查看详情','small-primary','style="margin-top:12px"')}</div>`).join('')}${state.checkin===localDate()?'<div class="notice-card"><h3>今天的小确幸已到账</h3><p>签到成功，10 金豆已加入你的账户。</p></div>':''}</div>`)}
function menuAction(action,id,button){if(expandedAction(action,id,button))return;switch(action){
 case 'nav':navigate(id);break;case 'close':closeOverlay();break;case 'go-home':case 'use-coupon':navigate('home');break;
 case 'home-tab':ui.homeTab=id;ui.homeFilter='推荐';render();break;case 'home-filter':ui.homeFilter=id;render();break;
 case 'social-tab':ui.socialTab=id;ui.socialFilter='推荐';render();break;case 'social-filter':ui.socialFilter=id;render();break;
 case 'live-tab':ui.liveTab=id;ui.liveFilter='全部';render();break;case 'live-filter':ui.liveFilter=id;render();break;
 case 'comms-tab':ui.commsTab=id;render();break;
 case 'city':showSheet('选择你的城市',`<p>好生活，从你所在的城市开始。</p><div class="city-grid">${cities.map(c=>act('select-city',c,c,state.city===c?'active':'')).join('')}</div><p class="form-note">当前服务和人物为示例内容，城市切换用于填写当地需求。</p>`);break;
 case 'select-city':state.city=id;save();render();closeOverlay();toast('已切换至 '+id);break;
 case 'category':categoryPage(id);break;case 'service':serviceDetail(id);break;case 'request':ui.quantity=1;requestForm(id);break;case 'book-service':ui.quantity=1;requestForm(services.find(s=>s.id===id).cat,id);break;
 case 'all-services':showScreen('发现好生活',`<div class="detail-content"><div class="product-grid">${services.map(productCard).join('')}</div></div>`);break;
 case 'campaign':showScreen('你好，马来西亚',`<div class="detail-hero"><img src="${asset('hero.png')}" alt="吉隆坡城市生活"></div><div class="detail-content"><h2>在大马，把日子过成喜欢。</h2><p class="detail-description">跟着本地人走一条新路线，吃一顿喜欢的饭，再给自己一个轻松的周末。</p>${heading('这周值得体验')}<div class="product-grid">${services.filter(s=>['s1','s2','s5','s6'].includes(s.id)).map(productCard).join('')}</div></div>`);break;
 case 'quantity':ui.quantity=Math.max(1,Math.min(20,ui.quantity+Number(id)));document.querySelector('#quantity').value=ui.quantity;{const f=button.closest('form');const s=services.find(s=>s.id===f.dataset.service);document.querySelector('#goods-total').textContent='RM '+(s.price*ui.quantity).toFixed(2)}break;
 case 'save-service':{const at=state.saved.indexOf(id);at<0?state.saved.push(id):state.saved.splice(at,1);save();button.style.color=at<0?'var(--red)':'inherit';toast(at<0?'已收藏到「我的」':'已取消收藏');render()}break;
 case 'orders':orders(id);break;case 'order-detail':orderDetail(id);break;
 case 'confirm-order':{const o=state.orders.find(o=>o.id===id);o.status='待服务';save();render();orderDetail(id);toast('已模拟商家确认预约')}break;
 case 'complete-order':{const o=state.orders.find(o=>o.id===id);o.status='已完成';save();render();orderDetail(id);toast('服务已完成，谢谢你的体验')}break;
 case 'cancel-order':showSheet('取消这条需求？',`<p>这条需求将标记为已取消，你可以随时重新预约。</p><div class="button-row">${act('order-detail',id,'保留需求','secondary-button')}${act('cancel-confirm',id,'确认取消','primary-button')}</div>`);break;
 case 'cancel-confirm':state.orders.find(o=>o.id===id).status='已取消';save();render();orderDetail(id);break;
 case 'person':personDetail(id);break;case 'greet':greet(id);break;case 'chat':openChat(id);break;
 case 'follow':case 'person-follow':case 'room-follow':{const at=state.follows.indexOf(id);at<0?state.follows.push(id):state.follows.splice(at,1);save();render();if(action==='person-follow')personDetail(id);else if(action==='room-follow')button.textContent=at<0?'已关注':'+ 关注';toast(at<0?'已关注，去动态看看 TA 的生活吧':'已取消关注')}break;
 case 'greeting-text':document.querySelector('textarea[name="message"]').value=id;break;
 case 'like':{const at=state.likes.indexOf(id);at<0?state.likes.push(id):state.likes.splice(at,1);save();render()}break;
 case 'compose':composer();break;case 'comments':comments(id);break;case 'social-filters':filterPeople();break;
 case 'social-recommend':closeOverlay();ui.socialTab='friends';ui.socialFilter='推荐';render();break;
 case 'social-event':showSheet('你好，新朋友',`<div class="info-highlight">周末一起探店、徒步、看日落。试着用一个共同兴趣，开启一段新对话。</div><div class="people-list" style="padding:0">${people.slice(0,3).map(personRow).join('')}</div>`);break;
 case 'photo':showSheet('生活瞬间',`<img src="${esc(id)}" alt="动态照片大图" style="width:100%;border-radius:12px">`);break;
 case 'report':showSheet('举报内容',`<form data-form="report" data-person="${id}">${selectField('举报原因','reason',['不友善内容','骚扰或广告','冒用资料','其他'])}${field('补充说明','text','textarea','描述你遇到的问题',true)}${formNote()}${submitButton('提交举报')}</form>`);break;
 case 'block':state.blocked.push(id);save();closeOverlay();render();toast('已不再推荐这位用户');break;
 case 'room':room(id);break;case 'next-room':nextRoom();break;
 case 'room-like':button.style.color='#ffb4bc';button.innerHTML=icon('heart');toast('送出一颗小心心');break;case 'gifts':giftPanel();break;case 'select-gift':ui.gift=id;giftPanel();break;
 case 'send-gift':{const prices={flower:10,coffee:20,crown:100},names={flower:'心意鲜花',coffee:'暖心咖啡',crown:'闪耀皇冠'};if(state.points<prices[ui.gift]){toast('金豆还不够，去签到领一点吧');break}state.points-=prices[ui.gift];state.sentGifts=state.sentGifts||[];state.sentGifts.unshift({name:names[ui.gift],host:people.find(p=>p.id===activeRoom).name,time:localDate()});save();render();room(activeRoom);const line=document.createElement('p');line.textContent='我 送出「'+names[ui.gift]+'」';line.style.color='#ffdd8f';document.querySelector('#room-comments').append(line);toast('你的心意已送出')}break;
 case 'book-call':callBooking(id);break;case 'connect-order':{const o=state.orders.find(o=>o.id===id);connectCall(o.hostId,o.id)}break;
 case 'call-toggle':button.classList.toggle('selected');button.setAttribute('aria-pressed',button.classList.contains('selected'));break;
 case 'end-call':clearInterval(callTimer);if(activeCallOrder){const completed=state.orders.find(o=>o.id===activeCallOrder);if(completed)completed.status='已完成';activeCallOrder=null;save();render();}showSheet('连线已结束',`<div class="success-icon">${icon('heart')}</div><h3 class="success-title">谢谢这段相伴时光</h3><p class="success-text">期待下一次，聊到更多有趣的事。</p>${act('close','','返回直播','primary-button')}`);break;
 case 'start-live':uploadData='';showSheet('开启你的直播',`<form data-form="start-live">${field('直播标题','title','text','给这次分享起个名字',true)}${selectField('直播话题','topic',['同城聊天','旅行分享','语言交流','音乐时光'])}${uploadField('选择直播封面')}<p class="form-note">提交后展示主播界面，不会启动真实摄像或推流。</p>${submitButton('预览开播')}</form>`);break;
 case 'edit-profile':editProfile();break;case 'settings':settings();break;
 case 'toggle-setting':state.settings[id]=!state.settings[id];save();button.classList.toggle('on',state.settings[id]);button.setAttribute('aria-checked',state.settings[id]);break;
 case 'language':showSheet('语言与地区',`<form data-form="language">${selectField('所在城市','city',cities,state.city)}${selectField('服务沟通语言偏好','language',['中文','English','Bahasa Melayu','中文 / English'],state.profile.language)}<div class="info-highlight">界面语言：简体中文<br>当前地区：${esc(window.ShizhongRegions?.locationLabel()||'马来西亚')}<br>演示结算货币：马来西亚令吉 RM<br>预约时间以服务所在地标注为准</div>${submitButton('保存偏好')}</form>`);break;
 case 'wallet':wallet();break;case 'recharge':recharge();break;case 'recharge-amount':selectedAmount=Number(id);recharge();break;
 case 'bills':showSheet('钱包账单',state.bills.length?state.bills.map(b=>`<div class="notice-card"><h3>${esc(b.title)}</h3><p>${esc(b.time)} · ${esc(b.method||'体验余额')}</p><strong style="display:block;color:var(--red);margin-top:10px">${b.amount>0?'+':''} RM ${b.amount.toFixed(2)}</strong></div>`).join(''):empty('暂时没有账单','你的体验充值和权益领取会显示在这里。'));break;
 case 'checkin':case 'points':checkin();break;
 case 'do-checkin':if(state.checkin===localDate())break;state.checkin=localDate();state.points+=10;save();render();checkin();toast('签到成功，10 金豆已到账');break;
 case 'coupons':coupons();break;case 'saved':showScreen('心动收藏',`<div class="detail-content">${state.saved.length?`<div class="product-grid">${services.filter(s=>state.saved.includes(s.id)).map(productCard).join('')}</div>`:empty('把喜欢的生活先收好','在服务详情点亮爱心，下次就能轻松找到。','go-home','发现好生活')}</div>`);break;
 case 'stat':if(id==='saved'){menuAction('saved','',button);break}showScreen({follows:'我关注的人',fans:'我的粉丝',visitors:'最近访客'}[id],`<div class="people-list">${(id==='follows'?people.filter(p=>state.follows.includes(p.id)):people.slice(0,id==='fans'?3:2)).map(personRow).join('')||empty('从一位新朋友开始','遇见喜欢的人，可以先关注 TA。')}</div>`);break;
 case 'membership':showSheet('适中会员 PLUS',`<div class="member-card"><div class="member-head">${icon('crown')}把好生活，升级一点</div><p>城市服务与日常陪伴的专属礼遇</p></div><div class="panel" style="margin-bottom:18px">${summary([['专属服务','优先客服与预约支持'],['会员礼遇','每月生活服务体验券'],['社交名片','专属会员标识'],['体验状态',state.member?'已领取会员体验':'可领取 7 天体验']])}</div>${act('claim-member','',state.member?'已领取体验':'领取 7 天会员体验','primary-button yellow',state.member?'disabled':'')}<p class="form-note">演示权益，不自动续费，不产生扣款。</p>`);break;
 case 'claim-member':state.member=true;if(!state.coupons.includes('member'))state.coupons.push('member');save();render();menuAction('membership','',button);toast('会员体验已领取，优惠券已放入账户');break;
 case 'tasks':showSheet('任务中心',`<div class="notice-card"><h3>每日签到 · +10 金豆</h3><p>见面的小礼物，每天都有。</p>${act('checkin','',state.checkin===localDate()?'已完成':'去签到','small-primary','style="margin-top:10px"')}</div><div class="notice-card"><h3>完善资料 · +20 金豆</h3><p>写下你的昵称与个人介绍，让朋友更了解你。</p>${act(state.profileReward?'close':'edit-profile','',state.profileReward?'已领取':'去完善','small-primary','style="margin-top:10px"')}</div><div class="notice-card"><h3>分享生活 · +10 金豆</h3><p>发布第一条动态，记录一个美好瞬间。</p>${act(state.postReward?'close':'compose','',state.postReward?'已领取':'去分享','small-primary','style="margin-top:10px"')}</div>`);break;
 case 'gift-wall':showSheet('我的礼物墙',(state.sentGifts||[]).length?state.sentGifts.map(g=>`<div class="notice-card"><h3>${icon('gift')} ${g.name}</h3><p>送给 ${esc(g.host)} · ${g.time}</p></div>`).join(''):empty('一份心意，一次温暖的相遇','你在直播间送出的礼物，会留在这里。'));break;
 case 'addresses':addresses();break;case 'edit-address':addressForm(id);break;
 case 'default-address':state.address.unshift(state.address.splice(Number(id),1)[0]);save();addresses();break;
 case 'remove-address':state.address.splice(Number(id),1);save();addresses();toast('地址已删除');break;
 case 'help':showHelp();break;case 'feedback':showSheet('意见反馈',`<form data-form="feedback">${selectField('反馈类型','type',['功能建议','页面体验','服务问题','其他'])}${field('你的建议','text','textarea','告诉我们怎样可以做得更好',true)}${field('联系方式','contact','text','选填，方便回复你')}${formNote()}${submitButton('提交反馈')}</form>`);break;
 case 'after-sales':showSheet('售后服务',`<form data-form="after-sales">${selectField('选择订单','order',state.orders.length?state.orders.map(o=>o.id+' · '+o.title):['暂无订单，可直接咨询'])}${selectField('需要什么帮助','reason',['修改服务时间','取消或退款咨询','服务体验反馈','其他问题'])}${field('问题描述','text','textarea','简单描述遇到的问题',true)}${formNote()}${submitButton('提交售后申请')}</form>`);break;
 case 'invite':showSheet('邀请朋友，一起适中',`<div style="text-align:center;padding:20px 10px"><img src="${asset('logo.png')}" alt="适中" style="width:80px;margin:0 auto 18px;border-radius:20px"><h3 style="font-size:22px">好生活，值得一起分享</h3><p class="detail-description" style="margin-top:12px">你的专属邀请码</p><div style="font-size:34px;font-weight:800;color:var(--red);letter-spacing:5px;margin:15px 0">SZ2688</div></div>${act('copy-invite','','复制邀请文案','primary-button')}<p class="form-note">当前为原稿邀请展示，没有实际拉新奖励。</p>`);break;
 case 'merchant':showSheet('成为适中服务伙伴',`<form data-form="merchant">${field('商家 / 服务名称','name','text','让用户认识你的服务',true)}${selectField('服务类别','category',categories.filter(c=>c.id!=='all').map(c=>c.name))}${selectField('所在城市','city',cities,state.city)}${field('联系电话','phone','tel','国家 / 地区代码与联系电话',true)}${field('服务介绍','text','textarea','简单介绍你的特色',true)}${formNote()}${submitButton('提交入驻意向')}</form>`);break;
 case 'add-friend':showSheet('添加新朋友',`<form data-form="add-friend">${field('适中 ID / 手机号','account','text','请输入对方的适中 ID 或手机号',true)}${field('验证消息','text','textarea','你好，我想和你交个朋友。',false,'你好，很高兴认识你！')}${formNote()}${submitButton('发送好友申请')}</form>`);break;
 case 'new-friends':showSheet('新的朋友',`<div class="people-list" style="padding:0">${people.slice(0,2).map(p=>`<div class="person-row"><img class="avatar" src="${asset(p.photo)}" alt="${p.name}"><div class="person-content"><h3 style="font-size:14px">${p.name}</h3><p>你好，一起发现城市生活吧！</p></div>${act('accept-friend',p.id,state.greeted.includes(p.id)?'发消息':'接受','greet-btn')}</div>`).join('')}</div>${state.friendRequests?.map(f=>`<div class="notice-card"><h3>${esc(f.account)}</h3><p>申请已记录 · 等待对方通过（演示）</p></div>`).join('')||''}`);break;
 case 'accept-friend':if(!state.greeted.includes(id))state.greeted.push(id);save();openChat(id);toast('现在可以开始聊天啦');break;
 case 'contacts':showScreen('通讯录',`<div class="people-list">${people.filter(p=>!state.blocked.includes(p.id)).map(personRow).join('')}</div>`);break;
 case 'create-group':showSheet('创建群聊',`<form data-form="group">${field('群名称','name','text','给你们的小圈子起个名字',true)}${selectField('城市','city',cities,state.city)}${field('群介绍','desc','textarea','聊什么，玩什么，欢迎什么样的朋友',true)}${submitButton('创建群组')}</form>`);break;
 case 'discover-groups':showScreen('发现群组',`<div style="padding-top:10px">${defaultGroups.map(g=>groupRow(g,true)).join('')}</div>`);break;
 case 'group-detail':groupDetail(id);break;case 'join-group':if(!state.joined.includes(id))state.joined.push(id);save();render();openChat(id);toast('已加入群组');break;
 case 'leave-group':state.joined=state.joined.filter(g=>g!==id);save();render();closeOverlay();toast('已退出群组');break;
 case 'chat-emoji':{const el=document.querySelector('input[name="text"]');el.value+=' ❤️';el.focus()}break;
 case 'chat-options':showSheet('会话设置',`<div class="panel list-panel" style="margin:0">${id!=='support'?listRow('user','查看个人主页','person','',id):''}${listRow('shield','聊天与隐私说明','privacy')}</div><p class="form-note">聊天为本地演示，输入内容不会发送给其他人。</p>${act('chat',id,'返回会话','primary-button')}`);break;
 case 'notifications':notifications();break;
 case 'privacy':showSheet('隐私与使用说明',`<div class="notice-card"><h3>本地设计体验</h3><p>当前为适中 H5 交互原稿。人物、商家、距离、评价和直播人数均为示例，照片用于界面设计展示。</p></div><div class="notice-card"><h3>数据留在本机</h3><p>表单、聊天、动态和图片保存在当前浏览器，不会发送到服务器。支付不会扣款，连线不会启用摄像头或麦克风。</p></div><div class="notice-card"><h3>尊重彼此</h3><p>在真实产品中，我们希望每次相遇都建立在尊重、友善与自愿的基础上。</p></div>`);break;
 case 'about':showSheet('关于适中',`<img src="${asset('logo.png')}" alt="适中" style="width:86px;margin:12px auto 22px;border-radius:20px"><h3 class="success-title">适中 SHIZHONG</h3><p class="success-text">在大马，好好生活。<br>生活服务 · 社交 · 直播 · 通讯</p><div class="panel">${summary([['版本','1.0 H5 交互设计原稿'],['地区','Malaysia'],['语言','简体中文'],['摄影素材','Unsplash / Pexels'],['品牌主视觉','原创 AI 生活方式图']])}</div>`);break;
 case 'copy-id':copyText('88002688','适中 ID 已复制');break;case 'copy-invite':copyText('和我一起发现大马好生活！适中邀请码：SZ2688','邀请文案已复制');break;
 case 'share-profile':if(window.ShizhongPersonalQR)window.ShizhongPersonalQR.open();else toast('二维码正在准备，请稍后重试');break;
 case 'copy-profile':copyText('适中 | '+state.profile.name+'\n'+state.profile.bio+'\n适中 ID：88002688','名片文案已复制');break;
 case 'export-data':{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='适中-本地体验数据.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('体验数据已导出')}break;
 case 'reset-data':showSheet('重新开始体验？',`<p>将清除当前浏览器中的演示订单、动态和聊天记录。你可以先在设置中导出演示数据。</p><div class="button-row">${act('settings','','保留数据','secondary-button')}${act('reset-confirm','','重置原稿','primary-button')}</div>`);break;
 case 'reset-confirm':state=JSON.parse(JSON.stringify(initialState));save();navigate('home');toast('已恢复初始体验');break;
 default:toast('请从页面选择一项操作');
}}
async function copyText(value,message){try{await navigator.clipboard.writeText(value);toast(message)}catch(_){showSheet('复制内容',`<textarea class="field" readonly aria-label="待复制内容">${esc(value)}</textarea><p class="form-note">长按或全选后复制。</p>`)}}
document.addEventListener('click',event=>{const button=event.target.closest('[data-action]');if(button&&!button.disabled){menuAction(button.dataset.action,button.dataset.id||'',button);return}if(event.target.matches('[data-dismiss]'))closeOverlay()});
document.addEventListener('submit',event=>{const form=event.target.closest('[data-form]');if(!form)return;event.preventDefault();if(!form.reportValidity())return;const data=Object.fromEntries(new FormData(form));for(const [k,v] of Object.entries(data)){if(typeof v==='string')data[k]=v.trim()}for(const input of form.querySelectorAll('input[type="tel"]')){const value=data[input.name];if(value&&(!/^\+?[0-9 ()-]{7,20}$/.test(value)||value.replace(/\D/g,'').length<7)){toast('请填写有效的电话号码');input.focus();return}}const kind=form.dataset.form;
 if(['profile','language','address','group','merchant'].includes(kind)||(kind==='request'&&!form.dataset.service)){const location=flowFormLocation(form);if(location){data.location={...location};data.city=location.cityName||data.city}}delete data.locationData;
 if(kind==='search')search(data.q);
 else if(kind==='chat-search')search(data.q,true);
 else if(kind==='request'){if(!validateRequiredText(form,data))return;createOrder(data,form.dataset.category,form.dataset.service)}
 else if(kind==='greet'){if(!data.message)return toast('写下一句问候吧');sendChat(form.dataset.person,data.message);if(!state.greeted.includes(form.dataset.person))state.greeted.push(form.dataset.person);save();render();openChat(form.dataset.person)}
 else if(kind==='chat'){if(!data.text)return;const id=form.dataset.chat;sendChat(id,data.text);if(id==='support')sendChat(id,'已记下你的问题。你可以在「我的订单」查看需求，或从「帮助与反馈」提交详细建议。本会话是自动演示回复。',false);render();openChat(id);document.querySelector('.chat-composer input').focus()}
 else if(kind==='post'){if(!data.text)return toast('先写一点想分享的内容吧');state.posts.unshift({id:'f'+Date.now(),person:'self',text:data.text,imageData:uploadData,place:data.place||state.city,topic:data.topic,visibility:data.visibility,likes:0,time:'刚刚'});if(!state.postReward){state.points+=10;state.postReward=true}save();closeOverlay();ui.page='social';ui.socialTab='feed';ui.socialFilter='推荐';render();document.querySelector('#app').scrollTo({top:0,behavior:'instant'});toast('已发布，生活的这一刻被好好记录了')}
 else if(kind==='comment'){if(!data.text)return;const id=form.dataset.post;if(!state.comments[id])state.comments[id]=[];state.comments[id].push({name:state.profile.name,text:data.text});save();render();comments(id)}
 else if(kind==='live-comment'){if(!data.text)return;const line=document.createElement('p');const b=document.createElement('b');b.textContent=state.profile.name;line.append(b,document.createTextNode(data.text));const box=document.querySelector('#room-comments');box.append(line);box.scrollTop=box.scrollHeight;form.reset()}
 else if(kind==='book-call'){if(new Date(data.date+'T'+data.time+':00+08:00').getTime()<=Date.now())return toast('这个时段已过去，请选择之后的时间');const p=people.find(p=>p.id===form.dataset.person);const order={id:'SZ'+Date.now().toString().slice(-9),category:'call',title:'面对面 · '+p.name,hostId:p.id,data:{...data,host:p.name},total:p.price*parseInt(data.duration,10)/10,status:'待服务',created:new Date().toLocaleString('zh-CN',{timeZone:'Asia/Kuala_Lumpur',hour12:false})};state.orders.unshift(order);save();render();orderSuccess(order)}
 else if(kind==='profile'){
  if(!data.name)return toast('请填写昵称');
  if(form.querySelector('[data-avatar-upload]')?.dataset.reading==='true')return toast('头像正在读取，请稍等片刻');
  const previous={profile:{...state.profile},city:state.city,location:state.location&&{...state.location},profileReward:state.profileReward,points:state.points};
  flowApplyLocation(data.location,data.city);
  state.profile={...state.profile,...data,photo:uploadData||state.profile.photo};
  if(data.bio&&!state.profileReward){state.profileReward=true;state.points+=20}
  if(!save()){
   state.profile=previous.profile;state.city=previous.city;state.location=previous.location;state.profileReward=previous.profileReward;state.points=previous.points;
   return toast('头像文件较大，浏览器存储空间不足，请换一张较小的图片');
  }
  closeOverlay();render();toast('个人资料已保存');
 }
 else if(kind==='social-filter'){ui.cityFilter=data.city;ui.interestFilter=data.interest;closeOverlay();render()}
 else if(kind==='language'){flowApplyLocation(data.location,data.city);state.profile.language=data.language;save();closeOverlay();render();toast('沟通偏好已保存')}
 else if(kind==='address'){if(!validateRequiredText(form,data))return;if((data.location?.countryCode||'MY')==='MY'&&!/^\d{5}$/.test(data.postcode||''))return toast('请输入 5 位马来西亚邮编');if((data.postcode||'').length>20)return toast('邮编请控制在 20 个字符以内');if(form.dataset.address==='new')state.address.push(data);else state.address[Number(form.dataset.address)]=data;save();addresses();toast('地址已保存')}
 else if(kind==='recharge'){state.wallet+=selectedAmount;state.bills.unshift({title:'演示充值',amount:selectedAmount,method:data.method,time:new Date().toLocaleString('zh-CN')});save();render();wallet();toast('演示余额已到账，未发生真实扣款')}
 else if(kind==='group'){if(!validateRequiredText(form,data))return;const id='g'+Date.now();state.groups.unshift({id,...data,count:1,icon:'group'});state.joined.push(id);save();render();openChat(id);toast('群组已创建')}
 else if(kind==='add-friend'){if(!data.account)return toast('请输入适中 ID 或手机号');state.friendRequests=state.friendRequests||[];state.friendRequests.unshift(data);save();closeOverlay();toast('好友申请已保存在本地')}
 else if(kind==='start-live'){if(!data.title)return toast('请填写直播标题');showScreen('我的直播预览',`<div class="detail-hero"><img src="${uploadData||asset('city-kl.jpg')}" alt="直播封面"></div><div class="detail-content"><span class="live-pill">${liveBars()} 主播预览</span><h2 style="margin-top:20px">${esc(data.title)}</h2><p class="detail-description">${esc(data.topic)} · 0 位观众<br>这里将承载你的实时直播画面。当前没有启动推流。</p><div class="button-row">${act('close','','结束预览','primary-button')}</div></div>`)}
 else if(['feedback','after-sales','merchant','report'].includes(kind)){if(!validateRequiredText(form,data))return;state.feedback.unshift({kind,...data,time:Date.now()});save();showSheet('已记录你的'+({feedback:'建议','after-sales':'售后申请',merchant:'入驻意向',report:'举报'}[kind]),`<div class="success-icon">${icon('check')}</div><h3 class="success-title">谢谢你的认真填写</h3><p class="success-text">内容已保存在本地体验数据中。<br>设计原稿不会向外部发送信息。</p>${act('close','','完成','primary-button')}`)}
});
function validateRequiredText(form,data){for(const input of form.querySelectorAll('[required]')){if(typeof data[input.name]==='string'&&!data[input.name]){toast('请填写完整必填信息');input.focus();return false}}return true}
document.addEventListener('change',event=>{
 const el=event.target;
 if(el.matches('input[type="file"]')){
  const file=el.files?.[0];if(!file)return;
  el.photoReadToken=Symbol('new-selection');
  uploadData='';
  const avatar=el.dataset.avatarUpload==='true';
  const types=avatar?['image/jpeg','image/png','image/gif','image/webp']:['image/jpeg','image/png','image/webp'];
  if(!types.includes(file.type)){el.value='';toast(avatar?'请选择 JPG、PNG/APNG、GIF 或 WebP 图片':'请选择 JPG、PNG 或 WebP 图片');return}
  const limit=avatar?2000000:1500000;
  if(file.size>limit){el.value='';toast(`请选择小于 ${avatar?'2':'1.5'} MB 的图片`);return}
  const reader=new FileReader(),readToken=Symbol('photo');el.photoReadToken=readToken;el.dataset.reading='true';
  reader.onload=()=>{
   if(el.photoReadToken!==readToken)return;
   delete el.dataset.reading;
   if(!document.querySelector('#overlay-root')?.contains(el)&&!window.ShizhongRegions?.containsPreservedNode(el))return;
   uploadData=String(reader.result||'');
   const preview=el.parentElement.querySelector('.upload-preview');
   if(preview){preview.src=uploadData;preview.style.display='block'}
  };
  reader.onerror=()=>{if(el.photoReadToken===readToken){delete el.dataset.reading;el.value='';toast('头像读取失败，请重新选择图片')}};
  reader.readAsDataURL(file);
 }
 if(el.matches('[name="duration"]')){const p=people.find(x=>x.id===el.closest('form').dataset.person);const total=document.querySelector('#call-total');if(total&&p)total.textContent='RM '+(p.price*parseInt(el.value,10)/10).toFixed(2)}
});
document.addEventListener('keydown',event=>{if(!currentOverlay)return;if(event.key==='Escape'){closeOverlay();return}if(event.key==='Tab'){const els=[...document.querySelectorAll('#overlay-root button:not(:disabled),#overlay-root input,#overlay-root textarea,#overlay-root select,#overlay-root [tabindex="0"]')].filter(el=>el.offsetParent!==null&&!el.closest('[inert]'));if(!els.length)return;const first=els[0],last=els[els.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}});
let touchStartY=0;document.addEventListener('touchstart',event=>{if(event.target.closest('.live-room')&&!event.target.closest('input,button,.room-comments,.lr-comments,.lr-panel-layer,.lr-composer'))touchStartY=event.touches[0].clientY;else touchStartY=0},{passive:true});document.addEventListener('touchend',event=>{if(touchStartY&&currentOverlay?.kind==='room'&&touchStartY-event.changedTouches[0].clientY>90){nextRoom()}touchStartY=0},{passive:true});

function nextDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuala_Lumpur',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(Date.now()+86400000))}
