'use strict';
/*
 * Gift catalogue (source language: zh-CN). Prices are demo RM amounts paid from the local demo
 * wallet; goldBeanPrice is the live-room price in gold beans. Rarity labels describe the visual
 * collection only; nothing here can be traded or refunded.
 *
 * Translations: names/descriptions via data/i18n/<locale>/gifts.js (tc('gifts', id, field)),
 * category / rarity / series labels via td('gifts.<field>', value) in the locale files.
 * Artwork: window.SHIZHONG_GIFT_ART[id] (assets/gift-art/manifest.js) overrides `image`.
 */
window.SHIZHONG_GIFT_DATA = {
  gifts: [
    {
      id: 'ribbon-heart',
      name: '丝带心意',
      price: 100,
      category: '心意礼物',
      rarity: '心意款',
      accent: '#E9718F',
      effect: 'hearts',
      image: 'gifts/ribbon-heart.webp',
      description: '把一句小小的喜欢系上柔软丝带，让你的问候在此刻轻轻发亮。',
    },
    {
      id: 'teddy-bear',
      name: '晚安抱抱熊',
      price: 1800,
      category: '趣味珍藏',
      rarity: '珍藏款',
      accent: '#CFA677',
      effect: 'hearts',
      image: 'gifts/teddy-bear.webp',
      description: '留一只毛绒小熊在礼物角，替你陪伴每个需要被温柔接住的夜晚。',
    },
    {
      id: 'rose',
      name: '一枝初见玫瑰',
      price: 500,
      category: '心意礼物',
      rarity: '心意款',
      accent: '#E85A70',
      effect: 'hearts',
      image: 'gifts/rose.webp',
      description: '一枝玫瑰就能点亮相遇的瞬间，愿今天的聊天从这抹花色开始。',
    },
    {
      id: 'gift-box',
      name: '蝴蝶结惊喜盒',
      price: 2600,
      category: '心意礼物',
      rarity: '心意款',
      accent: '#EA9987',
      effect: 'confetti',
      image: 'gifts/gift-box.webp',
      description: '拆开漂亮的蝴蝶结，把没来得及说出口的祝福装进这一份惊喜。',
    },
    {
      id: 'birthday-cake',
      name: '莓果许愿蛋糕',
      price: 3800,
      category: '心意礼物',
      rarity: '心意款',
      accent: '#F196A7',
      effect: 'confetti',
      image: 'gifts/birthday-cake.webp',
      description: '点亮一支小蜡烛，把今天值得庆祝的好消息留在甜甜的莓果色里。',
    },
    {
      id: 'bouquet',
      name: '春日满怀花束',
      price: 5200,
      category: '心意礼物',
      rarity: '心意款',
      accent: '#E98AAA',
      effect: 'hearts',
      image: 'gifts/bouquet.webp',
      description: '把春日的花色捧到你面前，愿这束柔和的绽放为平常一天添些明亮。',
    },
    {
      id: 'balloon',
      name: '晴空许愿气球',
      price: 800,
      category: '心意礼物',
      rarity: '心意款',
      accent: '#81B9DF',
      effect: 'confetti',
      image: 'gifts/balloon.webp',
      description: '放飞一颗轻盈气球，让你的好心情沿着天空慢慢升起。',
    },
    {
      id: 'butterfly',
      name: '琉彩蝶影',
      price: 6800,
      category: '趣味珍藏',
      rarity: '珍藏款',
      accent: '#B693DD',
      effect: 'stars',
      image: 'gifts/butterfly.webp',
      description: '让一抹彩蝶停在收藏页边，陪你记住那些不经意却动人的小发现。',
    },
    {
      id: 'headphones',
      name: '同频音乐耳机',
      price: 9000,
      category: '趣味珍藏',
      rarity: '珍藏款',
      accent: '#8E9DE4',
      effect: 'stars',
      image: 'gifts/headphones.webp',
      description: '戴上想象中的音乐耳机，把喜欢的旋律和今天的故事一起分享给懂你的人。',
    },
    {
      id: 'coffee',
      name: '午后暖心拿铁',
      price: 300,
      category: '心意礼物',
      rarity: '心意款',
      accent: '#BD967B',
      effect: 'hearts',
      image: 'gifts/coffee.webp',
      description: '递上一杯冒着柔软热气的拿铁，陪你把忙碌的一天聊得慢一点。',
    },
    {
      id: 'diamond-ring',
      name: '星光约定指环',
      price: 58000,
      category: '闪耀典藏',
      rarity: '典藏款',
      accent: '#AECFE5',
      effect: 'stars',
      image: 'gifts/diamond-ring.webp',
      description: '用一圈细碎星光装点这次相遇，把认真听见的每一句话好好珍藏。',
    },
    {
      id: 'crescent-moon',
      name: '月牙晚安灯',
      price: 22000,
      category: '趣味珍藏',
      rarity: '珍藏款',
      accent: '#F0D599',
      effect: 'orbit',
      image: 'gifts/crescent-moon.webp',
      description: '借一弯温柔月牙作夜灯，让晚归的心情也有一处安静发亮的角落。',
    },
    {
      id: 'golden-star',
      name: '闪闪鼓励星',
      price: 1200,
      category: '趣味珍藏',
      rarity: '珍藏款',
      accent: '#E9BF5A',
      effect: 'stars',
      image: 'gifts/golden-star.webp',
      description: '送你一颗金色小星星，为今天认真生活的自己点亮一个小小勋章。',
    },
    {
      id: 'trophy',
      name: '高光时刻奖杯',
      price: 35000,
      category: '闪耀典藏',
      rarity: '典藏款',
      accent: '#DEB65F',
      effect: 'confetti',
      image: 'gifts/trophy.webp',
      description: '把这一刻的掌声放进金色奖杯，和你一起庆祝努力之后的小小成就。',
    },
    {
      id: 'diamond',
      name: '冰蓝光棱宝石',
      price: 45000,
      category: '闪耀典藏',
      rarity: '典藏款',
      accent: '#86C9E5',
      effect: 'stars',
      image: 'gifts/diamond.webp',
      description: '清透的蓝色光棱为礼物陈列添一束亮光，也映出此刻真诚的欣赏。',
    },
    {
      id: 'crown',
      name: '星河加冕皇冠',
      price: 72000,
      category: '闪耀典藏',
      rarity: '典藏款',
      accent: '#E8BE67',
      effect: 'royal',
      image: 'gifts/crown.webp',
      description: '为愿意分享生活的你戴上星河皇冠，愿你在自己的故事里自在闪耀。',
    },
    {
      id: 'rocket',
      name: '逐梦星际火箭',
      price: 185000,
      category: '臻享臻藏',
      rarity: '臻藏款',
      accent: '#EB896C',
      effect: 'launch',
      image: 'gifts/rocket.webp',
      description: '让星际火箭带着今晚的愿望升空，把对明天的期待画成一条明亮轨迹。',
    },
    {
      id: 'racing-car',
      name: '流光疾风跑车',
      price: 105000,
      category: '闪耀典藏',
      rarity: '典藏款',
      accent: '#E66A72',
      effect: 'launch',
      image: 'gifts/racing-car.webp',
      description: '把热情涂成流光车身，让这辆小小跑车陪你的快乐向前多走一程。',
    },
    {
      id: 'yacht',
      name: '蔚蓝海岸游艇',
      price: 138000,
      category: '臻享臻藏',
      rarity: '臻藏款',
      accent: '#70B9D8',
      effect: 'confetti',
      image: 'gifts/yacht.webp',
      description: '在想象的蔚蓝海面展开白色甲板，邀你暂时放慢脚步听一会儿海风。',
    },
    {
      id: 'castle',
      name: '鎏金童话城堡',
      price: 200000,
      category: '臻享臻藏',
      rarity: '臻藏款',
      accent: '#E2BC76',
      effect: 'royal',
      image: 'gifts/castle.webp',
      description: '点亮层层城堡窗灯，为珍贵的相遇搭起一座温暖而盛大的童话舞台。',
    },
    {
      id: 'airplane',
      name: '云端环游航班',
      price: 120000,
      category: '闪耀典藏',
      rarity: '典藏款',
      accent: '#91B6DE',
      effect: 'launch',
      image: 'gifts/airplane.webp',
      description: '把一张想象中的登机牌送给你，愿我们总能聊起下一座想去的城市。',
    },
    {
      id: 'unicorn',
      name: '虹光梦境独角兽',
      price: 88000,
      category: '闪耀典藏',
      rarity: '典藏款',
      accent: '#C5A1E3',
      effect: 'stars',
      image: 'gifts/unicorn.webp',
      description: '让披着虹光的独角兽走进收藏花园，替你守住一点天马行空的童心。',
    },
    {
      id: 'panda',
      name: '竹叶团子熊猫',
      price: 12000,
      category: '趣味珍藏',
      rarity: '珍藏款',
      accent: '#8ABD99',
      effect: 'hearts',
      image: 'gifts/panda.webp',
      description: '圆滚滚的熊猫抱着一枝竹叶来报到，给今天的聊天添一份松弛和可爱。',
    },
    {
      id: 'dragon',
      name: '赤金祥云神龙',
      price: 195000,
      category: '臻享臻藏',
      rarity: '臻藏款',
      accent: '#DAB260',
      effect: 'royal',
      image: 'gifts/dragon.webp',
      description: '让赤金神龙穿过层层祥云，为这场热闹相聚留下舒展而明亮的祝福。',
    },
    {
      id: 'crystal-ball',
      name: '紫雾心愿水晶球',
      price: 28000,
      category: '趣味珍藏',
      rarity: '珍藏款',
      accent: '#AE8CCF',
      effect: 'orbit',
      image: 'gifts/crystal-ball.webp',
      description: '将一个小愿望收进紫雾水晶球，让柔和光晕陪你慢慢把未来说给朋友听。',
    },
    {
      id: 'satellite',
      name: '遥远问候卫星',
      price: 150000,
      category: '臻享臻藏',
      rarity: '臻藏款',
      accent: '#9DB4D4',
      effect: 'orbit',
      image: 'gifts/satellite.webp',
      description: '让一颗小卫星绕过漫长距离，把此刻的问候稳稳送到彼此的心里。',
    },
    {
      id: 'earth',
      name: '蔚蓝同心地球',
      price: 162000,
      category: '臻享臻藏',
      rarity: '臻藏款',
      accent: '#72BBCA',
      effect: 'orbit',
      image: 'gifts/earth.webp',
      description: '把共同生活的蓝色星球捧在掌心，愿不同城市的我们也能分享同一份温柔。',
    },
    {
      id: 'ringed-planet',
      name: '星环漫游行星',
      price: 175000,
      category: '臻享臻藏',
      rarity: '臻藏款',
      accent: '#D0B28C',
      effect: 'orbit',
      image: 'gifts/ringed-planet.webp',
      description: '沿着柔亮的星环慢慢漫游，给那些聊不完的想象留下一整片夜空。',
    },
    {
      id: 'violin',
      name: '暮色弦语小提琴',
      price: 16000,
      category: '趣味珍藏',
      rarity: '珍藏款',
      accent: '#B78365',
      effect: 'stars',
      image: 'gifts/violin.webp',
      description: '让木色琴弦替你奏起一段轻柔旋律，陪这场谈话停在恰到好处的温度。',
    },
    {
      id: 'love-letter',
      name: '悄悄心意信笺',
      price: 180,
      category: '心意礼物',
      rarity: '心意款',
      accent: '#DD8D9B',
      effect: 'hearts',
      image: 'gifts/love-letter.webp',
      description: '把一句惦念折进小小信封，让不善言辞的温柔也能被认真看见。',
    },
    {
      id: 'oriental-tongxin-knot',
      name: '同心结',
      price: 100,
      category: '盛世华章',
      rarity: '入门款',
      series: '盛世华章',
      subseries: '盛世雅物',
      tier: '入门',
      accent: '#BE2534',
      effect: 'hearts',
      orientalEffect: 'knot',
      goldBeanPrice: 9,
      image: 'gift-art/oriental/oriental-tongxin-knot.webp',
      description:
        '一枚朱红盘长结垂着细金穗，把想说的祝福系在一起；适合送给刚认识的新朋友，也能放在主页作小巧挂件。',
    },
    {
      id: 'oriental-lantern',
      name: '灯笼',
      price: 280,
      category: '盛世华章',
      rarity: '入门款',
      series: '盛世华章',
      subseries: '盛世雅物',
      tier: '入门',
      accent: '#D44627',
      effect: 'confetti',
      orientalEffect: 'lantern',
      goldBeanPrice: 19,
      image: 'gift-art/oriental/oriental-lantern.webp',
      description: '描金宫灯点亮暖黄烛光，沿着夜色缓缓升起；把团圆与平安的心意送到正在聊天的人面前。',
    },
    {
      id: 'oriental-folding-fan',
      name: '折扇',
      price: 520,
      category: '盛世华章',
      rarity: '入门款',
      series: '盛世华章',
      subseries: '盛世雅物',
      tier: '入门',
      accent: '#966747',
      effect: 'stars',
      orientalEffect: 'fan',
      goldBeanPrice: 39,
      image: 'gift-art/oriental/oriental-folding-fan.webp',
      description: '一柄乌木折扇展开层叠水墨山峦，合拢时留下一缕金色光迹；适合送给喜欢旅行与山水的朋友。',
    },
    {
      id: 'oriental-blue-white-porcelain',
      name: '青花瓷',
      price: 2600,
      category: '盛世华章',
      rarity: '进阶款',
      series: '盛世华章',
      subseries: '盛世雅物',
      tier: '进阶',
      accent: '#386898',
      effect: 'orbit',
      orientalEffect: 'porcelain',
      goldBeanPrice: 199,
      image: 'gift-art/oriental/oriental-blue-white-porcelain.webp',
      description: '白瓷小瓶映着细密青花缠枝纹，旋转间显出柔和釉光；让一份安静的雅意留在好友的礼物收藏里。',
    },
    {
      id: 'oriental-phoenix-flight',
      name: '凤凰于飞',
      price: 7800,
      category: '盛世华章',
      rarity: '进阶款',
      series: '盛世华章',
      subseries: '盛世雅物',
      tier: '进阶',
      accent: '#C84C42',
      effect: 'royal',
      orientalEffect: 'phoenix',
      wearable: 'avatar',
      goldBeanPrice: 520,
      image: 'gift-art/oriental/oriental-phoenix-flight.webp',
      description: '赤金凤凰舒展羽翼，尾羽如轻柔绸带掠过屏幕；送给并肩前行的人，纪念彼此照亮的一刻。',
    },
    {
      id: 'oriental-pipa-song',
      name: '琵琶行',
      price: 4500,
      category: '盛世华章',
      rarity: '进阶款',
      series: '盛世华章',
      subseries: '盛世雅物',
      tier: '进阶',
      accent: '#B28355',
      effect: 'stars',
      orientalEffect: 'pipa',
      goldBeanPrice: 399,
      image: 'gift-art/oriental/oriental-pipa-song.webp',
      description: '梨花木琵琶立在云纹绸带间，琴弦泛起细碎金芒；把一段无需言说的悠长心绪送进今晚的会话。',
    },
    {
      id: 'oriental-golden-dragon',
      name: '龙腾',
      price: 48000,
      category: '盛世华章',
      rarity: '豪华款',
      series: '盛世华章',
      subseries: '盛世雅物',
      tier: '豪华',
      accent: '#D29B37',
      effect: 'royal',
      orientalEffect: 'dragon',
      wearable: 'avatar',
      goldBeanPrice: 2999,
      image: 'gift-art/oriental/oriental-golden-dragon.webp',
      description: '鎏金祥龙穿过层叠云海腾空盘旋，龙鳞映着故宫红光；用一份壮阔礼物为朋友的重要时刻喝彩。',
    },
    {
      id: 'oriental-nine-ding',
      name: '九鼎',
      price: 60000,
      category: '盛世华章',
      rarity: '豪华款',
      series: '盛世华章',
      subseries: '盛世雅物',
      tier: '豪华',
      accent: '#A9783D',
      effect: 'royal',
      orientalEffect: 'ding',
      goldBeanPrice: 3999,
      image: 'gift-art/oriental/oriental-nine-ding.webp',
      description: '青铜古鼎承着九重云纹，鼎耳与金边在光束中渐次显现；适合纪念一项稳稳落地的重要成果。',
    },
    {
      id: 'oriental-qilin-treasure',
      name: '麒麟送宝',
      price: 72000,
      category: '盛世华章',
      rarity: '豪华款',
      series: '盛世华章',
      subseries: '盛世雅物',
      tier: '豪华',
      accent: '#C88B3F',
      effect: 'confetti',
      orientalEffect: 'qilin',
      goldBeanPrice: 5200,
      image: 'gift-art/oriental/oriental-qilin-treasure.webp',
      description: '瑞兽麒麟踏着祥云送来一只缀金宝匣，步伐轻快而隆重；把好事临门的祝愿留给特别的伙伴。',
    },
    {
      id: 'oriental-landscape-scroll',
      name: '江山如画',
      price: 138000,
      category: '盛世华章',
      rarity: '顶级款',
      series: '盛世华章',
      subseries: '盛世雅物',
      tier: '顶级',
      accent: '#887451',
      effect: 'orbit',
      orientalEffect: 'scroll',
      goldBeanPrice: 12888,
      image: 'gift-art/oriental/oriental-landscape-scroll.webp',
      description: '长卷徐徐展开，黛色山峦、云水与金色楼阁在纸上相遇；把眼前的宽阔风景送给愿意同行的人。',
    },
    {
      id: 'oriental-phoenix-crown',
      name: '凤冠霞帔',
      price: 168000,
      category: '盛世华章',
      rarity: '顶级款',
      series: '盛世华章',
      subseries: '盛世雅物',
      tier: '顶级',
      accent: '#C59042',
      effect: 'royal',
      orientalEffect: 'crown',
      wearable: 'avatar',
      goldBeanPrice: 18888,
      image: 'gift-art/oriental/oriental-phoenix-crown.webp',
      description: '点翠凤冠嵌着金珠与红色流苏，霞帔般的柔光在身后舒展；为值得珍惜的喜庆日子添一场华美仪式。',
    },
    {
      id: 'oriental-heavenly-craft',
      name: '天工开物',
      price: 200000,
      category: '盛世华章',
      rarity: '顶级款',
      series: '盛世华章',
      subseries: '盛世雅物',
      tier: '顶级',
      accent: '#D19B55',
      effect: 'royal',
      orientalEffect: 'craft',
      goldBeanPrice: 29999,
      image: 'gift-art/oriental/oriental-heavenly-craft.webp',
      description:
        '匠作宝匣汇聚建筑飞檐、青花瓷片与龙凤金纹，层层打开如一座微缩工艺殿堂；献给认真创造生活的人。',
    },
    {
      id: 'oriental-azure-dragon',
      name: '青龙出海',
      price: 82000,
      category: '盛世华章',
      rarity: '豪华款',
      series: '盛世华章',
      subseries: '上古四灵',
      tier: '豪华',
      accent: '#4A9A91',
      effect: 'orbit',
      orientalEffect: 'azure-dragon',
      wearable: 'avatar',
      goldBeanPrice: 8888,
      image: 'gift-art/oriental/oriental-azure-dragon.webp',
      description: '青碧灵龙越过墨色海浪，长须与云气带出流动的翠金光；这份四灵藏品象征向新的方向出发。',
    },
    {
      id: 'oriental-white-tiger',
      name: '白虎踏星',
      price: 76000,
      category: '盛世华章',
      rarity: '豪华款',
      series: '盛世华章',
      subseries: '上古四灵',
      tier: '豪华',
      accent: '#AEB9C9',
      effect: 'stars',
      orientalEffect: 'white-tiger',
      wearable: 'avatar',
      goldBeanPrice: 6999,
      image: 'gift-art/oriental/oriental-white-tiger.webp',
      description: '银白猛虎踩过深蓝星轨，额间金纹随着步伐闪亮；为勇敢迈出一步的朋友留下利落而坚定的祝福。',
    },
    {
      id: 'oriental-vermilion-bird',
      name: '朱雀涅槃',
      price: 98000,
      category: '盛世华章',
      rarity: '顶级款',
      series: '盛世华章',
      subseries: '上古四灵',
      tier: '顶级',
      accent: '#D15036',
      effect: 'royal',
      orientalEffect: 'vermilion-bird',
      wearable: 'avatar',
      goldBeanPrice: 9999,
      image: 'gift-art/oriental/oriental-vermilion-bird.webp',
      description: '朱雀从金红羽焰中展翼而起，细小火羽化作温暖光点；送给刚走过低谷、再次拥抱新开始的人。',
    },
    {
      id: 'oriental-black-tortoise',
      name: '玄武御天',
      price: 92000,
      category: '盛世华章',
      rarity: '顶级款',
      series: '盛世华章',
      subseries: '上古四灵',
      tier: '顶级',
      accent: '#637C79',
      effect: 'orbit',
      orientalEffect: 'black-tortoise',
      wearable: 'avatar',
      goldBeanPrice: 9888,
      image: 'gift-art/oriental/oriental-black-tortoise.webp',
      description: '龟蛇相依的玄武浮在深色云台之上，甲纹托起一圈温润的金色屏障；愿所爱之人安稳从容。',
    },
    {
      id: 'oriental-golden-calligraphy',
      name: '一字千金',
      price: 380,
      category: '盛世华章',
      rarity: '入门款',
      series: '盛世华章',
      subseries: '金榜题名',
      tier: '入门',
      accent: '#A78147',
      effect: 'stars',
      orientalEffect: 'calligraphy',
      goldBeanPrice: 29,
      image: 'gift-art/oriental/oriental-golden-calligraphy.webp',
      description: '羊毫笔蘸开浓墨，在宣纸上写出一枚泛金的吉字；为正在努力的朋友送上一点鼓励与文采。',
    },
    {
      id: 'oriental-top-scholar',
      name: '高中状元',
      price: 18000,
      category: '盛世华章',
      rarity: '进阶款',
      series: '盛世华章',
      subseries: '金榜题名',
      tier: '进阶',
      accent: '#C33E35',
      effect: 'confetti',
      orientalEffect: 'scholar',
      goldBeanPrice: 999,
      image: 'gift-art/oriental/oriental-top-scholar.webp',
      description: '绛红状元帽缀着金色花翎，卷轴在旁缓缓展开；祝贺考试、面试或作品发布时的每一份认真准备。',
    },
    {
      id: 'oriental-carp-dragon-gate',
      name: '鱼跃龙门',
      price: 30000,
      category: '盛世华章',
      rarity: '豪华款',
      series: '盛世华章',
      subseries: '金榜题名',
      tier: '豪华',
      accent: '#D39B54',
      effect: 'launch',
      orientalEffect: 'carp',
      goldBeanPrice: 1888,
      image: 'gift-art/oriental/oriental-carp-dragon-gate.webp',
      description: '赤金锦鲤冲出浪花跃向汉白玉龙门，水滴化作细碎星点；为迎来转机的好消息送上掌声。',
    },
    {
      id: 'oriental-ao-champion',
      name: '独占鳌头',
      price: 112000,
      category: '盛世华章',
      rarity: '顶级款',
      series: '盛世华章',
      subseries: '金榜题名',
      tier: '顶级',
      accent: '#B8833E',
      effect: 'royal',
      orientalEffect: 'ao',
      goldBeanPrice: 11999,
      image: 'gift-art/oriental/oriental-ao-champion.webp',
      description:
        '金鳌踏浪托起高台，卷云环绕如庆典舞台；把这一份荣耀感送给刚取得突破的朋友，纪念真正付出的努力。',
    },
    {
      id: 'oriental-midnight-pagoda',
      name: '子时·夜明琉璃',
      price: 680,
      category: '盛世华章',
      rarity: '入门款',
      series: '盛世华章',
      subseries: '十二时辰',
      tier: '入门',
      accent: '#6274A1',
      effect: 'stars',
      orientalEffect: 'pagoda',
      goldBeanPrice: 49,
      image: 'gift-art/oriental/oriental-midnight-pagoda.webp',
      description: '子夜的琉璃小塔透出深蓝与金色微光，月影落在塔檐；陪晚睡的人把夜色过得柔和一点。',
    },
    {
      id: 'oriental-dawn-corner-tower',
      name: '卯时·紫气东来',
      price: 880,
      category: '盛世华章',
      rarity: '入门款',
      series: '盛世华章',
      subseries: '十二时辰',
      tier: '入门',
      accent: '#8E6795',
      effect: 'orbit',
      orientalEffect: 'dawn',
      goldBeanPrice: 69,
      image: 'gift-art/oriental/oriental-dawn-corner-tower.webp',
      description: '晨光从宫墙角楼后升起，紫金云霞在屋檐间流动；用清亮的一声早安开启新一天。',
    },
    {
      id: 'oriental-noon-golden-cup',
      name: '午时·日光耀金',
      price: 1200,
      category: '盛世华章',
      rarity: '入门款',
      series: '盛世华章',
      subseries: '十二时辰',
      tier: '入门',
      accent: '#D19D44',
      effect: 'stars',
      orientalEffect: 'noon',
      goldBeanPrice: 99,
      image: 'gift-art/oriental/oriental-noon-golden-cup.webp',
      description: '正午阳光照在鎏金杯盏上，杯沿折出几道明快光线；送给忙到中午也记得停下歇息的朋友。',
    },
    {
      id: 'oriental-dusk-goose',
      name: '酉时·晚霞落雁',
      price: 980,
      category: '盛世华章',
      rarity: '入门款',
      series: '盛世华章',
      subseries: '十二时辰',
      tier: '入门',
      accent: '#B45E59',
      effect: 'hearts',
      orientalEffect: 'dusk',
      goldBeanPrice: 79,
      image: 'gift-art/oriental/oriental-dusk-goose.webp',
      description: '晚霞染红飞檐，归雁掠过层层绛色云彩；在一天将尽时，把温柔的问候送给惦念的人。',
    },
  ],
  // Profile covers and chat wallpapers. `tone` = brightness of the backdrop ('dark' needs light text).
  backgrounds: [
    {
      id: 'crimson-gold',
      name: '暗红鎏金',
      description: '深红底色浮着细腻金光，让礼物陈列多一份温暖的仪式感。',
      kind: 'gradient',
      tone: 'dark',
      ink: '#FFFFFF',
      background:
        'radial-gradient(ellipse at 18% 10%, rgba(224,181,99,0.24) 0%, transparent 44%), radial-gradient(ellipse at 88% 78%, rgba(145,41,48,0.48) 0%, transparent 55%), linear-gradient(145deg, #36171C 0%, #5B202A 48%, #28171B 100%)',
    },
    {
      id: 'rose-mist',
      name: '红粉晨雾',
      description: '像清晨花瓣上的薄雾，轻轻衬出每一份柔软心意。',
      kind: 'gradient',
      tone: 'light',
      ink: '#512F3C',
      background:
        'radial-gradient(ellipse at 16% 12%, rgba(255,255,255,0.90) 0%, transparent 52%), radial-gradient(ellipse at 90% 80%, rgba(241,172,189,0.35) 0%, transparent 52%), linear-gradient(145deg, #FFF5F5 0%, #FCE7EC 56%, #F5DCE2 100%)',
    },
    {
      id: 'mint-light',
      name: '薄荷浅绿',
      description: '浅浅薄荷色配上明亮留白，把收藏角装点得清新自在。',
      kind: 'gradient',
      tone: 'light',
      ink: '#27483A',
      background:
        'radial-gradient(ellipse at 20% 15%, rgba(255,255,255,0.95) 0%, transparent 48%), radial-gradient(ellipse at 80% 82%, rgba(179,221,204,0.35) 0%, transparent 50%), linear-gradient(145deg, #F2FBF5 0%, #E3F3EA 54%, #D4EADF 100%)',
    },
    {
      id: 'midnight-stars',
      name: '午夜星空',
      description: '安静的蓝紫夜幕托起点点星光，适合慢慢欣赏闪耀的小收藏。',
      kind: 'gradient',
      tone: 'dark',
      ink: '#FFFFFF',
      background:
        'radial-gradient(circle at 17% 21%, rgba(255,244,206,0.9) 0 1px, transparent 2px), radial-gradient(circle at 74% 16%, rgba(237,236,255,0.85) 0 1px, transparent 2px), radial-gradient(circle at 86% 62%, rgba(224,230,255,0.7) 0 1px, transparent 2px), radial-gradient(ellipse at 68% 36%, rgba(102,84,166,0.38) 0%, transparent 52%), linear-gradient(160deg, #111829 0%, #22213D 54%, #101722 100%)',
    },
    {
      id: 'kl-night',
      name: '吉隆坡夜色',
      description: '把熟悉的城市灯火留在身后，让每一次相遇都有温暖的夜色相伴。',
      kind: 'photo',
      tone: 'dark',
      ink: '#FFFFFF',
      image: 'city-kl.webp',
      background: '',
    },
    {
      id: 'cream-solid',
      name: '奶油纯色',
      description: '柔和奶油底色安静退后，让礼物本身的色彩成为主角。',
      kind: 'gradient',
      tone: 'light',
      ink: '#493E32',
      background: 'linear-gradient(0deg, #F8F1E6 0%, #F8F1E6 100%)',
    },
  ],
  // Short notes on friends' example gift messages, as [received, sent] pairs (tc('giftNotes', index)).
  friendNotes: [
    ['把一点星光留给你，愿今天也有好心情。', '这份小小的心意，送给认真生活的你。'],
    ['上次聊的故事我还记得，愿下一次也很开心。', '把这份闪耀送给你，谢谢你分享有趣的日常。'],
    ['忙完记得歇一会儿，送你一点温柔的光。', '今天的好心情，也想分给你一份。'],
    ['愿你的每个小计划，都慢慢变成喜欢的生活。', '为你的新尝试加油，把祝福放进这份礼物。'],
    ['有空再一起聊聊城市里的新发现。', '把美好的瞬间留下，送你一份相遇的纪念。'],
    ['谢谢你认真听我说话，这一点心意送给你。', '这份礼物替我说一句：认识你很开心。'],
  ],
};

/*
 * 大马风情 / Malaysia series. Its catalogue ships with the artwork (window.SHIZHONG_GIFT_ART_SERIES,
 * assets/gift-art/manifest.js, loaded before this file) so prices and art stay in one place.
 * English names and descriptions: data/i18n/en/gifts.js; the category label: data:gifts in locales.
 */
(function () {
  const data = window.SHIZHONG_GIFT_DATA;
  const series = window.SHIZHONG_GIFT_ART_SERIES?.malaysia;
  if (!data || !Array.isArray(series)) return;
  const known = new Set(data.gifts.map(g => g.id));
  for (const g of series) {
    if (!g?.id || known.has(g.id) || !(Number(g.priceRM) > 0)) continue;
    data.gifts.push({
      id: g.id,
      name: g.name_zh,
      price: Number(g.priceRM),
      category: g.category_zh || '大马风情',
      rarity: g.rarity_zh,
      accent: g.accent,
      effect: g.effect,
      ...(Number(g.goldBeans) > 0 ? { goldBeanPrice: Number(g.goldBeans) } : {}),
      image: g.image,
      description: g.description_zh,
    });
  }
})();

/*
 * Server mode: the unified catalogue from the database (data/gift-catalog.js, priced in gold beans and edited in
 * the console) replaces the built-in lists. Its artwork paths win over the manifest so console uploads show.
 */
(function () {
  const catalog = window.SHIZHONG_GIFT_CATALOG;
  const data = window.SHIZHONG_GIFT_DATA;
  if (!catalog || !data || !Array.isArray(catalog.mall)) return;
  data.gifts = catalog.mall;
  if (Array.isArray(catalog.backgrounds) && catalog.backgrounds.length) data.backgrounds = catalog.backgrounds;
  data.currency = 'beans';
  const art = window.SHIZHONG_GIFT_ART || (window.SHIZHONG_GIFT_ART = {});
  for (const [id, a] of Object.entries(catalog.art || {}))
    if (a && (a.full || a.thumb))
      art[id] = { ...(art[id] || {}), ...Object.fromEntries(Object.entries(a).filter(([, v]) => v)) };
})();
