'use strict';
/*
 * Live-room gift catalogue (owner: live). window.SHIZHONG_LIVE_GIFTS = [gift…] plus helpers on the array:
 *   .categories   tab order (stable ids stored in the source language; labels: td('live.giftCategory', id))
 *   .legacyIds    { oldId: newId } for gifts renamed in v2 (stored history is migrated by live-room.js)
 *   .byId(id)     gift by id (old ids resolve too)
 *   .art(id, 'full'|'thumb')  artwork path relative to assets/
 * Each gift: { id, price (demo gold beans), category, effect (live-effects family), accent, orientalEffect? }
 * plus read-only getters: name / description in the active language (data/i18n/<locale>/live-gifts.js,
 * read with tc('liveGifts', …)) and image (square artwork from window.SHIZHONG_GIFT_ART).
 * Gifts without their own description describe their effect: t('live.effect.<effect>').
 */
(function () {
  // v2 renamed the gifts that copied another platform's names; the artwork manifest still uses the old keys.
  const LEGACY_IDS = {
    'douyin-magic-wand': 'wand',
    'douyin-yellow-magic-wand': 'wand-yellow',
    'douyin-blue-magic-wand': 'wand-blue',
    'douyin-green-magic-wand': 'wand-green',
    'douyin-purple-magic-wand': 'wand-purple',
    'douyin-power-pill': 'power-pill',
    'douyin-magic-mirror': 'magic-mirror',
    'douyin-donut': 'donut',
    'douyin-energy-battery': 'battery',
    'douyin-love-burst': 'heart-grow',
    'douyin-party-microphone': 'party-mic',
    'douyin-mystery-airdrop': 'mystery-parcel',
    'douyin-strawberry-dessert': 'shortcake',
    'douyin-super-airdrop': 'parachute',
    'douyin-life-potion': 'potion',
    'douyin-super-jet': 'saucer',
    'douyin-rare-treasure': 'lucky-bag',
    'douyin-lucky-cube': 'lucky-dice',
  };
  // Server mode: the database catalogue (data/gift-catalog.js) replaces SOURCE and CATEGORIES and adds its aliases.
  const CATALOG = Array.isArray(window.SHIZHONG_GIFT_CATALOG?.live) ? window.SHIZHONG_GIFT_CATALOG : null;
  if (CATALOG) for (const [from, to] of Object.entries(CATALOG.aliases || {})) LEGACY_IDS[from] ??= to;
  const ART_KEYS = Object.fromEntries(Object.entries(LEGACY_IDS).map(([from, to]) => [to, from]));
  const BUILT_IN = [
    { id: 'heart', name: '小心心', price: 1, category: '推荐', effect: 'heart', accent: '#ff4d87' },
    { id: 'flowers', name: '鲜花', price: 10, category: '推荐', effect: 'flowers', accent: '#fb6888' },
    { id: 'rose', name: '心动玫瑰', price: 19, category: '推荐', effect: 'flowers', accent: '#ff467a' },
    { id: 'coffee', name: '暖心咖啡', price: 20, category: '推荐', effect: 'heart', accent: '#d99c62' },
    { id: 'bear', name: '抱抱熊', price: 99, category: '推荐', effect: 'heart', accent: '#e9b277' },
    {
      id: 'confetti',
      name: '礼花筒',
      price: 199,
      category: '推荐',
      effect: 'celebration',
      accent: '#ffbb44',
    },
    { id: 'cake', name: '生日心愿', price: 299, category: '推荐', effect: 'celebration', accent: '#ff819f' },
    {
      id: 'ribbon-heart',
      name: '心动礼盒',
      price: 520,
      category: '推荐',
      effect: 'heart',
      accent: '#ff498f',
    },
    { id: 'car', name: '心动跑车', price: 1200, category: '推荐', effect: 'car', accent: '#ff425c' },
    { id: 'crown', name: '荣耀皇冠', price: 1888, category: '推荐', effect: 'crown', accent: '#ffcf56' },
    { id: 'rocket', name: '星际启程', price: 3000, category: '推荐', effect: 'rocket', accent: '#93c7ff' },
    { id: 'planet', name: '星河浪漫', price: 5200, category: '推荐', effect: 'galaxy', accent: '#b493ff' },
    { id: 'yacht', name: '海上之约', price: 6000, category: '典藏', effect: 'galaxy', accent: '#68d8f5' },
    { id: 'unicorn', name: '独角兽之梦', price: 8888, category: '典藏', effect: 'galaxy', accent: '#d78bf4' },
    { id: 'dragon', name: '祥云神龙', price: 12000, category: '典藏', effect: 'crown', accent: '#fbc657' },
    { id: 'castle', name: '童话城堡', price: 20000, category: '典藏', effect: 'crown', accent: '#ffc377' },
    {
      id: 'wand',
      name: '仙女棒',
      price: 1,
      category: '互动',
      effect: 'celebration',
      accent: '#d58afa',
      art: 'douyin-magic-wand',
    },
    {
      id: 'wand-yellow',
      name: '金色仙女棒',
      price: 1,
      category: '互动',
      effect: 'celebration',
      accent: '#d58afa',
      art: 'douyin-yellow-magic-wand',
    },
    {
      id: 'wand-blue',
      name: '蓝色仙女棒',
      price: 1,
      category: '互动',
      effect: 'celebration',
      accent: '#d58afa',
      art: 'douyin-blue-magic-wand',
    },
    {
      id: 'wand-green',
      name: '绿色仙女棒',
      price: 1,
      category: '互动',
      effect: 'celebration',
      accent: '#d58afa',
      art: 'douyin-green-magic-wand',
    },
    {
      id: 'wand-purple',
      name: '紫色仙女棒',
      price: 1,
      category: '互动',
      effect: 'celebration',
      accent: '#d58afa',
      art: 'douyin-purple-magic-wand',
    },
    {
      id: 'power-pill',
      name: '能量药丸',
      price: 10,
      category: '互动',
      effect: 'celebration',
      accent: '#d58afa',
      art: 'douyin-power-pill',
    },
    {
      id: 'magic-mirror',
      name: '魔法镜',
      price: 19,
      category: '互动',
      effect: 'celebration',
      accent: '#d58afa',
      art: 'douyin-magic-mirror',
    },
    {
      id: 'donut',
      name: '甜甜圈',
      price: 52,
      category: '互动',
      effect: 'celebration',
      accent: '#d58afa',
      art: 'douyin-donut',
    },
    {
      id: 'battery',
      name: '能量电池',
      price: 99,
      category: '互动',
      effect: 'celebration',
      accent: '#d58afa',
      art: 'douyin-energy-battery',
    },
    {
      id: 'heart-grow',
      name: '心动放大',
      price: 199,
      category: '互动',
      effect: 'heart',
      accent: '#d58afa',
      art: 'douyin-love-burst',
    },
    {
      id: 'party-mic',
      name: '派对话筒',
      price: 299,
      category: '互动',
      effect: 'celebration',
      accent: '#d58afa',
      art: 'douyin-party-microphone',
    },
    {
      id: 'mystery-parcel',
      name: '神秘包裹',
      price: 520,
      category: '互动',
      effect: 'celebration',
      accent: '#d58afa',
      art: 'douyin-mystery-airdrop',
    },
    {
      id: 'shortcake',
      name: '草莓蛋糕',
      price: 666,
      category: '互动',
      effect: 'celebration',
      accent: '#d58afa',
      art: 'douyin-strawberry-dessert',
    },
    {
      id: 'parachute',
      name: '降落伞空投',
      price: 888,
      category: '互动',
      effect: 'celebration',
      accent: '#d58afa',
      art: 'douyin-super-airdrop',
    },
    {
      id: 'potion',
      name: '生命药水',
      price: 999,
      category: '互动',
      effect: 'celebration',
      accent: '#d58afa',
      art: 'douyin-life-potion',
    },
    {
      id: 'saucer',
      name: '星际飞碟',
      price: 1200,
      category: '互动',
      effect: 'rocket',
      accent: '#d58afa',
      art: 'douyin-super-jet',
    },
    {
      id: 'lucky-bag',
      name: '招财福袋',
      price: 3000,
      category: '互动',
      effect: 'crown',
      accent: '#d58afa',
      art: 'douyin-rare-treasure',
    },
    {
      id: 'lucky-dice',
      name: '幸运骰子',
      price: 1,
      category: '互动',
      effect: 'celebration',
      accent: '#d58afa',
      art: 'douyin-lucky-cube',
    },
    {
      id: 'oriental-tongxin-knot',
      name: '同心结',
      price: 9,
      category: '盛世华章',
      effect: 'heart',
      accent: '#BE2534',
      orientalEffect: 'knot',
      description:
        '一枚朱红盘长结垂着细金穗，把想说的祝福系在一起；适合送给刚认识的新朋友，也能放在主页作小巧挂件。',
    },
    {
      id: 'oriental-lantern',
      name: '灯笼',
      price: 19,
      category: '盛世华章',
      effect: 'celebration',
      accent: '#D44627',
      orientalEffect: 'lantern',
      description: '描金宫灯点亮暖黄烛光，沿着夜色缓缓升起；把团圆与平安的心意送到正在聊天的人面前。',
    },
    {
      id: 'oriental-folding-fan',
      name: '折扇',
      price: 39,
      category: '盛世华章',
      effect: 'galaxy',
      accent: '#966747',
      orientalEffect: 'fan',
      description: '一柄乌木折扇展开层叠水墨山峦，合拢时留下一缕金色光迹；适合送给喜欢旅行与山水的朋友。',
    },
    {
      id: 'oriental-blue-white-porcelain',
      name: '青花瓷',
      price: 199,
      category: '盛世华章',
      effect: 'galaxy',
      accent: '#386898',
      orientalEffect: 'porcelain',
      description: '白瓷小瓶映着细密青花缠枝纹，旋转间显出柔和釉光；让一份安静的雅意留在好友的礼物收藏里。',
    },
    {
      id: 'oriental-phoenix-flight',
      name: '凤凰于飞',
      price: 520,
      category: '盛世华章',
      effect: 'crown',
      accent: '#C84C42',
      orientalEffect: 'phoenix',
      description: '赤金凤凰舒展羽翼，尾羽如轻柔绸带掠过屏幕；送给并肩前行的人，纪念彼此照亮的一刻。',
    },
    {
      id: 'oriental-pipa-song',
      name: '琵琶行',
      price: 399,
      category: '盛世华章',
      effect: 'galaxy',
      accent: '#B28355',
      orientalEffect: 'pipa',
      description: '梨花木琵琶立在云纹绸带间，琴弦泛起细碎金芒；把一段无需言说的悠长心绪送进今晚的会话。',
    },
    {
      id: 'oriental-golden-dragon',
      name: '龙腾',
      price: 2999,
      category: '盛世华章',
      effect: 'crown',
      accent: '#D29B37',
      orientalEffect: 'dragon',
      description: '鎏金祥龙穿过层叠云海腾空盘旋，龙鳞映着故宫红光；用一份壮阔礼物为朋友的重要时刻喝彩。',
    },
    {
      id: 'oriental-nine-ding',
      name: '九鼎',
      price: 3999,
      category: '盛世华章',
      effect: 'crown',
      accent: '#A9783D',
      orientalEffect: 'ding',
      description: '青铜古鼎承着九重云纹，鼎耳与金边在光束中渐次显现；适合纪念一项稳稳落地的重要成果。',
    },
    {
      id: 'oriental-qilin-treasure',
      name: '麒麟送宝',
      price: 5200,
      category: '盛世华章',
      effect: 'celebration',
      accent: '#C88B3F',
      orientalEffect: 'qilin',
      description: '瑞兽麒麟踏着祥云送来一只缀金宝匣，步伐轻快而隆重；把好事临门的祝愿留给特别的伙伴。',
    },
    {
      id: 'oriental-landscape-scroll',
      name: '江山如画',
      price: 12888,
      category: '盛世华章',
      effect: 'galaxy',
      accent: '#887451',
      orientalEffect: 'scroll',
      description: '长卷徐徐展开，黛色山峦、云水与金色楼阁在纸上相遇；把眼前的宽阔风景送给愿意同行的人。',
    },
    {
      id: 'oriental-phoenix-crown',
      name: '凤冠霞帔',
      price: 18888,
      category: '盛世华章',
      effect: 'crown',
      accent: '#C59042',
      orientalEffect: 'crown',
      description: '点翠凤冠嵌着金珠与红色流苏，霞帔般的柔光在身后舒展；为值得珍惜的喜庆日子添一场华美仪式。',
    },
    {
      id: 'oriental-heavenly-craft',
      name: '天工开物',
      price: 29999,
      category: '盛世华章',
      effect: 'crown',
      accent: '#D19B55',
      orientalEffect: 'craft',
      description:
        '匠作宝匣汇聚建筑飞檐、青花瓷片与龙凤金纹，层层打开如一座微缩工艺殿堂；献给认真创造生活的人。',
    },
    {
      id: 'oriental-azure-dragon',
      name: '青龙出海',
      price: 8888,
      category: '盛世华章',
      effect: 'galaxy',
      accent: '#4A9A91',
      orientalEffect: 'azure-dragon',
      description: '青碧灵龙越过墨色海浪，长须与云气带出流动的翠金光；这份四灵藏品象征向新的方向出发。',
    },
    {
      id: 'oriental-white-tiger',
      name: '白虎踏星',
      price: 6999,
      category: '盛世华章',
      effect: 'galaxy',
      accent: '#AEB9C9',
      orientalEffect: 'white-tiger',
      description: '银白猛虎踩过深蓝星轨，额间金纹随着步伐闪亮；为勇敢迈出一步的朋友留下利落而坚定的祝福。',
    },
    {
      id: 'oriental-vermilion-bird',
      name: '朱雀涅槃',
      price: 9999,
      category: '盛世华章',
      effect: 'crown',
      accent: '#D15036',
      orientalEffect: 'vermilion-bird',
      description: '朱雀从金红羽焰中展翼而起，细小火羽化作温暖光点；送给刚走过低谷、再次拥抱新开始的人。',
    },
    {
      id: 'oriental-black-tortoise',
      name: '玄武御天',
      price: 9888,
      category: '盛世华章',
      effect: 'galaxy',
      accent: '#637C79',
      orientalEffect: 'black-tortoise',
      description: '龟蛇相依的玄武浮在深色云台之上，甲纹托起一圈温润的金色屏障；愿所爱之人安稳从容。',
    },
    {
      id: 'oriental-golden-calligraphy',
      name: '一字千金',
      price: 29,
      category: '盛世华章',
      effect: 'galaxy',
      accent: '#A78147',
      orientalEffect: 'calligraphy',
      description: '羊毫笔蘸开浓墨，在宣纸上写出一枚泛金的吉字；为正在努力的朋友送上一点鼓励与文采。',
    },
    {
      id: 'oriental-top-scholar',
      name: '高中状元',
      price: 999,
      category: '盛世华章',
      effect: 'celebration',
      accent: '#C33E35',
      orientalEffect: 'scholar',
      description: '绛红状元帽缀着金色花翎，卷轴在旁缓缓展开；祝贺考试、面试或作品发布时的每一份认真准备。',
    },
    {
      id: 'oriental-carp-dragon-gate',
      name: '鱼跃龙门',
      price: 1888,
      category: '盛世华章',
      effect: 'rocket',
      accent: '#D39B54',
      orientalEffect: 'carp',
      description: '赤金锦鲤冲出浪花跃向汉白玉龙门，水滴化作细碎星点；为迎来转机的好消息送上掌声。',
    },
    {
      id: 'oriental-ao-champion',
      name: '独占鳌头',
      price: 11999,
      category: '盛世华章',
      effect: 'crown',
      accent: '#B8833E',
      orientalEffect: 'ao',
      description:
        '金鳌踏浪托起高台，卷云环绕如庆典舞台；把这一份荣耀感送给刚取得突破的朋友，纪念真正付出的努力。',
    },
    {
      id: 'oriental-midnight-pagoda',
      name: '子时·夜明琉璃',
      price: 49,
      category: '盛世华章',
      effect: 'galaxy',
      accent: '#6274A1',
      orientalEffect: 'pagoda',
      description: '子夜的琉璃小塔透出深蓝与金色微光，月影落在塔檐；陪晚睡的人把夜色过得柔和一点。',
    },
    {
      id: 'oriental-dawn-corner-tower',
      name: '卯时·紫气东来',
      price: 69,
      category: '盛世华章',
      effect: 'galaxy',
      accent: '#8E6795',
      orientalEffect: 'dawn',
      description: '晨光从宫墙角楼后升起，紫金云霞在屋檐间流动；用清亮的一声早安开启新一天。',
    },
    {
      id: 'oriental-noon-golden-cup',
      name: '午时·日光耀金',
      price: 99,
      category: '盛世华章',
      effect: 'galaxy',
      accent: '#D19D44',
      orientalEffect: 'noon',
      description: '正午阳光照在鎏金杯盏上，杯沿折出几道明快光线；送给忙到中午也记得停下歇息的朋友。',
    },
    {
      id: 'oriental-dusk-goose',
      name: '酉时·晚霞落雁',
      price: 79,
      category: '盛世华章',
      effect: 'heart',
      accent: '#B45E59',
      orientalEffect: 'dusk',
      description: '晚霞染红飞檐，归雁掠过层层绛色云彩；在一天将尽时，把温柔的问候送给惦念的人。',
    },
    {
      id: 'my-teh-tarik',
      name: '拉茶',
      price: 1,
      category: '大马风情',
      effect: 'heart',
      accent: '#C77B37',
      description: '一杯拉得高高、泡沫绵密的拉茶，把嘛嘛档的暖意和闲聊一起递给你。',
    },
    {
      id: 'my-ketupat',
      name: '马来粽',
      price: 3,
      category: '大马风情',
      effect: 'celebration',
      accent: '#6DB33A',
      description: '椰叶一格一格编成的马来粽，装满开斋节团圆的祝福。',
    },
    {
      id: 'my-cendol',
      name: '煎蕊',
      price: 6,
      category: '大马风情',
      effect: 'celebration',
      accent: '#4CB050',
      description: '翠绿煎蕊淋上浓浓椰糖浆，为炎热的午后送上一口清凉。',
    },
    {
      id: 'my-nasi-lemak',
      name: '椰浆饭',
      price: 9,
      category: '大马风情',
      effect: 'galaxy',
      accent: '#E0381F',
      description: '椰香米饭配上参巴、鸡蛋和花生小鱼干，是最地道的大马早安问候。',
    },
    {
      id: 'my-satay',
      name: '沙爹',
      price: 19,
      category: '大马风情',
      effect: 'celebration',
      accent: '#C4621F',
      description: '炭火烤得焦香的沙爹蘸上花生酱，最适合和好朋友一起分享。',
    },
    {
      id: 'my-bunga-raya',
      name: '大红花',
      price: 52,
      category: '大马风情',
      effect: 'heart',
      accent: '#E8283A',
      description: '一朵盛放的大红花，把热情与勇气送给你在乎的人。',
    },
    {
      id: 'my-durian',
      name: '榴梿',
      price: 88,
      category: '大马风情',
      effect: 'galaxy',
      accent: '#94B23A',
      description: '果王驾到，懂的人自然会心一笑。',
    },
    {
      id: 'my-wau-bulan',
      name: '月亮风筝',
      price: 199,
      category: '大马风情',
      effect: 'rocket',
      accent: '#E8352B',
      description: '彩绘月亮风筝乘风而起，带着你的心意飞得又高又远。',
    },
    {
      id: 'my-kampung',
      name: '甘榜高脚屋',
      price: 399,
      category: '大马风情',
      effect: 'galaxy',
      accent: '#C27A3C',
      description: '椰树下的甘榜高脚屋，是随时欢迎你回家的温暖角落。',
    },
    {
      id: 'my-hornbill',
      name: '犀鸟',
      price: 699,
      category: '大马风情',
      effect: 'rocket',
      accent: '#FF6A2B',
      description: '来自婆罗洲雨林的犀鸟展翅而来，守护着你们之间的约定。',
    },
    {
      id: 'my-twin-towers',
      name: '吉隆坡双峰塔',
      price: 1688,
      category: '大马风情',
      effect: 'crown',
      accent: '#FF9B6B',
      description: '暮色里的双峰塔闪闪发亮，为你点亮整座城市。',
      art: 'my-petronas',
    },
    {
      id: 'my-panda-mascot',
      name: '适中熊猫',
      price: 2999,
      category: '大马风情',
      effect: 'crown',
      accent: '#FFC61A',
      description: '适中熊猫眨眨眼、抱紧爱心，把最好的祝福留给最特别的你。',
    },
  ];
  const SOURCE = CATALOG ? CATALOG.live : BUILT_IN;
  const CATEGORIES = CATALOG?.liveCategories?.length
    ? CATALOG.liveCategories
    : ['推荐', '互动', '大马风情', '典藏', '盛世华章'];
  const index = new Map();
  function byId(id) {
    return index.get(id) || index.get(LEGACY_IDS[id]) || null;
  }
  function artwork(id, size = 'thumb') {
    const gift = byId(id);
    const manifest = window.SHIZHONG_GIFT_ART || {};
    const entry = manifest[gift?.id] || manifest[gift?.artKey] || manifest[ART_KEYS[gift?.id]];
    return (
      (entry && (entry[size] || entry.full || entry.thumb)) || gift?.fallbackImage || 'gifts/gift-box.png'
    );
  }
  function define(source) {
    const { name, description = '', art = '', image = '', ...rest } = source;
    const gift = { ...rest, sourceName: name, artKey: art, fallbackImage: image };
    const translate = (field, value) =>
      value && typeof tc === 'function' ? tc('liveGifts', gift.id, field, value) : value;
    Object.defineProperties(gift, {
      name: { enumerable: true, get: () => translate('name', name) },
      description: {
        enumerable: true,
        get: () =>
          translate('description', description) ||
          (typeof t === 'function' ? t(`live.effect.${gift.effect}`) : ''),
      },
      image: { enumerable: true, get: () => artwork(gift.id, 'thumb') },
    });
    index.set(gift.id, gift);
    return Object.freeze(gift);
  }
  const list = SOURCE.map(define);
  Object.defineProperties(list, {
    categories: { value: Object.freeze(CATEGORIES.slice()) },
    legacyIds: { value: Object.freeze({ ...LEGACY_IDS }) },
    byId: { value: byId },
    art: { value: artwork },
  });
  window.SHIZHONG_LIVE_GIFTS = list;
})();
