'use strict';
// Independent local demo gold-bean prices. Official references are documented in assets/live-gifts.
window.SHIZHONG_LIVE_GIFTS = [
  {
    id: 'heart',
    name: '小心心',
    price: 1,
    image: 'live-gifts/fluent-red-heart.png',
    effect: 'heart',
    category: '推荐',
    accent: '#ff4d87',
    sourceKind: 'fluent-demo',
    description: '爱心环绕 · 温柔上浮',
  },
  {
    id: 'flowers',
    name: '鲜花',
    price: 10,
    image: 'gifts/bouquet.png',
    effect: 'flowers',
    category: '推荐',
    accent: '#fb6888',
    sourceKind: 'fluent-demo',
    description: '花瓣洒落 · 满屏花色',
  },
  {
    id: 'rose',
    name: '心动玫瑰',
    price: 19,
    image: 'gifts/rose.png',
    effect: 'flowers',
    category: '推荐',
    accent: '#ff467a',
    sourceKind: 'fluent-demo',
    description: '花瓣洒落 · 满屏花色',
  },
  {
    id: 'coffee',
    name: '暖心咖啡',
    price: 20,
    image: 'gifts/coffee.png',
    effect: 'heart',
    category: '推荐',
    accent: '#d99c62',
    sourceKind: 'fluent-demo',
    description: '爱心环绕 · 温柔上浮',
  },
  {
    id: 'bear',
    name: '抱抱熊',
    price: 99,
    image: 'gifts/teddy-bear.png',
    effect: 'heart',
    category: '推荐',
    accent: '#e9b277',
    sourceKind: 'fluent-demo',
    description: '爱心环绕 · 温柔上浮',
  },
  {
    id: 'confetti',
    name: '礼花筒',
    price: 199,
    image: 'live-gifts/fluent-party-popper.png',
    effect: 'celebration',
    category: '推荐',
    accent: '#ffbb44',
    sourceKind: 'fluent-demo',
    description: '彩色礼花 · 庆祝时刻',
  },
  {
    id: 'cake',
    name: '生日心愿',
    price: 299,
    image: 'gifts/birthday-cake.png',
    effect: 'celebration',
    category: '推荐',
    accent: '#ff819f',
    sourceKind: 'fluent-demo',
    description: '彩色礼花 · 庆祝时刻',
  },
  {
    id: 'ribbon-heart',
    name: '心动礼盒',
    price: 520,
    image: 'gifts/ribbon-heart.png',
    effect: 'heart',
    category: '推荐',
    accent: '#ff498f',
    sourceKind: 'fluent-demo',
    description: '爱心环绕 · 温柔上浮',
  },
  {
    id: 'car',
    name: '心动跑车',
    price: 1200,
    image: 'gifts/racing-car.png',
    effect: 'car',
    category: '推荐',
    accent: '#ff425c',
    sourceKind: 'fluent-demo',
    description: '流光跑车 · 闪耀登场',
  },
  {
    id: 'crown',
    name: '荣耀皇冠',
    price: 1888,
    image: 'gifts/crown.png',
    effect: 'crown',
    category: '推荐',
    accent: '#ffcf56',
    sourceKind: 'fluent-demo',
    description: '金色光环 · 荣耀加冕',
  },
  {
    id: 'rocket',
    name: '星际启程',
    price: 3000,
    image: 'gifts/rocket.png',
    effect: 'rocket',
    category: '推荐',
    accent: '#93c7ff',
    sourceKind: 'fluent-demo',
    description: '星际升空 · 光芒尾迹',
  },
  {
    id: 'planet',
    name: '星河浪漫',
    price: 5200,
    image: 'gifts/ringed-planet.png',
    effect: 'galaxy',
    category: '推荐',
    accent: '#b493ff',
    sourceKind: 'fluent-demo',
    description: '星河旋转 · 浪漫相遇',
  },
  {
    id: 'yacht',
    name: '海上之约',
    price: 6000,
    image: 'gifts/yacht.png',
    effect: 'galaxy',
    category: '典藏',
    accent: '#68d8f5',
    sourceKind: 'fluent-demo',
    description: '星河旋转 · 浪漫相遇',
  },
  {
    id: 'unicorn',
    name: '独角兽之梦',
    price: 8888,
    image: 'gifts/unicorn.png',
    effect: 'galaxy',
    category: '典藏',
    accent: '#d78bf4',
    sourceKind: 'fluent-demo',
    description: '星河旋转 · 浪漫相遇',
  },
  {
    id: 'dragon',
    name: '祥云神龙',
    price: 12000,
    image: 'gifts/dragon.png',
    effect: 'crown',
    category: '典藏',
    accent: '#fbc657',
    sourceKind: 'fluent-demo',
    description: '金色光环 · 荣耀加冕',
  },
  {
    id: 'castle',
    name: '童话城堡',
    price: 20000,
    image: 'gifts/castle.png',
    effect: 'crown',
    category: '典藏',
    accent: '#ffc377',
    sourceKind: 'fluent-demo',
    description: '金色光环 · 荣耀加冕',
  },
  {
    id: 'douyin-magic-wand',
    name: '仙女棒',
    image: 'live-gifts/douyin-magic-wand.png',
    officialId: 'n1/Dg1905sj1FyoBlQBvmbaDZFBNaKuKZH6zxHkv8Lg5x2cRfrKUTb8gzMs=',
    officialValue: 1,
    officialUnit: '抖币',
    appDemoPrice: null,
    assetKind: 'official public documentation gift icon; not an animation file',
    licenseStatus: 'unknown for independent-app redistribution',
    price: 1,
    category: '互动',
    effect: 'celebration',
    accent: '#d58afa',
    description: '互动心意 · 星光绽放',
    sourceKind: 'douyin-public-icon',
    priceNote: 'App-specific demo gold beans; no currency conversion from the documented Douyin value.',
  },
  {
    id: 'douyin-yellow-magic-wand',
    name: '黄色仙女棒',
    image: 'live-gifts/douyin-yellow-magic-wand.png',
    officialId: 'eplFUy7i0B0fiv0Iym1MpOZa5XmUE8g/WUAyJ6Tc+UJJDpcs7pzclNOz/WM=',
    officialValue: 1,
    officialUnit: '抖币',
    appDemoPrice: null,
    assetKind: 'official public documentation gift icon; not an animation file',
    licenseStatus: 'unknown for independent-app redistribution',
    price: 1,
    category: '互动',
    effect: 'celebration',
    accent: '#d58afa',
    description: '互动心意 · 星光绽放',
    sourceKind: 'douyin-public-icon',
    priceNote: 'App-specific demo gold beans; no currency conversion from the documented Douyin value.',
  },
  {
    id: 'douyin-blue-magic-wand',
    name: '蓝色仙女棒',
    image: 'live-gifts/douyin-blue-magic-wand.png',
    officialId: '4I66OIE1HKWfM7PNvAHtAgYUSNlggSEgcpo3ai8GYQXAWqjrDuH8NtjsWEQ=',
    officialValue: 1,
    officialUnit: '抖币',
    appDemoPrice: null,
    assetKind: 'official public documentation gift icon; not an animation file',
    licenseStatus: 'unknown for independent-app redistribution',
    price: 1,
    category: '互动',
    effect: 'celebration',
    accent: '#d58afa',
    description: '互动心意 · 星光绽放',
    sourceKind: 'douyin-public-icon',
    priceNote: 'App-specific demo gold beans; no currency conversion from the documented Douyin value.',
  },
  {
    id: 'douyin-green-magic-wand',
    name: '绿色仙女棒',
    image: 'live-gifts/douyin-green-magic-wand.png',
    officialId: 'XHS+QR5Cv0b9ydsZZ5mLkrhPtMTTdrLsgfWNU/QX2IfUy2P6dmDaRHJT+0U=',
    officialValue: 1,
    officialUnit: '抖币',
    appDemoPrice: null,
    assetKind: 'official public documentation gift icon; not an animation file',
    licenseStatus: 'unknown for independent-app redistribution',
    price: 1,
    category: '互动',
    effect: 'celebration',
    accent: '#d58afa',
    description: '互动心意 · 星光绽放',
    sourceKind: 'douyin-public-icon',
    priceNote: 'App-specific demo gold beans; no currency conversion from the documented Douyin value.',
  },
  {
    id: 'douyin-purple-magic-wand',
    name: '紫色仙女棒',
    image: 'live-gifts/douyin-purple-magic-wand.png',
    officialId: 'gs+95ujNzXXSCtLTv97fWgbApTQi0sqz1BULB+7w62g+v4sFxINvxOIrXCw=',
    officialValue: 1,
    officialUnit: '抖币',
    appDemoPrice: null,
    assetKind: 'official public documentation gift icon; not an animation file',
    licenseStatus: 'unknown for independent-app redistribution',
    price: 1,
    category: '互动',
    effect: 'celebration',
    accent: '#d58afa',
    description: '互动心意 · 星光绽放',
    sourceKind: 'douyin-public-icon',
    priceNote: 'App-specific demo gold beans; no currency conversion from the documented Douyin value.',
  },
  {
    id: 'douyin-power-pill',
    name: '能力药丸',
    image: 'live-gifts/douyin-power-pill.png',
    officialId: '28rYzVFNyXEXFC8HI+f/WG+I7a6lfl3OyZZjUS+CVuwCgYZrPrUdytGHu0c=',
    officialValue: 10,
    officialUnit: '抖币',
    appDemoPrice: null,
    assetKind: 'official public documentation gift icon; not an animation file',
    licenseStatus: 'unknown for independent-app redistribution',
    price: 10,
    category: '互动',
    effect: 'celebration',
    accent: '#d58afa',
    description: '互动心意 · 星光绽放',
    sourceKind: 'douyin-public-icon',
    priceNote: 'App-specific demo gold beans; no currency conversion from the documented Douyin value.',
  },
  {
    id: 'douyin-magic-mirror',
    name: '魔法镜',
    image: 'live-gifts/douyin-magic-mirror.png',
    officialId: 'fJs8HKQ0xlPRixn8JAUiL2gFRiLD9S6IFCFdvZODSnhyo9YN8q7xUuVVyZI=',
    officialValue: 19,
    officialUnit: '抖币',
    appDemoPrice: null,
    assetKind: 'official public documentation gift icon; not an animation file',
    licenseStatus: 'unknown for independent-app redistribution',
    price: 19,
    category: '互动',
    effect: 'celebration',
    accent: '#d58afa',
    description: '互动心意 · 星光绽放',
    sourceKind: 'douyin-public-icon',
    priceNote: 'App-specific demo gold beans; no currency conversion from the documented Douyin value.',
  },
  {
    id: 'douyin-donut',
    name: '甜甜圈',
    image: 'live-gifts/douyin-donut.png',
    officialId: 'PJ0FFeaDzXUreuUBZH6Hs+b56Jh0tQjrq0bIrrlZmv13GSAL9Q1hf59fjGk=',
    officialValue: 52,
    officialUnit: '抖币',
    appDemoPrice: null,
    assetKind: 'official public documentation gift icon; not an animation file',
    licenseStatus: 'unknown for independent-app redistribution',
    price: 52,
    category: '互动',
    effect: 'celebration',
    accent: '#d58afa',
    description: '互动心意 · 星光绽放',
    sourceKind: 'douyin-public-icon',
    priceNote: 'App-specific demo gold beans; no currency conversion from the documented Douyin value.',
  },
  {
    id: 'douyin-energy-battery',
    name: '能量电池',
    image: 'live-gifts/douyin-energy-battery.png',
    officialId: 'IkkadLfz7O/a5UR45p/OOCCG6ewAWVbsuzR/Z+v1v76CBU+mTG/wPjqdpfg=',
    officialValue: 99,
    officialUnit: '抖币',
    appDemoPrice: null,
    assetKind: 'official public documentation gift icon; not an animation file',
    licenseStatus: 'unknown for independent-app redistribution',
    price: 99,
    category: '互动',
    effect: 'celebration',
    accent: '#d58afa',
    description: '互动心意 · 星光绽放',
    sourceKind: 'douyin-public-icon',
    priceNote: 'App-specific demo gold beans; no currency conversion from the documented Douyin value.',
  },
  {
    id: 'douyin-love-burst',
    name: '爱的爆炸',
    image: 'live-gifts/douyin-love-burst.png',
    officialId: 'gx7pmjQfhBaDOG2XkWI2peZ66YFWkCWRjZXpTqb23O/epru+sxWyTV/3Ufs=',
    officialValue: 199,
    officialUnit: '抖币',
    appDemoPrice: null,
    assetKind: 'official public documentation gift icon; not an animation file',
    licenseStatus: 'unknown for independent-app redistribution',
    price: 199,
    category: '互动',
    effect: 'heart',
    accent: '#d58afa',
    description: '互动心意 · 星光绽放',
    sourceKind: 'douyin-public-icon',
    priceNote: 'App-specific demo gold beans; no currency conversion from the documented Douyin value.',
  },
  {
    id: 'douyin-party-microphone',
    name: '派对话筒',
    image: 'live-gifts/douyin-party-microphone.png',
    officialId: 'YbLESoUj053FWVYPWUNOAtp4FYnb+/eZbyrLi7ndArVFz14rivgxf0cFrKs=',
    officialValue: 299,
    officialUnit: '抖币',
    appDemoPrice: null,
    assetKind: 'official public documentation gift icon; not an animation file',
    licenseStatus: 'unknown for independent-app redistribution',
    price: 299,
    category: '互动',
    effect: 'celebration',
    accent: '#d58afa',
    description: '互动心意 · 星光绽放',
    sourceKind: 'douyin-public-icon',
    priceNote: 'App-specific demo gold beans; no currency conversion from the documented Douyin value.',
  },
  {
    id: 'douyin-mystery-airdrop',
    name: '神秘空投',
    image: 'live-gifts/douyin-mystery-airdrop.png',
    officialId: 'pGLo7HKNk1i4djkicmJXf6iWEyd+pfPBjbsHmd3WcX0Ierm2UdnRR7UINvI=',
    officialValue: 520,
    officialUnit: '抖币',
    appDemoPrice: null,
    assetKind: 'official public documentation gift icon; not an animation file',
    licenseStatus: 'unknown for independent-app redistribution',
    price: 520,
    category: '互动',
    effect: 'celebration',
    accent: '#d58afa',
    description: '互动心意 · 星光绽放',
    sourceKind: 'douyin-public-icon',
    priceNote: 'App-specific demo gold beans; no currency conversion from the documented Douyin value.',
  },
  {
    id: 'douyin-strawberry-dessert',
    name: '草莓甜点',
    image: 'live-gifts/douyin-strawberry-dessert.png',
    officialId: 'rHSYLYmWZvy2eal+foarBgE5qDJe3j2e96icNOhTSO/t2G0W8UVnXN3mltM=',
    officialValue: 666,
    officialUnit: '抖币',
    appDemoPrice: null,
    assetKind: 'official public documentation gift icon; not an animation file',
    licenseStatus: 'unknown for independent-app redistribution',
    price: 666,
    category: '互动',
    effect: 'celebration',
    accent: '#d58afa',
    description: '互动心意 · 星光绽放',
    sourceKind: 'douyin-public-icon',
    priceNote: 'App-specific demo gold beans; no currency conversion from the documented Douyin value.',
  },
  {
    id: 'douyin-super-airdrop',
    name: '超级空投',
    image: 'live-gifts/douyin-super-airdrop.png',
    officialId: 'lsEGaeC++k/yZbzTU2ST64EukfpPENQmqEZxaK9v1+7etK+qnCRKOnDyjsE=',
    officialValue: 888,
    officialUnit: '抖币',
    appDemoPrice: null,
    assetKind: 'official public documentation gift icon; not an animation file',
    licenseStatus: 'unknown for independent-app redistribution',
    price: 888,
    category: '互动',
    effect: 'celebration',
    accent: '#d58afa',
    description: '互动心意 · 星光绽放',
    sourceKind: 'douyin-public-icon',
    priceNote: 'App-specific demo gold beans; no currency conversion from the documented Douyin value.',
  },
  {
    id: 'douyin-life-potion',
    name: '生命药水',
    image: 'live-gifts/douyin-life-potion.png',
    officialId: 'CwaE5Zyq2ZvwgA4S9udpz1BTWMAM41FRkMN5WI5J8E7QJEUT6VFZK0USxig=',
    officialValue: 999,
    officialUnit: '抖币',
    appDemoPrice: null,
    assetKind: 'official public documentation gift icon; not an animation file',
    licenseStatus: 'unknown for independent-app redistribution',
    price: 999,
    category: '互动',
    effect: 'celebration',
    accent: '#d58afa',
    description: '互动心意 · 星光绽放',
    sourceKind: 'douyin-public-icon',
    priceNote: 'App-specific demo gold beans; no currency conversion from the documented Douyin value.',
  },
  {
    id: 'douyin-super-jet',
    name: '超能喷射',
    image: 'live-gifts/douyin-super-jet.png',
    officialId: 'P7zDZzpeO215SpUptB+aURb1+zC14UC9MY1+MHszKoF0p5gzYk8CNEbey60=',
    officialValue: 1200,
    officialUnit: '抖币',
    appDemoPrice: null,
    assetKind: 'official public documentation gift icon; not an animation file',
    licenseStatus: 'unknown for independent-app redistribution',
    price: 1200,
    category: '互动',
    effect: 'rocket',
    accent: '#d58afa',
    description: '互动心意 · 星光绽放',
    sourceKind: 'douyin-public-icon',
    priceNote: 'App-specific demo gold beans; no currency conversion from the documented Douyin value.',
  },
  {
    id: 'douyin-rare-treasure',
    name: '稀有宝箱',
    image: 'live-gifts/douyin-rare-treasure.png',
    officialId: 'rROiXLcY2saGvxHt3fAkYbWvbbikhEzbo0wpI794zEv+A2SCLrkNKYZEVuE=',
    officialValue: 3000,
    officialUnit: '抖币',
    appDemoPrice: null,
    assetKind: 'official public documentation gift icon; not an animation file',
    licenseStatus: 'unknown for independent-app redistribution',
    price: 3000,
    category: '互动',
    effect: 'crown',
    accent: '#d58afa',
    description: '互动心意 · 星光绽放',
    sourceKind: 'douyin-public-icon',
    priceNote: 'App-specific demo gold beans; no currency conversion from the documented Douyin value.',
  },
  {
    id: 'douyin-lucky-cube',
    name: '幸运魔方',
    image: 'live-gifts/douyin-lucky-cube.png',
    officialId: '9tPFzcpEQFovisU3j3coz5tqj/qQ5LHJQJWob/X5bLbxm1s7kYLj0aGSb4k=',
    officialValue: 1,
    officialUnit: '抖币',
    appDemoPrice: null,
    assetKind: 'official public documentation gift icon; not an animation file',
    licenseStatus: 'unknown for independent-app redistribution',
    price: 1,
    category: '互动',
    effect: 'celebration',
    accent: '#d58afa',
    description: '互动心意 · 星光绽放',
    sourceKind: 'douyin-public-icon',
    priceNote: 'App-specific demo gold beans; no currency conversion from the documented Douyin value.',
  },
];

// BEGIN SHIZHONG ORIENTAL SERIES
window.SHIZHONG_LIVE_GIFTS.push(
  ...[
    {
      id: 'oriental-tongxin-knot',
      name: '同心结',
      price: 9,
      image: 'oriental/oriental-tongxin-knot.png',
      effect: 'heart',
      orientalEffect: 'knot',
      category: '盛世华章',
      accent: '#BE2534',
      description:
        '一枚朱红盘长结垂着细金穗，把想说的祝福系在一起；适合送给刚认识的新朋友，也能放在主页作小巧挂件。',
      sourceKind: 'original-concept',
      series: '盛世华章',
      tier: '入门',
      subseries: '盛世雅物',
      shopPriceRM: 100,
    },
    {
      id: 'oriental-lantern',
      name: '灯笼',
      price: 19,
      image: 'oriental/oriental-lantern.png',
      effect: 'celebration',
      orientalEffect: 'lantern',
      category: '盛世华章',
      accent: '#D44627',
      description: '描金宫灯点亮暖黄烛光，沿着夜色缓缓升起；把团圆与平安的心意送到正在聊天的人面前。',
      sourceKind: 'original-concept',
      series: '盛世华章',
      tier: '入门',
      subseries: '盛世雅物',
      shopPriceRM: 280,
    },
    {
      id: 'oriental-folding-fan',
      name: '折扇',
      price: 39,
      image: 'oriental/oriental-folding-fan.png',
      effect: 'galaxy',
      orientalEffect: 'fan',
      category: '盛世华章',
      accent: '#966747',
      description: '一柄乌木折扇展开层叠水墨山峦，合拢时留下一缕金色光迹；适合送给喜欢旅行与山水的朋友。',
      sourceKind: 'original-concept',
      series: '盛世华章',
      tier: '入门',
      subseries: '盛世雅物',
      shopPriceRM: 520,
    },
    {
      id: 'oriental-blue-white-porcelain',
      name: '青花瓷',
      price: 199,
      image: 'oriental/oriental-blue-white-porcelain.png',
      effect: 'galaxy',
      orientalEffect: 'porcelain',
      category: '盛世华章',
      accent: '#386898',
      description: '白瓷小瓶映着细密青花缠枝纹，旋转间显出柔和釉光；让一份安静的雅意留在好友的礼物收藏里。',
      sourceKind: 'original-concept',
      series: '盛世华章',
      tier: '进阶',
      subseries: '盛世雅物',
      shopPriceRM: 2600,
    },
    {
      id: 'oriental-phoenix-flight',
      name: '凤凰于飞',
      price: 520,
      image: 'oriental/oriental-phoenix-flight.png',
      effect: 'crown',
      orientalEffect: 'phoenix',
      category: '盛世华章',
      accent: '#C84C42',
      description: '赤金凤凰舒展羽翼，尾羽如轻柔绸带掠过屏幕；送给并肩前行的人，纪念彼此照亮的一刻。',
      sourceKind: 'original-concept',
      series: '盛世华章',
      tier: '进阶',
      subseries: '盛世雅物',
      shopPriceRM: 7800,
    },
    {
      id: 'oriental-pipa-song',
      name: '琵琶行',
      price: 399,
      image: 'oriental/oriental-pipa-song.png',
      effect: 'galaxy',
      orientalEffect: 'pipa',
      category: '盛世华章',
      accent: '#B28355',
      description: '梨花木琵琶立在云纹绸带间，琴弦泛起细碎金芒；把一段无需言说的悠长心绪送进今晚的会话。',
      sourceKind: 'original-concept',
      series: '盛世华章',
      tier: '进阶',
      subseries: '盛世雅物',
      shopPriceRM: 4500,
    },
    {
      id: 'oriental-golden-dragon',
      name: '龙腾',
      price: 2999,
      image: 'oriental/oriental-golden-dragon.png',
      effect: 'crown',
      orientalEffect: 'dragon',
      category: '盛世华章',
      accent: '#D29B37',
      description: '鎏金祥龙穿过层叠云海腾空盘旋，龙鳞映着故宫红光；用一份壮阔礼物为朋友的重要时刻喝彩。',
      sourceKind: 'original-concept',
      series: '盛世华章',
      tier: '豪华',
      subseries: '盛世雅物',
      shopPriceRM: 48000,
    },
    {
      id: 'oriental-nine-ding',
      name: '九鼎',
      price: 3999,
      image: 'oriental/oriental-nine-ding.png',
      effect: 'crown',
      orientalEffect: 'ding',
      category: '盛世华章',
      accent: '#A9783D',
      description: '青铜古鼎承着九重云纹，鼎耳与金边在光束中渐次显现；适合纪念一项稳稳落地的重要成果。',
      sourceKind: 'original-concept',
      series: '盛世华章',
      tier: '豪华',
      subseries: '盛世雅物',
      shopPriceRM: 60000,
    },
    {
      id: 'oriental-qilin-treasure',
      name: '麒麟送宝',
      price: 5200,
      image: 'oriental/oriental-qilin-treasure.png',
      effect: 'celebration',
      orientalEffect: 'qilin',
      category: '盛世华章',
      accent: '#C88B3F',
      description: '瑞兽麒麟踏着祥云送来一只缀金宝匣，步伐轻快而隆重；把好事临门的祝愿留给特别的伙伴。',
      sourceKind: 'original-concept',
      series: '盛世华章',
      tier: '豪华',
      subseries: '盛世雅物',
      shopPriceRM: 72000,
    },
    {
      id: 'oriental-landscape-scroll',
      name: '江山如画',
      price: 12888,
      image: 'oriental/oriental-landscape-scroll.png',
      effect: 'galaxy',
      orientalEffect: 'scroll',
      category: '盛世华章',
      accent: '#887451',
      description: '长卷徐徐展开，黛色山峦、云水与金色楼阁在纸上相遇；把眼前的宽阔风景送给愿意同行的人。',
      sourceKind: 'original-concept',
      series: '盛世华章',
      tier: '顶级',
      subseries: '盛世雅物',
      shopPriceRM: 138000,
    },
    {
      id: 'oriental-phoenix-crown',
      name: '凤冠霞帔',
      price: 18888,
      image: 'oriental/oriental-phoenix-crown.png',
      effect: 'crown',
      orientalEffect: 'crown',
      category: '盛世华章',
      accent: '#C59042',
      description: '点翠凤冠嵌着金珠与红色流苏，霞帔般的柔光在身后舒展；为值得珍惜的喜庆日子添一场华美仪式。',
      sourceKind: 'original-concept',
      series: '盛世华章',
      tier: '顶级',
      subseries: '盛世雅物',
      shopPriceRM: 168000,
    },
    {
      id: 'oriental-heavenly-craft',
      name: '天工开物',
      price: 29999,
      image: 'oriental/oriental-heavenly-craft.png',
      effect: 'crown',
      orientalEffect: 'craft',
      category: '盛世华章',
      accent: '#D19B55',
      description:
        '匠作宝匣汇聚建筑飞檐、青花瓷片与龙凤金纹，层层打开如一座微缩工艺殿堂；献给认真创造生活的人。',
      sourceKind: 'original-concept',
      series: '盛世华章',
      tier: '顶级',
      subseries: '盛世雅物',
      shopPriceRM: 200000,
    },
    {
      id: 'oriental-azure-dragon',
      name: '青龙出海',
      price: 8888,
      image: 'oriental/oriental-azure-dragon.png',
      effect: 'galaxy',
      orientalEffect: 'azure-dragon',
      category: '盛世华章',
      accent: '#4A9A91',
      description: '青碧灵龙越过墨色海浪，长须与云气带出流动的翠金光；这份四灵藏品象征向新的方向出发。',
      sourceKind: 'original-concept',
      series: '盛世华章',
      tier: '豪华',
      subseries: '上古四灵',
      shopPriceRM: 82000,
    },
    {
      id: 'oriental-white-tiger',
      name: '白虎踏星',
      price: 6999,
      image: 'oriental/oriental-white-tiger.png',
      effect: 'galaxy',
      orientalEffect: 'white-tiger',
      category: '盛世华章',
      accent: '#AEB9C9',
      description: '银白猛虎踩过深蓝星轨，额间金纹随着步伐闪亮；为勇敢迈出一步的朋友留下利落而坚定的祝福。',
      sourceKind: 'original-concept',
      series: '盛世华章',
      tier: '豪华',
      subseries: '上古四灵',
      shopPriceRM: 76000,
    },
    {
      id: 'oriental-vermilion-bird',
      name: '朱雀涅槃',
      price: 9999,
      image: 'oriental/oriental-vermilion-bird.png',
      effect: 'crown',
      orientalEffect: 'vermilion-bird',
      category: '盛世华章',
      accent: '#D15036',
      description: '朱雀从金红羽焰中展翼而起，细小火羽化作温暖光点；送给刚走过低谷、再次拥抱新开始的人。',
      sourceKind: 'original-concept',
      series: '盛世华章',
      tier: '顶级',
      subseries: '上古四灵',
      shopPriceRM: 98000,
    },
    {
      id: 'oriental-black-tortoise',
      name: '玄武御天',
      price: 9888,
      image: 'oriental/oriental-black-tortoise.png',
      effect: 'galaxy',
      orientalEffect: 'black-tortoise',
      category: '盛世华章',
      accent: '#637C79',
      description: '龟蛇相依的玄武浮在深色云台之上，甲纹托起一圈温润的金色屏障；愿所爱之人安稳从容。',
      sourceKind: 'original-concept',
      series: '盛世华章',
      tier: '顶级',
      subseries: '上古四灵',
      shopPriceRM: 92000,
    },
    {
      id: 'oriental-golden-calligraphy',
      name: '一字千金',
      price: 29,
      image: 'oriental/oriental-golden-calligraphy.png',
      effect: 'galaxy',
      orientalEffect: 'calligraphy',
      category: '盛世华章',
      accent: '#A78147',
      description: '羊毫笔蘸开浓墨，在宣纸上写出一枚泛金的吉字；为正在努力的朋友送上一点鼓励与文采。',
      sourceKind: 'original-concept',
      series: '盛世华章',
      tier: '入门',
      subseries: '金榜题名',
      shopPriceRM: 380,
    },
    {
      id: 'oriental-top-scholar',
      name: '高中状元',
      price: 999,
      image: 'oriental/oriental-top-scholar.png',
      effect: 'celebration',
      orientalEffect: 'scholar',
      category: '盛世华章',
      accent: '#C33E35',
      description: '绛红状元帽缀着金色花翎，卷轴在旁缓缓展开；祝贺考试、面试或作品发布时的每一份认真准备。',
      sourceKind: 'original-concept',
      series: '盛世华章',
      tier: '进阶',
      subseries: '金榜题名',
      shopPriceRM: 18000,
    },
    {
      id: 'oriental-carp-dragon-gate',
      name: '鱼跃龙门',
      price: 1888,
      image: 'oriental/oriental-carp-dragon-gate.png',
      effect: 'rocket',
      orientalEffect: 'carp',
      category: '盛世华章',
      accent: '#D39B54',
      description: '赤金锦鲤冲出浪花跃向汉白玉龙门，水滴化作细碎星点；为迎来转机的好消息送上掌声。',
      sourceKind: 'original-concept',
      series: '盛世华章',
      tier: '豪华',
      subseries: '金榜题名',
      shopPriceRM: 30000,
    },
    {
      id: 'oriental-ao-champion',
      name: '独占鳌头',
      price: 11999,
      image: 'oriental/oriental-ao-champion.png',
      effect: 'crown',
      orientalEffect: 'ao',
      category: '盛世华章',
      accent: '#B8833E',
      description:
        '金鳌踏浪托起高台，卷云环绕如庆典舞台；把这一份荣耀感送给刚取得突破的朋友，纪念真正付出的努力。',
      sourceKind: 'original-concept',
      series: '盛世华章',
      tier: '顶级',
      subseries: '金榜题名',
      shopPriceRM: 112000,
    },
    {
      id: 'oriental-midnight-pagoda',
      name: '子时·夜明琉璃',
      price: 49,
      image: 'oriental/oriental-midnight-pagoda.png',
      effect: 'galaxy',
      orientalEffect: 'pagoda',
      category: '盛世华章',
      accent: '#6274A1',
      description: '子夜的琉璃小塔透出深蓝与金色微光，月影落在塔檐；陪晚睡的人把夜色过得柔和一点。',
      sourceKind: 'original-concept',
      series: '盛世华章',
      tier: '入门',
      subseries: '十二时辰',
      shopPriceRM: 680,
    },
    {
      id: 'oriental-dawn-corner-tower',
      name: '卯时·紫气东来',
      price: 69,
      image: 'oriental/oriental-dawn-corner-tower.png',
      effect: 'galaxy',
      orientalEffect: 'dawn',
      category: '盛世华章',
      accent: '#8E6795',
      description: '晨光从宫墙角楼后升起，紫金云霞在屋檐间流动；用清亮的一声早安开启新一天。',
      sourceKind: 'original-concept',
      series: '盛世华章',
      tier: '入门',
      subseries: '十二时辰',
      shopPriceRM: 880,
    },
    {
      id: 'oriental-noon-golden-cup',
      name: '午时·日光耀金',
      price: 99,
      image: 'oriental/oriental-noon-golden-cup.png',
      effect: 'galaxy',
      orientalEffect: 'noon',
      category: '盛世华章',
      accent: '#D19D44',
      description: '正午阳光照在鎏金杯盏上，杯沿折出几道明快光线；送给忙到中午也记得停下歇息的朋友。',
      sourceKind: 'original-concept',
      series: '盛世华章',
      tier: '入门',
      subseries: '十二时辰',
      shopPriceRM: 1200,
    },
    {
      id: 'oriental-dusk-goose',
      name: '酉时·晚霞落雁',
      price: 79,
      image: 'oriental/oriental-dusk-goose.png',
      effect: 'heart',
      orientalEffect: 'dusk',
      category: '盛世华章',
      accent: '#B45E59',
      description: '晚霞染红飞檐，归雁掠过层层绛色云彩；在一天将尽时，把温柔的问候送给惦念的人。',
      sourceKind: 'original-concept',
      series: '盛世华章',
      tier: '入门',
      subseries: '十二时辰',
      shopPriceRM: 980,
    },
  ]
);
// END SHIZHONG ORIENTAL SERIES
