// 风控中心: account risk control (rules per scene with preset levels, slider check, block / allow lists, event log)
// and Blue V (蓝V) verified accounts. Server: server/Shizhong.Api/Modules/Risk (RiskAdmin.cs lists the endpoints).
import UserRisk from './UserRisk.vue';

const T = (zh, en) => ({ zh, en });

export default {
  menu: 'risk',
  order: 58,
  icon: 'Lock',
  title: T('风控中心', 'Risk control'),
  routes: [
    { path: '/risk/overview', component: () => import('./Overview.vue'), meta: { title: T('风控总览', 'Overview'), perm: 'risk.view' }, menu: true },
    { path: '/risk/policy', component: () => import('./Policy.vue'), meta: { title: T('风控策略', 'Policy'), perm: 'risk.view' }, menu: true },
    { path: '/risk/events', component: () => import('./Events.vue'), meta: { title: T('风控记录', 'Events'), perm: 'risk.view' }, menu: true },
    { path: '/risk/lists', component: () => import('./Lists.vue'), meta: { title: T('黑白名单', 'Block & allow lists'), perm: 'risk.view' }, menu: true },
    { path: '/risk/verified', component: () => import('./Verified.vue'), meta: { title: T('蓝V认证', 'Blue V'), perm: 'risk.view' }, menu: true },
  ],
  userTabs: [{ key: 'risk', title: T('风控', 'Risk'), perm: 'risk.view', component: UserRisk }],
  messages: {
    zh: {
      risk: {
        blueV: '蓝V', blueVHint: '蓝V账号跳过所有风控规则（黑名单和封禁除外），App 里显示认证标识',
        scene: {
          register: '注册', login: '登录', friend: '加好友', groupJoin: '加群', groupCreate: '建群', groupInvite: '拉人进群', greet: '打招呼',
          penalty: '自动处罚', captcha: '滑块验证',
        },
        action: { captcha: '要求滑块', block: '拦截', lock: '锁定账号', mute: '自动禁言', fail: '滑块失败', pass: '通过' },
        level: { off: '关闭', light: '轻度', medium: '中度', heavy: '重度', severe: '严重', custom: '自定义' },
        captchaMode: { off: '关闭', always: '每次都要', risky: '仅在触发风险时' },
        rule: { blockList: '命中黑名单', always: '每次都要滑块', slider: '滑块验证' },
        failReason: { position: '拖动位置不对', track: '拖动轨迹异常（疑似脚本）', expired: '滑块已过期' },
        zero: {
          limit: '不限', captchaAfter: '不按此条件', maxFailures: '不锁定', ipFailuresHour: '不封 IP', violationsToMute: '不自动禁言',
          newAccountHours: '不区分新老账号', minAccountHours: '不限', newAccountDay: '保护期内禁止',
        },
        detail: {
          limit: '已 {used} + 本次 {qty}，上限 {limit}', reached: '已有 {used}，上限 {limit}', age: '注册 {age} 小时，需满 {min} 小时',
          locked: '锁定 {n} 分钟', ipBlocked: '每小时输错 {n} 次，封 IP {m} 分钟', muted: '24 小时内被拦截 {n} 次，禁言 {h} 小时',
          perInvite: '一次拉 {n} 人，上限 {max}', newAccount: '新账号（注册 {age} 小时）：已 {used} + 本次 {qty}，上限 {limit}', invalidToken: '滑块凭证无效',
        },
        kind: { ip: 'IP', device: '设备', phone: '手机号', email: '邮箱', emailDomain: '邮箱域名', nameKeyword: '昵称关键词' },
        listType: { block: '黑名单', allow: '白名单' },
        source: { manual: '手动', auto: '自动', domain: '域名认证' },
        blockIp: '封禁 IP', blockDevice: '封禁设备', blockThisIp: '封禁此 IP', viewMember: '查看会员', viewEvents: '查看记录',
        ov: {
          title: '风控总览', level: '当前风控等级', changePolicy: '调整策略', today: '今日',
          captcha: '要求滑块', block: '拦截', lock: '锁定账号', mute: '自动禁言', fail: '滑块失败', verified: '蓝V账号', blockList: '生效黑名单',
          allowList: '生效白名单', autoBlocks: '其中自动封禁 {n} 条', muted: '当前禁言中的会员',
          slider: '滑块（本次启动以来）：发出 {issued} 次，通过 {solved} 次，失败 {failed} 次',
          actionsTrend: '通过的敏感操作', eventsTrend: '风控处置', actions: '敏感操作',
          scenes: '各场景', scene: '场景', sceneActions: '通过的操作', blockRate: '拦截率', blockRateHint: '（拦截 + 锁定）÷（通过 + 拦截 + 锁定）',
          topIps: '触发最多的 IP', topUsers: '触发最多的会员', events: '记录', blocks: '拦截', users: '涉及会员', lastAt: '最近一次',
          listed: { block: '已封禁', allow: '白名单' }, mutedNow: '禁言中', evShort: '记录', blockShort: '封禁', blockNote: '风控总览：{period}触发 {events} 次，其中拦截 {blocks} 次',
        },
        pol: {
          title: '风控策略', current: '当前', inUse: '正在使用', use: '启用此等级', viewing: '{level} 的规则',
          confirmUse: '把风控等级切换为「{level}」？切换后立即对所有会员生效。', switched: '已切换为「{level}」',
          customize: '基于此等级自定义', editCustom: '编辑自定义规则', customTitle: '自定义规则（基于「{level}」）', saveUse: '保存并启用',
          saveOnly: '仅保存（不切换等级）', confirmCustom: '保存自定义规则并切换为「自定义」等级？立即生效。', customSaved: '自定义规则已保存',
          byLevel: '按等级查看', compare: '对比全部等级', compareHint: '颜色越深越严格。「自定义」列里和「轻度」不同的值加粗显示。',
          field: '规则', notApplicable: '—（未开启新账号保护期）', max: '最大 {max}', general: '通用参数',
          generalHint: '滑块误差和有效期、额外的临时邮箱域名、记录保留天数。',
          noCustom: '还没有保存过自定义规则，当前显示的是基于「轻度」的默认值。', recommended: '适用',
          when: {
            off: '内测、压测', light: '日常运营（默认）', medium: '推广期、新城市开城', heavy: '正在被刷号 / 批量骚扰', severe: '大规模攻击时临时使用',
            custom: '需要单独调整某几项时',
          },
          differsFrom: '与「{level}」不同',
        },
        ev: {
          title: '风控记录', q: '账号 / IP / 设备 / 会员', handled: '已处理', unhandled: '未处理', markHandled: '标记已处理',
          rule: '触发规则', member: '会员 / 账号', ip: 'IP', device: '设备', platform: '平台', detail: '详情', level: '当时等级',
          filterIp: 'IP：{ip}', filterUser: '会员 ID：{id}', clear: '清除',
        },
        lists: {
          title: '黑白名单', add: '新增', addTitle: '新增名单', editTitle: '编辑名单', value: '值', type: '名单', note: '备注', validity: '有效期',
          permanent: '永久', hours: '小时', keep: '保持不变（{time}）', expiresAt: '到期时间', expired: '已过期', active: '生效中', onlyActive: '只看生效中',
          createdBy: '添加人', all: '全部', unlock: '解除登录锁定', unlockTitle: '解除登录锁定',
          unlockHint: '清除账号的「密码输错」锁定；填写 IP 时同时解除该 IP 的封禁（自动或手动）。', account: '账号（手机或邮箱）',
          unlockDone: '已解除（{n} 项）', confirmDelete: '删除「{value}」？', validityHint: '到期后自动失效',
          placeholder: {
            ip: '例如 175.139.12.34', device: '设备标识（风控记录里的「设备」）', phone: '+60 12-345 6789', email: 'name@example.com',
            emailDomain: 'example.com', nameKeyword: '昵称包含这个词就拦截注册',
          },
          allowHint: '白名单：跳过所有频率限制和滑块（昵称关键词只有黑名单）',
          presets: { h1: '1 小时', h24: '1 天', h168: '7 天', h720: '30 天' },
        },
        v: {
          title: '蓝V认证', accounts: '蓝V账号', domains: '域名认证', q: '昵称 / 手机 / 邮箱 / 用户ID / 认证名称', label: '认证名称',
          source: '来源', verifiedAt: '认证时间', verifiedBy: '操作人', add: '添加蓝V', addTitle: '添加蓝V', search: '搜索会员（昵称 / 手机 / 邮箱 / 用户ID）',
          revoke: '取消认证', confirmRevoke: '取消「{name}」的蓝V认证？', editLabel: '修改认证名称', granted: '已认证', labelPlaceholder: '留空使用默认：{label}',
          domain: '域名', domainAdd: '添加域名', domainTitle: '添加认证域名', enabled: '启用', users: '该域名账号', verifiedUsers: '已认证',
          apply: '认证现有账号', applyConfirm: '把邮箱为 @{domain} 的现有账号全部设为蓝V（{label}）？', applied: '已认证 {n} 个账号',
          deleteTitle: '删除域名 {domain}', alsoRevoke: '同时取消这个域名下自动认证的账号', deleted: '已删除，取消了 {n} 个账号的认证',
          domainHint: '用这些域名邮箱注册的账号自动成为蓝V（比如公司员工、合作伙伴）。停用后不再自动认证新账号，已认证的保留。',
          kindPersona: '运营人物', settings: '蓝V设置',
        },
        user: {
          state: '蓝V状态', notVerified: '未认证', grant: '设为蓝V', muted: '禁言到', notMuted: '未禁言', attempts: '剩余登录尝试',
          noLock: '当前等级不锁定账号', locked: '已锁定', unlock: '解除锁定', last24h: '最近 24 小时的敏感操作', recent: '最近的风控记录',
          account: '登录账号', noAccount: '没有手机或邮箱',
        },
      },
      err: {
        'risk.level': '未知的风控等级', 'risk.listKind': '名单类型不正确', 'risk.listValue': '值的格式不正确', 'risk.listExists': '名单里已经有这一项',
        'risk.domainInvalid': '域名格式不正确', 'risk.domainExists': '这个域名已经添加过', 'risk.scene': '未知的场景',
      },
    },
    en: {
      risk: {
        blueV: 'Blue V', blueVHint: 'Blue V accounts skip every risk rule (not bans or block lists) and show a badge in the app',
        scene: {
          register: 'Sign-up', login: 'Sign-in', friend: 'Friend requests', groupJoin: 'Joining groups', groupCreate: 'Creating groups',
          groupInvite: 'Adding people to groups', greet: 'Greetings', penalty: 'Automatic penalties', captcha: 'Slider check',
        },
        action: { captcha: 'Slider asked', block: 'Blocked', lock: 'Account locked', mute: 'Auto-muted', fail: 'Slider failed', pass: 'Passed' },
        level: { off: 'Off', light: 'Light', medium: 'Medium', heavy: 'Heavy', severe: 'Severe', custom: 'Custom' },
        captchaMode: { off: 'Off', always: 'Every time', risky: 'Only on risk signals' },
        rule: { blockList: 'On a block list', always: 'Slider every time', slider: 'Slider check' },
        failReason: { position: 'Wrong position', track: 'Unnatural drag (likely a script)', expired: 'Slider expired' },
        zero: {
          limit: 'No limit', captchaAfter: 'Not used', maxFailures: 'Never locks', ipFailuresHour: 'Never blocks', violationsToMute: 'No auto mute',
          newAccountHours: 'All accounts alike', minAccountHours: 'No minimum', newAccountDay: 'Not allowed in the period',
        },
        detail: {
          limit: '{used} done + {qty} now, limit {limit}', reached: '{used} already, limit {limit}', age: 'Account {age} h old, needs {min} h',
          locked: 'Locked {n} min', ipBlocked: '{n} wrong passwords in an hour, IP blocked {m} min', muted: 'Blocked {n} times in 24 h, muted {h} h',
          perInvite: '{n} people at once, limit {max}', newAccount: 'New account ({age} h): {used} done + {qty} now, limit {limit}', invalidToken: 'Invalid slider pass',
        },
        kind: { ip: 'IP', device: 'Device', phone: 'Phone', email: 'E-mail', emailDomain: 'E-mail domain', nameKeyword: 'Name keyword' },
        listType: { block: 'Block', allow: 'Allow' },
        source: { manual: 'Manual', auto: 'Automatic', domain: 'Domain' },
        blockIp: 'Block IP', blockDevice: 'Block device', blockThisIp: 'Block this IP', viewMember: 'Member', viewEvents: 'Events',
        ov: {
          title: 'Risk overview', level: 'Risk level', changePolicy: 'Change policy', today: 'Today',
          captcha: 'Slider asked', block: 'Blocked', lock: 'Accounts locked', mute: 'Auto-muted', fail: 'Slider failed', verified: 'Blue V accounts',
          blockList: 'Active block entries', allowList: 'Active allow entries', autoBlocks: '{n} automatic', muted: 'Members muted now',
          slider: 'Slider since start: {issued} issued, {solved} solved, {failed} failed',
          actionsTrend: 'Sensitive actions that went through', eventsTrend: 'Risk responses', actions: 'Actions',
          scenes: 'By scene', scene: 'Scene', sceneActions: 'Actions', blockRate: 'Block rate', blockRateHint: '(blocked + locked) ÷ (actions + blocked + locked)',
          topIps: 'Top IPs', topUsers: 'Top members', events: 'Events', blocks: 'Blocks', users: 'Members', lastAt: 'Last',
          listed: { block: 'Blocked', allow: 'Allowed' }, mutedNow: 'Muted', evShort: 'Events', blockShort: 'Block', blockNote: 'From the overview: {events} events ({blocks} blocks), {period}',
        },
        pol: {
          title: 'Risk policy', current: 'Current', inUse: 'In use', use: 'Use this level', viewing: 'Rules of {level}',
          confirmUse: 'Switch the risk level to “{level}”? It applies to every member at once.', switched: 'Switched to “{level}”',
          customize: 'Customise from this level', editCustom: 'Edit custom rules', customTitle: 'Custom rules (from “{level}”)', saveUse: 'Save and use',
          saveOnly: 'Save only (keep the level)', confirmCustom: 'Save the custom rules and switch to Custom? Applies at once.', customSaved: 'Custom rules saved',
          byLevel: 'By level', compare: 'Compare levels', compareHint: 'Darker = stricter. Custom values that differ from Light are in bold.',
          field: 'Rule', notApplicable: '— (no new-account period)', max: 'max {max}', general: 'General settings',
          generalHint: 'Slider tolerance and validity, extra disposable e-mail domains, how long events are kept.',
          noCustom: 'No custom rules saved yet; showing the Light defaults.', recommended: 'For',
          when: {
            off: 'Closed tests, load tests', light: 'Everyday (default)', medium: 'Campaigns, new city launches', heavy: 'Under bulk sign-ups / spam',
            severe: 'Temporary, during a large attack', custom: 'Fine-tuning a few rules',
          },
          differsFrom: 'Differs from “{level}”',
        },
        ev: {
          title: 'Risk events', q: 'Account / IP / device / member', handled: 'Handled', unhandled: 'Open', markHandled: 'Mark handled',
          rule: 'Rule', member: 'Member / account', ip: 'IP', device: 'Device', platform: 'Platform', detail: 'Detail', level: 'Level',
          filterIp: 'IP: {ip}', filterUser: 'Member ID: {id}', clear: 'Clear',
        },
        lists: {
          title: 'Block & allow lists', add: 'Add', addTitle: 'Add entry', editTitle: 'Edit entry', value: 'Value', type: 'List', note: 'Note', validity: 'Valid for',
          permanent: 'Permanent', hours: 'hours', keep: 'Unchanged ({time})', expiresAt: 'Expires', expired: 'Expired', active: 'Active', onlyActive: 'Active only',
          createdBy: 'Added by', all: 'All', unlock: 'Unlock sign-in', unlockTitle: 'Unlock sign-in',
          unlockHint: 'Clears the wrong-password lock of an account; with an IP, also lifts that IP’s block (automatic or manual).', account: 'Account (phone or e-mail)',
          unlockDone: 'Unlocked ({n})', confirmDelete: 'Delete “{value}”?', validityHint: 'Expires automatically',
          placeholder: {
            ip: 'e.g. 175.139.12.34', device: 'Device ID (from the events)', phone: '+60 12-345 6789', email: 'name@example.com',
            emailDomain: 'example.com', nameKeyword: 'Sign-ups whose name contains this are refused',
          },
          allowHint: 'Allow: skips every limit and slider (name keywords are block-only)',
          presets: { h1: '1 hour', h24: '1 day', h168: '7 days', h720: '30 days' },
        },
        v: {
          title: 'Blue V', accounts: 'Blue V accounts', domains: 'Verified domains', q: 'Name / phone / e-mail / ID / label', label: 'Label',
          source: 'Source', verifiedAt: 'Verified', verifiedBy: 'By', add: 'Add Blue V', addTitle: 'Add Blue V', search: 'Find a member (name / phone / e-mail / ID)',
          revoke: 'Revoke', confirmRevoke: 'Revoke Blue V from “{name}”?', editLabel: 'Edit label', granted: 'Verified', labelPlaceholder: 'Empty = default: {label}',
          domain: 'Domain', domainAdd: 'Add domain', domainTitle: 'Add a verified domain', enabled: 'Enabled', users: 'Accounts', verifiedUsers: 'Verified',
          apply: 'Verify existing accounts', applyConfirm: 'Make every existing @{domain} account Blue V ({label})?', applied: '{n} accounts verified',
          deleteTitle: 'Delete {domain}', alsoRevoke: 'Also revoke the accounts verified through this domain', deleted: 'Deleted; {n} accounts revoked',
          domainHint: 'Accounts that sign up with an e-mail on these domains become Blue V (staff, partners). Disabling stops new ones; verified accounts stay.',
          kindPersona: 'Persona', settings: 'Blue V settings',
        },
        user: {
          state: 'Blue V', notVerified: 'Not verified', grant: 'Make Blue V', muted: 'Muted until', notMuted: 'Not muted', attempts: 'Sign-in attempts left',
          noLock: 'The current level does not lock accounts', locked: 'Locked', unlock: 'Unlock', last24h: 'Sensitive actions, last 24 h', recent: 'Recent risk events',
          account: 'Sign-in account', noAccount: 'No phone or e-mail',
        },
      },
      err: {
        'risk.level': 'Unknown risk level', 'risk.listKind': 'Unknown list kind', 'risk.listValue': 'Invalid value', 'risk.listExists': 'Already on the list',
        'risk.domainInvalid': 'Invalid domain', 'risk.domainExists': 'Domain already added', 'risk.scene': 'Unknown scene',
      },
    },
  },
};
