#!/usr/bin/env python3
"""
Build the Windows / IIS deployment package: API + app (site) + admin console + database scripts.

    python tools/deploy/build_server.py            # → dist/shizhong-server-<build>/ and .zip
    python tools/deploy/build_server.py --no-admin # skip the console build (reuse admin/dist)

Layout of the package (copy the whole folder to the IIS site's physical path):

    Shizhong.Api.dll …           the ASP.NET Core 8 app (framework-dependent: install the .NET 8 Hosting Bundle)
    web.config                   IIS: ASP.NET Core Module v2, in-process, WebSockets on, 64 MB uploads
    appsettings.json             defaults (no secrets)
    appsettings.Production.json  EDIT: connection string (template written here if absent)
    site/                        the H5 app (same files as tools/release.py produces)
    admin/                       the console (served at /admin)
    db/migrations/*.sql          applied automatically at start (or run sql/ scripts by hand)
    sql/shizhong-schema.sql      every migration in one script, for SSMS
    sql/create-app-login.sql     least-privilege SQL login for the app (recommended instead of sa)
    logs/                        stdout logs if you enable them in web.config
"""
import argparse, os, re, shutil, subprocess, sys, zipfile

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "tools"))
import release  # noqa: E402  (site file selection)

WEB_CONFIG = """<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\\Shizhong.Api.dll" stdoutLogEnabled="false" stdoutLogFile=".\\logs\\stdout" hostingModel="inprocess">
        <environmentVariables>
          <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Production" />
        </environmentVariables>
      </aspNetCore>
      <!-- realtime chat, live rooms and call signalling use WebSockets (IIS feature "WebSocket Protocol" must be installed) -->
      <webSocket enabled="true" />
      <security>
        <requestFiltering>
          <requestLimits maxAllowedContentLength="67108864" />
          <hiddenSegments>
            <add segment="db" />
            <add segment="sql" />
            <add segment="logs" />
          </hiddenSegments>
        </requestFiltering>
      </security>
      <httpProtocol>
        <customHeaders>
          <remove name="X-Powered-By" />
        </customHeaders>
      </httpProtocol>
    </system.webServer>
  </location>
</configuration>
"""

PRODUCTION_SETTINGS = """{
  "ConnectionStrings": {
    "Main": "Server=127.0.0.1;Database=shizhong;User Id=shizhong_app;Password=CHANGE_ME;TrustServerCertificate=True;Encrypt=True;Max Pool Size=200"
  },
  "Logging": { "LogLevel": { "Default": "Warning", "Microsoft.Hosting.Lifetime": "Information", "Shizhong": "Information" } }
}
"""

APP_LOGIN = """-- Run once in SSMS as sa (or another sysadmin). Replace the password.
-- The app then connects as shizhong_app instead of sa (see appsettings.Production.json).
USE [master];
IF NOT EXISTS (SELECT 1 FROM sys.sql_logins WHERE name = N'shizhong_app')
  CREATE LOGIN [shizhong_app] WITH PASSWORD = N'CHANGE_ME_Strong#Passw0rd', CHECK_POLICY = ON;
GO
IF DB_ID(N'shizhong') IS NULL CREATE DATABASE [shizhong];
GO
USE [shizhong];
IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'shizhong_app')
  CREATE USER [shizhong_app] FOR LOGIN [shizhong_app];
-- db_owner on this database only: the app applies its own migrations at start-up.
ALTER ROLE [db_owner] ADD MEMBER [shizhong_app];
GO
"""


def run(cmd, cwd=ROOT):
    print("$", " ".join(cmd))
    subprocess.run(cmd, cwd=cwd, check=True)


def schema_script(migrations_dir):
    """All migrations as one idempotent-by-version script (records each in dbo.SchemaVersions)."""
    parts = [
        "-- 适中 Shizhong: full database schema. Generated by tools/deploy/build_server.py.",
        "-- Safe to run on an empty database; already-applied migrations are skipped; each migration is all-or-nothing.",
        "SET ANSI_NULLS ON;",
        "SET QUOTED_IDENTIFIER ON;",
        "SET XACT_ABORT ON;",
        "GO",
        "IF OBJECT_ID('dbo.SchemaVersions') IS NULL",
        "  CREATE TABLE dbo.SchemaVersions (Name NVARCHAR(200) PRIMARY KEY, AppliedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME());",
        "GO",
    ]
    for name in sorted(os.listdir(migrations_dir), key=str.lower):
        if not name.endswith(".sql"):
            continue
        body = open(os.path.join(migrations_dir, name), encoding="utf-8").read()
        batches = [b.strip() for b in re.split(r"^\s*GO\s*;?\s*$", body, flags=re.M | re.I) if b.strip()]
        parts.append(f"-- ===== {name}")
        parts.append(f"IF NOT EXISTS (SELECT 1 FROM dbo.SchemaVersions WHERE Name = N'{name}')")
        parts.append("BEGIN")
        parts.append("  BEGIN TRANSACTION;")
        for b in batches:
            # each batch runs through sp_executesql so the whole migration can sit inside IF … BEGIN … END
            parts.append("  EXEC sp_executesql N'" + b.replace("'", "''") + "';")
        parts.append(f"  INSERT INTO dbo.SchemaVersions(Name) VALUES (N'{name}');")
        parts.append("  COMMIT TRANSACTION;")
        parts.append("END")
        parts.append("GO")
    return "\n".join(parts) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-admin", action="store_true")
    args = ap.parse_args()
    build = release.build_id().replace("-v2", "-v3")
    out = os.path.join(ROOT, "dist", f"shizhong-server-{build}")
    shutil.rmtree(out, ignore_errors=True)

    # 1. API
    run(["dotnet", "publish", "server/Shizhong.Api/Shizhong.Api.csproj", "-c", "Release", "-o", out, "--nologo"])
    for junk in ["appsettings.Local.json", "appsettings.Development.json"]:
        p = os.path.join(out, junk)
        if os.path.exists(p):
            os.remove(p)
    with open(os.path.join(out, "web.config"), "w", encoding="utf-8") as fh:
        fh.write(WEB_CONFIG)
    with open(os.path.join(out, "appsettings.Production.json"), "w", encoding="utf-8") as fh:
        fh.write(PRODUCTION_SETTINGS)
    os.makedirs(os.path.join(out, "logs"), exist_ok=True)

    # 2. database scripts
    mig_src = os.path.join(ROOT, "server", "db", "migrations")
    shutil.copytree(mig_src, os.path.join(out, "db", "migrations"))
    os.makedirs(os.path.join(out, "sql"), exist_ok=True)
    with open(os.path.join(out, "sql", "shizhong-schema.sql"), "w", encoding="utf-8-sig") as fh:
        fh.write(schema_script(mig_src))
    with open(os.path.join(out, "sql", "create-app-login.sql"), "w", encoding="utf-8-sig") as fh:
        fh.write(APP_LOGIN)

    # 3. the app (site)
    site = os.path.join(out, "site")
    count = 0
    for dirpath, dirnames, filenames in os.walk(ROOT):
        rel_dir = os.path.relpath(dirpath, ROOT).replace("\\", "/")
        prefix = "" if rel_dir == "." else rel_dir + "/"
        dirnames[:] = [d for d in dirnames if release.included(prefix + d)]
        for f in filenames:
            rel = prefix + f
            if release.included(rel):
                dst = os.path.join(site, rel)
                os.makedirs(os.path.dirname(dst), exist_ok=True)
                shutil.copy2(os.path.join(ROOT, rel), dst)
                count += 1
    print(f"site: {count} files")

    # 4. admin console
    admin_dir = os.path.join(ROOT, "admin")
    if not args.no_admin:
        if not os.path.isdir(os.path.join(admin_dir, "node_modules")):
            run(["npm", "install", "--no-audit", "--no-fund"], cwd=admin_dir)
        run(["npx", "vite", "build"], cwd=admin_dir)
    shutil.copytree(os.path.join(admin_dir, "dist"), os.path.join(out, "admin"))

    # 5. zip
    zpath = out + ".zip"
    with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as z:
        for dirpath, _, filenames in os.walk(out):
            for f in filenames:
                full = os.path.join(dirpath, f)
                z.write(full, os.path.relpath(full, out).replace("\\", "/"))
    print(f"wrote {out}\nwrote {zpath} ({os.path.getsize(zpath) / 1048576:.1f} MB)")


if __name__ == "__main__":
    main()
