"""Generate assets/gift-art/manifest.js (owner: assets).

    python assets/gift-art/_tools/build_manifest.py

Reads gift ids from gift-data.js and live-data.js, and the Malaysia series from
malaysia-series.json. Fails loudly if any gift id has no artwork on disk.
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ART = os.path.abspath(os.path.join(HERE, '..'))
ASSETS = os.path.abspath(os.path.join(ART, '..'))
ROOT = os.path.abspath(os.path.join(ASSETS, '..'))

F, O, A = 'F', 'O', 'A'  # credit keys, expanded in the JS header
# live-only ids that reuse a Fluent shop image
LIVE_ALIAS = {'flowers': 'bouquet', 'bear': 'teddy-bear', 'cake': 'birthday-cake',
              'car': 'racing-car', 'planet': 'ringed-planet'}


def image_ids(path):
    """[(id, image)] for every object literal in a data file whose image is gift artwork."""
    src = open(os.path.join(ROOT, path), encoding='utf-8').read()
    marks = [m for m in re.finditer(r"(?<![\w-])id: '([^']+)'", src)]
    out = []
    for i, m in enumerate(marks):
        chunk = src[m.end():marks[i + 1].start() if i + 1 < len(marks) else len(src)]
        im = re.search(r"(?<![\w-])image: '((?:gifts|oriental|live-gifts)/[^']+)'", chunk)
        if im:
            out.append((m.group(1), im.group(1)))
    return out


def entry(full, thumb, charm, credit):
    for p in (full, thumb, charm):
        assert os.path.exists(os.path.join(ASSETS, p)), p
    return (full, thumb, charm, credit)


def main():
    art = {}
    shop = image_ids('gift-data.js')
    live = image_ids('live-data.js')
    for gid, img in shop + live:
        if gid in art:
            continue
        folder, fn = img.split('/', 1)
        name = fn.rsplit('.', 1)[0]
        if folder == 'gifts':
            art[gid] = entry('gift-art/fluent/%s.png' % name, 'gift-art/fluent/%s.png' % name,
                             'gift-art/fluent/%s.charm.png' % name, F)
        elif folder == 'oriental':
            b = 'gift-art/oriental/' + name
            art[gid] = entry(b + '.png', b + '.thumb.png', b + '.charm.png', A)
        elif folder == 'live-gifts':
            b = 'gift-art/live/' + gid
            art[gid] = entry(b + '.png', b + '.png', b + '.charm.png', F)
        else:
            raise SystemExit('unmapped image %s for %s' % (img, gid))
    for gid, target in LIVE_ALIAS.items():
        assert art.get(gid) == art.get(target) or gid in art, gid
    series = json.load(open(os.path.join(ART, 'malaysia-series.json'), encoding='utf-8'))
    for g in series:
        p = 'gift-art/malaysia/%s.svg' % g['id']
        art[g['id']] = entry(p, p, p, O)

    shop_ids = [g for g, _ in shop]
    live_ids = [g for g, _ in live]
    lines = []
    for gid, (full, thumb, charm, credit) in art.items():
        lines.append("    '%s': { full: '%s', thumb: '%s', charm: '%s', credit: %s }," % (gid, full, thumb, charm, credit))
    series_js = json.dumps(series, ensure_ascii=False, indent=2).replace('\n', '\n  ')
    js = '''/* Gift artwork manifest (owner: assets). GENERATED by assets/gift-art/_tools/build_manifest.py.
 *
 * window.SHIZHONG_GIFT_ART[giftId] = { full, thumb, charm, credit }
 *   paths are relative to assets/ (prefix with 'assets/' from index.html);
 *   full  = detail / effect artwork (oriental: max 512px, keeps aspect; fluent/live: 256px; malaysia: SVG)
 *   thumb = square grid tile (256px or SVG)
 *   charm = square 96px avatar charm / chat bubble icon (SVG for the Malaysia series)
 * window.SHIZHONG_GIFT_ART_SERIES.malaysia = the 大马风情 / Malaysia gift list (same data as
 *   malaysia-series.json, inlined so it also works from file:// where fetch() is blocked).
 *
 * Adding art: drop files into gift-art/<set>/, extend the build script, re-run it.
 * Credits: see gift-art/CREDITS.md. %d shop ids, %d live ids, %d Malaysia ids, %d entries.
 */
(function () {
  'use strict';
  var F = 'Microsoft Fluent Emoji (MIT)';
  var O = 'Shizhong original';
  var A = 'Shizhong original (AI-assisted render)';
  var art = {
%s
  };
  var target = window.SHIZHONG_GIFT_ART || (window.SHIZHONG_GIFT_ART = {});
  Object.keys(art).forEach(function (id) {
    target[id] = art[id];
  });
  var series = window.SHIZHONG_GIFT_ART_SERIES || (window.SHIZHONG_GIFT_ART_SERIES = {});
  series.malaysia = %s;
})();
''' % (len(set(shop_ids)), len(set(live_ids)), len(series), len(art), '\n'.join(lines), series_js)
    with open(os.path.join(ART, 'manifest.js'), 'w', encoding='utf-8', newline='\n') as f:
        f.write(js)
    print('shop', len(set(shop_ids)), 'live', len(set(live_ids)), 'malaysia', len(series), 'entries', len(art))


if __name__ == '__main__':
    main()
