"""Hand-authored SVG source for the 大马风情 / Malaysia gift series (owner: assets).

    python assets/gift-art/_tools/malaysia_svg.py

writes assets/gift-art/malaysia/<id>.svg. Style rules shared by all 12 pieces:
viewBox 0 0 256 256, light from the top-left, 2-3 stop gradients, one soft top-left
highlight per volume, one soft contact shadow at y~226, no text, no external refs.
Only repetitive parts (durian spikes, ketupat weave, satay chunks) are generated by loops.
"""
import math
import os

OUT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'malaysia'))


def n(v):
    """Compact number formatting."""
    r = round(v, 1)
    return str(int(r)) if r == int(r) else str(r)


def svg(defs, body):
    return ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256">'
            '<defs>' + defs + '</defs>' + body + '</svg>')


def lg(id_, stops, x1=0, y1=0, x2=0, y2=1, extra=''):
    s = ''.join('<stop offset="%s" stop-color="%s"%s/>' % (
        o, c, (' stop-opacity="%s"' % op) if op is not None else '') for o, c, op in
        [(t + (None,))[:3] for t in stops])
    return '<linearGradient id="%s" x1="%s" y1="%s" x2="%s" y2="%s"%s>%s</linearGradient>' % (
        id_, x1, y1, x2, y2, extra, s)


def rg(id_, stops, cx=.35, cy=.3, r=.75, extra=''):
    s = ''.join('<stop offset="%s" stop-color="%s"%s/>' % (
        o, c, (' stop-opacity="%s"' % op) if op is not None else '') for o, c, op in
        [(t + (None,))[:3] for t in stops])
    return '<radialGradient id="%s" cx="%s" cy="%s" r="%s"%s>%s</radialGradient>' % (id_, cx, cy, r, extra, s)


SHADOW_DEF = rg('sh', [(0, '#2B1A10', .30), (.6, '#2B1A10', .12), (1, '#2B1A10', 0)], .5, .5, .5)
BLUR = '<filter id="bl" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation="2.4"/></filter>'


def shadow(cx=128, cy=226, rx=80, ry=12):
    return '<ellipse cx="%s" cy="%s" rx="%s" ry="%s" fill="url(#sh)"/>' % (cx, cy, rx, ry)


def hl(cx, cy, rx, ry, rot=-30, op=.55):
    """Soft top-left specular highlight."""
    return ('<ellipse cx="%s" cy="%s" rx="%s" ry="%s" transform="rotate(%s %s %s)" fill="#fff" '
            'opacity="%s" filter="url(#bl)"/>' % (cx, cy, rx, ry, rot, cx, cy, op))


ART = {}

# ---------------------------------------------------------------- Teh Tarik
ART['my-teh-tarik'] = svg(
    SHADOW_DEF + BLUR
    + lg('tea', [(0, '#E7A864'), (.5, '#C77B37'), (1, '#8A4718')], 0, 0, 1, 0)
    + lg('foam', [(0, '#FFF8EA'), (.6, '#F6DDB4'), (1, '#E2B57C')])
    + lg('gl', [(0, '#FFFFFF', .7), (.25, '#FFFFFF', .12), (.75, '#FFFFFF', 0), (1, '#FFFFFF', .35)], 0, 0, 1, 0)
    + lg('st', [(0, '#7E8A96'), (.35, '#F4F7FA'), (.7, '#B7C1CB'), (1, '#66727E')], 0, 0, 1, 0)
    + lg('sm', [(0, '#D08A45'), (1, '#A65A22')], 0, 0, 1, 0)
    + lg('hd', [(0, '#E8F6F9'), (1, '#A9CDD6')], 0, 0, 1, 1),
    shadow(124, 226, 66, 10)
    # glass handle
    + '<path d="M166 140c34-2 38 56 0 56" fill="none" stroke="url(#hd)" stroke-width="15" stroke-linecap="round"/>'
    + '<path d="M170 145c22 2 24 40 0 44" fill="none" stroke="#fff" stroke-opacity=".75" stroke-width="3.5" stroke-linecap="round"/>'
    # glass shell + tea
    + '<path d="M74 122l8 88q2 14 16 14h52q14 0 16-14l8-88z" fill="#E4F2F5"/>'
    + '<path d="M80 126l7 80q1 8 11 8h52q10 0 11-8l7-80z" fill="url(#tea)"/>'
    + '<path d="M80 126l2 26q42 10 84 0l2-26z" fill="url(#foam)"/>'
    + '<path d="M82 152q42 10 84 0" fill="none" stroke="#B46D2F" stroke-opacity=".35" stroke-width="2"/>'
    # froth crown above the rim
    + '<path d="M72 124q-2-14 16-16q4-12 20-9q10-9 24-2q14-6 22 4q18-1 20 15q0 8-8 10H80q-8-1-8-2z" fill="url(#foam)"/>'
    + '<g fill="#fff" opacity=".9"><circle cx="92" cy="112" r="5"/><circle cx="112" cy="104" r="4"/><circle cx="140" cy="106" r="3"/><circle cx="104" cy="118" r="2.5"/><circle cx="158" cy="114" r="3.5"/></g>'
    + '<g fill="#D9A769" opacity=".6"><circle cx="126" cy="116" r="2.5"/><circle cx="148" cy="120" r="2"/><circle cx="84" cy="120" r="2"/></g>'
    # glass sheen
    + '<path d="M74 122l8 88q2 14 16 14h52q14 0 16-14l8-88z" fill="url(#gl)"/>'
    + '<rect x="88" y="138" width="8" height="66" rx="4" fill="#fff" opacity=".55"/>'
    + '<path d="M86 218h76" stroke="#fff" stroke-opacity=".6" stroke-width="3" stroke-linecap="round"/>'
    # pulled tea stream
    + '<path d="M84 64c24 4 38 24 37 52h11c1-34-18-56-44-62z" fill="url(#sm)"/>'
    + '<path d="M93 64c15 5 26 20 28 40" fill="none" stroke="#F6CB94" stroke-width="3" stroke-linecap="round" opacity=".85"/>'
    + '<g fill="none" stroke="#CFC6BA" stroke-width="4" stroke-linecap="round" opacity=".75"><path d="M160 96c-6-8 4-12-2-20"/><path d="M172 100c-5-6 3-10-1-16"/></g>'
    # stainless mug tipping in
    + '<g transform="translate(62 56) rotate(112)">'
    '<path d="M19 -20c20 0 22 30 0 32" fill="none" stroke="#8C98A4" stroke-width="7" stroke-linecap="round"/>'
    '<path d="M-24 -28h48l-4 52q-20 10-40 0z" fill="url(#st)"/>'
    '<ellipse cx="0" cy="-28" rx="24" ry="7" fill="#DCE3EA"/>'
    '<ellipse cx="0" cy="-27" rx="19.5" ry="4.8" fill="#B06A2E"/>'
    '<path d="M-22.6 -8h45.2" stroke="#6F7B87" stroke-opacity=".35" stroke-width="2"/>'
    '</g>'
    + hl(80, 44, 5, 12, 20, .8)
)

# ---------------------------------------------------------------- Nasi Lemak
rice_grains = ''.join('<ellipse cx="%s" cy="%s" rx="4" ry="2" transform="rotate(%s %s %s)"/>' % (x, y, a, x, y) for x, y, a in [
    (96, 132, 20), (110, 118, -30), (126, 110, 10), (142, 116, 40), (104, 146, -10), (120, 134, 60),
    (138, 132, -20), (156, 130, 15), (90, 150, 45), (150, 146, -40), (128, 150, 5), (112, 160, 30), (164, 150, 70)])
ART['my-nasi-lemak'] = svg(
    SHADOW_DEF + BLUR
    + rg('pl', [(0, '#FFFFFF'), (.7, '#EEF1F5'), (1, '#C9D1DB')], .4, .3, .7)
    + lg('lf', [(0, '#7FD35B'), (.55, '#3FA343'), (1, '#1F6E33')], 0, 0, 1, 1)
    + rg('rc', [(0, '#FFFFFF'), (.65, '#F3F4F7'), (1, '#CDD3DD')], .35, .25, .8)
    + rg('sb', [(0, '#FF7A55'), (.5, '#E0381F'), (1, '#9C1C12')], .35, .3, .75)
    + rg('yk', [(0, '#FFE07A'), (.6, '#FFB323'), (1, '#E08410')], .35, .3, .7)
    + rg('cu', [(0, '#F4FFD8'), (.7, '#C8EDA0'), (1, '#9FD574')], .4, .35, .7)
    + lg('pn', [(0, '#F0C184'), (1, '#B87838')]),
    shadow(128, 222, 100, 14)
    + '<ellipse cx="128" cy="172" rx="108" ry="46" fill="#B8C2CE"/>'
    + '<ellipse cx="128" cy="166" rx="108" ry="46" fill="url(#pl)"/>'
    + '<ellipse cx="128" cy="166" rx="86" ry="34" fill="none" stroke="#DCE2EA" stroke-width="3"/>'
    # banana leaf
    + '<path d="M30 170c20-36 70-54 118-52c42 2 72 18 82 40c-22 22-66 36-112 34c-44-2-76-10-88-22z" fill="url(#lf)"/>'
    + '<path d="M40 170c56-18 124-22 180-10" fill="none" stroke="#B9EB8E" stroke-opacity=".8" stroke-width="3" stroke-linecap="round"/>'
    + '<g stroke="#2A7F37" stroke-opacity=".55" stroke-width="1.5" fill="none"><path d="M70 164l-14-18M100 159l-10-24M130 157l-4-26M160 157l4-24M190 158l10-18M86 166l-10 18M122 162l-6 24M160 162l2 22M196 164l8 14"/></g>'
    # rice dome
    + '<path d="M72 168c-6-44 22-72 58-72s64 28 56 72c-20 10-94 10-114 0z" fill="url(#rc)"/>'
    + '<g fill="#DCE1EA">' + rice_grains + '</g>'
    + hl(104, 116, 12, 22, 25, .8)
    # cucumber slices
    + '<g transform="rotate(-14 196 170)"><ellipse cx="196" cy="172" rx="21" ry="13" fill="#2F8A3C"/><ellipse cx="196" cy="170" rx="18" ry="10.5" fill="url(#cu)"/>'
    '<g fill="#E9F8D2"><ellipse cx="190" cy="170" rx="2.5" ry="1.5"/><ellipse cx="196" cy="166" rx="2.5" ry="1.5"/><ellipse cx="202" cy="170" rx="2.5" ry="1.5"/><ellipse cx="196" cy="174" rx="2.5" ry="1.5"/></g></g>'
    + '<g transform="rotate(10 214 150)"><ellipse cx="214" cy="152" rx="17" ry="11" fill="#2F8A3C"/><ellipse cx="214" cy="150" rx="14.5" ry="8.5" fill="url(#cu)"/></g>'
    # sambal
    + '<path d="M126 102c-12-2-20 10-14 18c-10 4-8 18 4 18c6 8 26 8 32 0c12 2 18-12 8-18c6-10-4-20-14-16c-4-6-12-6-16-2z" fill="url(#sb)"/>'
    + '<g fill="#fff" opacity=".75"><ellipse cx="124" cy="110" rx="6" ry="3" transform="rotate(-20 124 110)"/><circle cx="146" cy="116" r="2"/><circle cx="116" cy="126" r="1.6"/></g>'
    + '<g fill="#F7D2DA"><path d="M136 122c4-2 8 0 8 4c-3-1-6-2-8-4z"/><path d="M120 130c3-2 7-1 8 2c-3 0-6 0-8-2z"/></g>'
    # boiled egg
    + '<ellipse cx="74" cy="184" rx="30" ry="21" fill="#E9EDF3"/><ellipse cx="72" cy="180" rx="28" ry="19" fill="#FFFFFF"/>'
    + '<ellipse cx="74" cy="180" rx="14" ry="11" fill="url(#yk)"/>'
    + '<ellipse cx="70" cy="176" rx="5" ry="3" fill="#FFF6C8" opacity=".85"/>'
    # peanuts & anchovies
    + '<g fill="url(#pn)"><ellipse cx="124" cy="196" rx="7" ry="5"/><ellipse cx="136" cy="200" rx="7" ry="5"/><ellipse cx="146" cy="193" rx="6.5" ry="4.5"/><ellipse cx="130" cy="189" rx="6" ry="4.5"/><ellipse cx="116" cy="202" rx="6" ry="4.5"/></g>'
    + '<g fill="#C98A2E" stroke="#8C5716" stroke-width="1"><path d="M152 204c8-6 18-6 24-2c-8 4-16 5-24 2z"/><path d="M150 196c6-8 16-10 22-8c-6 6-14 9-22 8z"/><path d="M104 196c6-6 12-8 18-6c-6 5-12 7-18 6z"/></g>'
    + '<g fill="#fff" opacity=".6"><circle cx="122" cy="194" r="1.8"/><circle cx="134" cy="198" r="1.8"/><circle cx="144" cy="191" r="1.6"/></g>'
)

# ---------------------------------------------------------------- Durian
def durian():
    cx, cy, rx, ry = 124, 144, 74, 70
    light = (-0.62, -0.78)

    def shade(t):
        # t in 0..1 -> dark olive .. light lime
        dark, mid, lite = (0x4A, 0x66, 0x1C), (0x8F, 0xAE, 0x35), (0xE2, 0xEC, 0x8A)
        if t < .5:
            a, b, k = dark, mid, t / .5
        else:
            a, b, k = mid, lite, (t - .5) / .5
        return '#%02X%02X%02X' % tuple(int(a[i] + (b[i] - a[i]) * k) for i in range(3))

    def spike(bx, by, s, ox, oy, pos_light):
        ax, ay = bx + ox, by + oy
        corners = [(bx, by - s), (bx + s, by), (bx, by + s), (bx - s, by)]
        out = ''
        for i in range(4):
            p, q = corners[i], corners[(i + 1) % 4]
            mx, my = (p[0] + q[0]) / 2 - bx, (p[1] + q[1]) / 2 - by
            l = math.hypot(mx, my) or 1
            d = (mx / l) * light[0] + (my / l) * light[1]
            t = max(0, min(1, .5 + .42 * d + .28 * pos_light))
            out += '<path d="M%s %sL%s %sL%s %sz" fill="%s"/>' % (n(ax), n(ay), n(p[0]), n(p[1]), n(q[0]), n(q[1]), shade(t))
        return out

    back = ''
    for k in range(22):
        a = -math.pi / 2 + k * 2 * math.pi / 22 + .07
        bx, by = cx + rx * .93 * math.cos(a), cy + ry * .93 * math.sin(a)
        if by > cy + ry * .75:
            continue
        s = 11
        pl = -(math.cos(a) * light[0] + math.sin(a) * light[1]) * -1
        back += spike(bx, by, s, math.cos(a) * 17, math.sin(a) * 17, pl * .8)
    front = []
    step = 23
    for row, y in enumerate(range(int(cy - ry) + 16, int(cy + ry) - 4, 19)):
        off = (row % 2) * step / 2
        x = cx - rx - off
        while x < cx + rx:
            u, v = (x - cx) / rx, (y - cy) / ry
            r = math.hypot(u, v)
            if r < .86:
                s = 10.5 * (1 - .32 * r)
                pl = -(u * light[0] + v * light[1]) * -1 * 0 + (-(u + v) / 1.6)
                front.append((y, spike(x, y, s, u * s * 1.3, v * s * 1.3 - 2, pl)))
            x += step
    front.sort(key=lambda t: t[0])
    return back, ''.join(f for _, f in front)


_db, _df = durian()
ART['my-durian'] = svg(
    SHADOW_DEF + BLUR
    + rg('du', [(0, '#D5E27A'), (.5, '#94B23A'), (1, '#4E6A1E')], .38, .3, .78)
    + lg('ds', [(0, '#9B7445'), (1, '#5B3E1E')], 0, 0, 1, 0)
    + rg('pd', [(0, '#FFF3B0'), (.55, '#FFD54D'), (1, '#E7A51E')], .35, .3, .75),
    shadow(128, 224, 86, 12)
    + _db
    + '<ellipse cx="124" cy="144" rx="74" ry="70" fill="url(#du)"/>'
    + _df
    + hl(92, 102, 16, 26, 35, .35)
    # stem
    + '<path d="M118 80c-2-14 2-26 12-34l9 5c-7 7-9 17-7 29z" fill="url(#ds)"/>'
    + '<ellipse cx="125" cy="80" rx="12" ry="5" fill="#6B8A25"/>'
    + '<ellipse cx="134" cy="48" rx="6" ry="3.5" fill="#B99466" transform="rotate(30 134 48)"/>'
    # a fresh pod in front
    + '<path d="M162 210C154 192 166 176 182 178C188 166 206 166 214 174C230 172 242 188 234 204C226 220 172 226 162 210Z" fill="url(#pd)"/>'
    + '<path d="M184 180C190 192 188 206 180 216M214 175C216 188 214 204 206 218" fill="none" stroke="#D9921C" stroke-opacity=".55" stroke-width="2.2" stroke-linecap="round"/>'
    + '<path d="M172 188c2-6 8-9 14-8M194 176c6-4 14-4 18 0" fill="none" stroke="#fff" stroke-opacity=".85" stroke-width="3.5" stroke-linecap="round"/>'
)

# ---------------------------------------------------------------- Cendol
strands = ''.join('<path d="%s"/>' % d for d in [
    'M84 150q8-6 16 0t16 0', 'M120 158q8-6 16 0t16 0', 'M152 148q8-6 16 0', 'M96 170q8-6 16 0t16 0',
    'M136 176q8-6 16 0', 'M112 186q6-5 12 0t12 0', 'M76 164q6-5 12 0', 'M166 162q6-5 12 0'])
ART['my-cendol'] = svg(
    SHADOW_DEF + BLUR
    + lg('gl', [(0, '#FFFFFF', .75), (.3, '#FFFFFF', .12), (.8, '#FFFFFF', 0), (1, '#FFFFFF', .4)], 0, 0, 1, 0)
    + lg('mk', [(0, '#FFFBF1'), (1, '#EADCC0')])
    + rg('ic', [(0, '#FFFFFF'), (.7, '#EEF6FC'), (1, '#BFD6E8')], .35, .25, .8)
    + lg('gm', [(0, '#D98A3E'), (.5, '#9A4A17'), (1, '#5E280B')], 0, 0, 1, 1)
    + lg('ft', [(0, '#E6F3F7'), (1, '#AFCBD6')], 0, 0, 1, 0),
    shadow(128, 226, 64, 10)
    # foot
    + '<path d="M116 196h24l4 18h-32z" fill="url(#ft)"/>'
    + '<ellipse cx="128" cy="218" rx="40" ry="9" fill="#A9C6D1"/><ellipse cx="128" cy="215" rx="40" ry="9" fill="url(#ft)"/>'
    # bowl + coconut milk
    + '<path d="M58 118q2 76 70 82q68-6 70-82z" fill="#E6F2F6"/>'
    + '<path d="M64 124q4 66 64 72q60-6 64-72z" fill="url(#mk)"/>'
    + '<path d="M64 132q64 14 128 0" fill="none" stroke="#fff" stroke-width="3" opacity=".7"/>'
    + '<g fill="none" stroke="#4CB050" stroke-width="6" stroke-linecap="round">' + strands + '</g>'
    + '<g fill="none" stroke="#B9F09A" stroke-width="1.6" stroke-linecap="round" opacity=".9" transform="translate(-1 -2)">' + strands + '</g>'
    + '<g fill="#7B1E2B"><ellipse cx="104" cy="182" rx="4" ry="3"/><ellipse cx="150" cy="186" rx="4" ry="3"/><ellipse cx="170" cy="150" rx="4" ry="3"/></g>'
    # bowl sheen
    + '<path d="M58 118q2 76 70 82q68-6 70-82z" fill="url(#gl)"/>'
    + '<path d="M72 136q4 30 20 46" fill="none" stroke="#fff" stroke-width="6" stroke-linecap="round" opacity=".6"/>'
    # shaved ice mountain
    + '<path d="M60 120c-6-18 10-30 22-28c0-26 22-42 46-42s46 16 46 42c14-2 28 10 22 28c-40 10-96 10-136 0z" fill="url(#ic)"/>'
    + '<g fill="#fff" opacity=".9"><circle cx="96" cy="76" r="3"/><circle cx="110" cy="98" r="2"/><circle cx="148" cy="84" r="2.5"/><circle cx="80" cy="104" r="2"/><circle cx="168" cy="106" r="2"/></g>'
    # gula melaka drizzle
    + '<path d="M98 66c14-14 44-16 60 0c6 6 4 14-2 16c-4 10 2 22-4 24c-6 2-6-10-8-18c-8 2-12 10-18 8c-4-2 0-8-4-10c-6 2-8 16-14 14c-6-2 0-14-4-18c-8-2-10-10-6-16z" fill="url(#gm)"/>'
    + '<path d="M108 66c10-8 26-10 38-4" fill="none" stroke="#FFD29A" stroke-width="3.5" stroke-linecap="round" opacity=".9"/>' + '<g fill="#FFD29A" opacity=".8"><ellipse cx="146" cy="92" rx="1.6" ry="4"/><ellipse cx="102" cy="90" rx="1.6" ry="3.5"/></g>'
    # red beans on top
    + '<g><ellipse cx="120" cy="56" rx="7" ry="5.5" fill="#8E2233"/><ellipse cx="136" cy="58" rx="7" ry="5.5" fill="#7A1C2B"/><ellipse cx="128" cy="48" rx="7" ry="5.5" fill="#A12A3C"/>'
    '<g fill="#fff" opacity=".7"><circle cx="118" cy="54" r="1.6"/><circle cx="134" cy="56" r="1.6"/><circle cx="126" cy="46" r="1.6"/></g></g>'
    + hl(84, 84, 7, 14, 25, .7)
)

# ---------------------------------------------------------------- Satay
def satay():
    out = ''
    chunk_shapes = [
        [1, .92, 1.05, .95, 1.02, .9, 1.04, .96],
        [.95, 1.04, .92, 1, .97, 1.05, .93, 1],
        [1.03, .94, 1, 1.06, .92, 1, .96, 1.04],
    ]
    px0, py0 = 50, 216
    for si, ang in enumerate((-78, -57, -36)):
        a = math.radians(ang)
        ux, uy = math.cos(a), math.sin(a)
        x0, y0 = px0 + si * 6, py0 - si * 2
        x1, y1 = x0 + ux * 196, y0 + uy * 196
        out += '<path d="M%s %sL%s %s" stroke="#9C7038" stroke-width="7" stroke-linecap="round"/>' % (n(x0), n(y0), n(x1), n(y1))
        out += '<path d="M%s %sL%s %s" stroke="url(#bb)" stroke-width="4.5" stroke-linecap="round"/>' % (n(x0), n(y0), n(x1), n(y1))
        for ci in range(4):
            d = 90 + ci * 22
            cx_, cy_ = x0 + ux * d, y0 + uy * d
            shp = chunk_shapes[(ci + si) % 3]
            pts = []
            for k in range(8):
                t = k * math.pi / 4
                ra = 12.5 * shp[k] * abs(math.cos(t)) + 15 * shp[k] * abs(math.sin(t))
                lx, ly = math.cos(t) * ra, math.sin(t) * ra
                pts.append((cx_ + lx * ux - ly * uy, cy_ + lx * uy + ly * ux))
            p = 'M%s %s' % (n((pts[0][0] + pts[1][0]) / 2), n((pts[0][1] + pts[1][1]) / 2))
            for k in range(8):
                q = pts[(k + 1) % 8]
                r_ = pts[(k + 2) % 8]
                p += 'Q%s %s %s %s' % (n(q[0]), n(q[1]), n((q[0] + r_[0]) / 2), n((q[1] + r_[1]) / 2))
            out += '<path d="%sz" fill="url(#mt)" stroke="#6E2C0B" stroke-opacity=".35" stroke-width="1.2"/>' % p
            px, py = -uy, ux
            for off, ln, w, op in ((-4, 16, 3, .5), (5, 12, 2.4, .4)):
                sx, sy = cx_ + ux * off + px * ln / 2, cy_ + uy * off + py * ln / 2
                out += '<path d="M%s %sl%s %s" stroke="#4E1F06" stroke-opacity="%s" stroke-width="%s" stroke-linecap="round"/>' % (
                    n(sx), n(sy), n(-px * ln), n(-py * ln), op, w)
            hx, hy = cx_ - px * 7 - ux * 2, cy_ - py * 7 - uy * 2
            out += '<ellipse cx="%s" cy="%s" rx="4.5" ry="2.4" transform="rotate(%s %s %s)" fill="#FFE2B8" opacity=".8"/>' % (
                n(hx), n(hy), n(ang), n(hx), n(hy))
    return out


ART['my-satay'] = svg(
    SHADOW_DEF + BLUR
    + lg('bb', [(0, '#F6DDA6'), (1, '#D9AE68')], 0, 0, 1, 1)
    + rg('mt', [(0, '#F7B062'), (.55, '#C4621F'), (1, '#7A300C')], .35, .3, .75)
    + lg('bw', [(0, '#F2F5F8'), (.6, '#C9D3DD'), (1, '#8E9CAB')], 0, 0, 1, 0)
    + rg('ps', [(0, '#E9A45B'), (.6, '#BF6F2A'), (1, '#8A4516')], .4, .35, .75),
    shadow(128, 224, 96, 12)
    + satay()
    # peanut sauce bowl
    + '<ellipse cx="188" cy="202" rx="44" ry="14" fill="#7C8B9A"/>'
    + '<path d="M144 186q2 32 44 34q42-2 44-34z" fill="url(#bw)"/>'
    + '<ellipse cx="188" cy="186" rx="44" ry="13" fill="#E9EEF3"/>'
    + '<ellipse cx="188" cy="187" rx="38" ry="10" fill="url(#ps)"/>'
    + '<g fill="#D7372A" opacity=".85"><ellipse cx="176" cy="186" rx="6" ry="2.4"/><ellipse cx="198" cy="189" rx="4" ry="1.8"/></g>'
    + '<g fill="#F7D19B"><circle cx="188" cy="184" r="2"/><circle cx="204" cy="184" r="1.6"/><circle cx="170" cy="190" r="1.6"/></g>'
    + '<path d="M154 196q6 14 22 18" fill="none" stroke="#fff" stroke-width="4" stroke-linecap="round" opacity=".7"/>'
)

# ---------------------------------------------------------------- Petronas Twin Towers
def tower(cx):
    tiers = [(214, 24), (160, 22), (126, 19), (100, 16), (80, 12.5), (66, 9), (56, 6), (48, 3.5)]
    left = []
    for i, (y, hw) in enumerate(tiers):
        ny = tiers[i + 1][0] if i + 1 < len(tiers) else 40
        left.append((cx - hw, y))
        left.append((cx - hw * .96, ny + 3))
    right = [(2 * cx - x, y) for x, y in reversed(left)]
    pts = left + [(cx - 2, 41), (cx, 37), (cx + 2, 41)] + right
    s = '<path d="M%sz" fill="url(#tw)"/>' % 'L'.join('%s %s' % (n(x), n(y)) for x, y in pts)
    s += '<g stroke="#5E6F8C" stroke-opacity=".28" stroke-width="1.2">'
    for off, top in ((-15, 163), (-8, 103), (0, 69), (8, 103), (15, 163)):
        s += '<path d="M%s 212V%s"/>' % (n(cx + off), top)
    s += '</g><g fill="#F8FBFF" opacity=".95">'
    for y, hw in tiers[1:-1]:
        s += '<rect x="%s" y="%s" width="%s" height="3" rx="1.5"/>' % (n(cx - hw - 2.5), n(y), n(2 * hw + 5))
    s += '</g><g fill="#FFD36B">'
    for i, y in enumerate((196, 182, 170, 146, 136, 112, 90)):
        s += '<rect x="%s" y="%s" width="5" height="3" rx="1"/>' % (n(cx - 11 + (i * 7) % 18), y)
    s += '</g>'
    s += '<path d="M%s 40V8" stroke="#E6EDF7" stroke-width="2.6" stroke-linecap="round"/>' % n(cx)
    s += '<circle cx="%s" cy="24" r="2.6" fill="#fff"/>' % n(cx)
    return s


ART['my-petronas'] = svg(
    SHADOW_DEF + BLUR
    + rg('sun', [(0, '#FFE8A3'), (.55, '#FFB56E'), (1, '#FF7F86')], .45, .35, .7)
    + lg('tw', [(0, '#FFFFFF'), (.4, '#C9D5E6'), (1, '#667899')], 0, 0, 1, 0)
    + lg('bs', [(0, '#E6ECF4'), (1, '#8C9BB3')]),
    '<circle cx="128" cy="118" r="86" fill="url(#sun)"/>'
    + '<circle cx="128" cy="118" r="86" fill="none" stroke="#fff" stroke-opacity=".4" stroke-width="3"/>'
    + '<g fill="#fff" opacity=".75"><ellipse cx="62" cy="100" rx="20" ry="7"/><ellipse cx="198" cy="78" rx="15" ry="5.5"/></g>'
    + shadow(128, 224, 90, 11)
    + tower(96) + tower(160)
    # skybridge with its inverted-V support
    + '<path d="M117 148L128 130L139 148" fill="none" stroke="#B5C2D4" stroke-width="3.2" stroke-linejoin="round"/>'
    + '<rect x="114" y="120" width="28" height="9" rx="2" fill="#EEF3F9"/><path d="M114 129h28" stroke="#667899" stroke-width="2"/>'
    + '<rect x="118" y="123" width="20" height="2.5" rx="1" fill="#FFD36B"/>'
    # podium
    + '<rect x="54" y="206" width="148" height="18" rx="8" fill="url(#bs)"/>'
    + '<rect x="60" y="208" width="136" height="4" rx="2" fill="#fff" opacity=".8"/>'
    + hl(84, 128, 3.5, 44, 0, .6) + hl(148, 128, 3.5, 44, 0, .55)
)

# ---------------------------------------------------------------- Wau Bulan
W_WING = 'M128 60C150 50 200 46 238 64C222 76 206 94 196 114C178 126 152 130 128 130C104 130 78 126 60 114C50 94 34 76 18 64C56 46 106 50 128 60Z'
W_MOON = 'M128 164C170 164 214 144 234 100C242 162 194 210 128 210C62 210 14 162 22 100C42 144 86 164 128 164Z'
W_HEAD = 'M128 20C144 30 148 48 142 64H114C108 48 112 30 128 20Z'
ART['my-wau-bulan'] = svg(
    SHADOW_DEF + BLUR
    + lg('wr', [(0, '#FF7058'), (.5, '#E8352B'), (1, '#A61B25')], 0, 0, .5, 1)
    + lg('wy', [(0, '#FFF0A8'), (.5, '#FFC93D'), (1, '#E59A12')], 0, 0, 0, 1)
    + lg('wt', [(0, '#52DACA'), (1, '#0F8583')], 0, 0, 0, 1),
    shadow(128, 236, 58, 7)
    + '<path d="M128 208c-8 10 8 16 0 26" fill="none" stroke="#8A5A2B" stroke-width="2" stroke-linecap="round" opacity=".6"/>'
    # bow (busur)
    + '<path d="M76 42Q128 -2 180 42" fill="none" stroke="#7A4A20" stroke-width="4" stroke-linecap="round"/>'
    + '<path d="M76 42c-8 8-10 20-6 30M180 42c8 8 10 20 6 30" fill="none" stroke="#1FA7A0" stroke-width="3.5" stroke-linecap="round"/>'
    # gold-rimmed pieces
    + '<g fill="url(#wy)" stroke="url(#wy)" stroke-width="9" stroke-linejoin="round">'
    '<path d="%s"/><path d="%s"/><path d="%s"/><path d="M118 126H138L136 168H120Z"/></g>' % (W_WING, W_MOON, W_HEAD)
    + '<g fill="url(#wr)"><path d="%s"/><path d="%s"/><path d="%s"/><path d="M118 126H138L136 168H120Z"/></g>' % (W_WING, W_MOON, W_HEAD)
    # teal bands
    + '<g fill="url(#wt)">'
    '<path d="M128 72C150 64 184 62 212 70C200 80 190 94 184 106C168 114 148 118 128 118C108 118 88 114 72 106C66 94 56 80 44 70C72 62 106 64 128 72Z"/>'
    '<path d="M128 175C164 175 202 158 222 126C216 172 178 200 128 200C78 200 40 172 34 126C54 158 92 175 128 175Z"/>'
    '<path d="M128 32C136 38 138 48 135 58H121C118 48 120 38 128 32Z"/></g>'
    # red cores
    + '<g fill="url(#wr)">'
    '<path d="M128 82C144 76 166 76 182 80C176 88 170 96 166 104C154 108 142 110 128 110C114 110 102 108 90 104C86 96 80 88 74 80C90 76 112 76 128 82Z"/>'
    '<path d="M128 183C156 183 184 174 202 158C190 180 162 193 128 193C94 193 66 180 54 158C72 174 100 183 128 183Z"/></g>'
    # gold floral motifs
    + '<g fill="none" stroke="#FFE27A" stroke-width="2.4" stroke-linecap="round">'
    '<path d="M96 96c2-8 14-8 14 0c0 5-7 6-8 1"/><path d="M160 96c-2-8-14-8-14 0c0 5 7 6 8 1"/>'
    '<path d="M60 164c4-6 14-4 12 2c-1 4-6 3-6 0"/><path d="M196 164c-4-6-14-4-12 2c1 4 6 3 6 0"/></g>'
    + '<g fill="#FFE27A"><circle cx="128" cy="94" r="6"/><circle cx="128" cy="146" r="5"/>'
    '<circle cx="128" cy="84" r="3.2"/><circle cx="128" cy="104" r="3.2"/><circle cx="118" cy="94" r="3.2"/><circle cx="138" cy="94" r="3.2"/>'
    '<circle cx="128" cy="188" r="3.4"/></g>'
    + '<g fill="#A61B25"><circle cx="128" cy="94" r="2.4"/><circle cx="128" cy="146" r="2"/></g>'
    # tassels
    + '<g fill="#1FA7A0"><path d="M14 62l-6 18l14-8z"/><path d="M242 62l6 18l-14-8z"/><path d="M20 96l-8 16l14-4z"/><path d="M236 96l8 16l-14-4z"/></g>'
    + '<path d="M128 22v182" stroke="#7A4A20" stroke-width="1.6" stroke-opacity=".35"/>'
    + hl(70, 72, 5, 22, 62, .7) + hl(44, 150, 4, 18, 30, .5)
)

# ---------------------------------------------------------------- Bunga Raya
petal = 'M0 0C-34-8-58-46-46-78c10-22 30-22 40-12c8-12 30-14 40 4c14 30-6 72-34 86z'
petals = ''.join('<g transform="rotate(%s)"><path d="%s" fill="url(#pt)"/>'
                 '<path d="M0-6c-4-20-8-44-6-66M0-6c6-18 12-42 20-60M0-6c-12-16-22-36-28-56" fill="none" stroke="#FFB0A8" stroke-opacity=".45" stroke-width="1.6" stroke-linecap="round"/></g>'
                 % (a, petal) for a in (-8, 64, 136, 208, 280))
ART['my-bunga-raya'] = svg(
    SHADOW_DEF + BLUR
    + rg('pt', [(0, '#7C0718'), (.35, '#D11A2E'), (.8, '#F4404A'), (1, '#FF7066')], 0, 0, 90, ' gradientUnits="userSpaceOnUse" fx="0" fy="0"'.replace('cx="0"', ''))
    + lg('lv', [(0, '#86DB5A'), (.55, '#3FA548'), (1, '#1E6B34')], 0, 0, 1, 1)
    + lg('sm', [(0, '#FFB9A8'), (1, '#E23A3A')], 0, 1, 1, 0),
    shadow(128, 226, 78, 11)
    # leaves
    + '<path d="M120 176c-24 10-60 18-92 6c14-26 50-44 82-34z" fill="url(#lv)"/>'
    + '<path d="M36 180c26-4 54-12 76-26" fill="none" stroke="#C4F29E" stroke-width="2.4" stroke-linecap="round" opacity=".8"/>'
    + '<path d="M140 176c24 14 58 26 90 16c-10-28-46-48-80-40z" fill="url(#lv)"/>'
    + '<path d="M222 190c-26-4-52-16-72-30" fill="none" stroke="#C4F29E" stroke-width="2.4" stroke-linecap="round" opacity=".8"/>'
    + '<g transform="translate(128 124)">' + petals
    + '<circle r="12" fill="#6A0514"/><circle r="6" fill="#4A020C"/></g>'
    # staminal column
    + '<path d="M130 122c12-12 24-30 30-50" fill="none" stroke="url(#sm)" stroke-width="6" stroke-linecap="round"/>'
    + '<g fill="#FFD23F"><circle cx="146" cy="100" r="3"/><circle cx="152" cy="92" r="3"/><circle cx="141" cy="94" r="2.6"/><circle cx="156" cy="84" r="2.6"/><circle cx="149" cy="84" r="2.6"/><circle cx="157" cy="96" r="2.4"/></g>'
    + '<g fill="#C8102E"><circle cx="158" cy="66" r="3.4"/><circle cx="166" cy="70" r="3.4"/><circle cx="163" cy="62" r="3.4"/><circle cx="154" cy="62" r="3"/><circle cx="168" cy="63" r="3"/></g>'
    + hl(86, 88, 10, 24, 40, .45)
)

# ---------------------------------------------------------------- Rhinoceros Hornbill
ART['my-hornbill'] = svg(
    SHADOW_DEF + BLUR
    + rg('bk', [(0, '#636C84'), (.45, '#272B37'), (1, '#0E1016')], .38, .28, .75)
    + lg('bil', [(0, '#F07A2A'), (.45, '#FFC93D'), (1, '#FFE8A0')], 0, 0, 1, .6)
    + lg('cq', [(0, '#FFC04A'), (.5, '#FF6A2B'), (1, '#D93A1E')], 0, 0, 1, 0)
    + lg('br', [(0, '#A87A4A'), (1, '#5E3D1E')], 0, 0, 0, 1)
    + lg('wt', [(0, '#FFFFFF'), (1, '#D5DCE6')], 0, 0, 1, 0),
    shadow(128, 230, 84, 10)
    # tail: white with a black band, hanging below the branch
    + '<path d="M86 148L62 214Q76 226 94 220L112 156Z" fill="url(#wt)"/>'
    + '<path d="M73.5 184L68.4 198L97.8 198L101.6 184Z" fill="#1B1D25"/>'
    # branch
    + '<path d="M8 176C80 166 170 162 248 152L250 164C172 176 82 180 10 188Z" fill="url(#br)"/>'
    + '<path d="M28 178C92 170 170 166 236 158" stroke="#D2A776" stroke-width="2" stroke-linecap="round" opacity=".7"/>'
    + '<path d="M214 156c8-18 24-22 34-16c-8 14-22 18-34 16z" fill="#3FA548"/><path d="M226 150c10-4 18-2 22-10" fill="none" stroke="#9BE27A" stroke-width="2" stroke-linecap="round"/>'
    + '<path d="M30 186c-10 10-8 22 0 26c4-10 4-18 0-26z" fill="#2E8A3E"/>'
    # body
    + '<path d="M150 84C120 72 80 90 76 128C72 156 94 174 124 172C152 170 170 146 166 114Z" fill="url(#bk)"/>'
    + '<path d="M96 104C116 94 144 98 154 118C160 134 152 154 134 162C112 166 92 154 88 136C86 122 88 112 96 104Z" fill="#161920"/>'
    + '<g fill="none" stroke="#4A5368" stroke-width="2.6" stroke-linecap="round"><path d="M100 112C116 104 138 106 148 120"/><path d="M98 132Q116 140 138 136"/><path d="M104 148Q118 154 134 150"/></g>'
    + '<path d="M112 164C124 172 144 170 154 160C142 162 126 164 112 164Z" fill="url(#wt)"/>'
    + '<g fill="#3B3F4B"><rect x="120" y="164" width="7" height="14" rx="3"/><rect x="138" y="162" width="7" height="14" rx="3"/></g>'
    # head
    + '<circle cx="156" cy="78" r="32" fill="url(#bk)"/>'
    # bill + casque
    + '<path d="M174 64C214 66 238 98 246 138C228 114 206 106 176 106Z" fill="url(#bil)" stroke="#C9771E" stroke-width="1.6" stroke-linejoin="round"/>'
    + '<path d="M176 106C206 106 228 114 246 138C224 124 202 116 178 116Z" fill="#D98A26"/>'
    + '<path d="M176 70C182 46 212 34 238 44C246 48 246 58 238 58C228 56 216 58 208 64C218 70 226 80 230 90C216 78 198 70 176 70Z" fill="url(#cq)"/>'
    + '<path d="M186 56C198 46 216 42 232 46" fill="none" stroke="#FFE08A" stroke-width="3" stroke-linecap="round" opacity=".9"/>'
    # eye
    + '<circle cx="164" cy="72" r="8" fill="#FF5A3A"/><circle cx="164" cy="72" r="4.2" fill="#120A08"/><circle cx="162" cy="70" r="2" fill="#fff"/>'
    + '<path d="M153 63q11-7 22 0" fill="none" stroke="#0A0B10" stroke-width="2.6" stroke-linecap="round"/>'
    + hl(140, 62, 5, 11, 35, .5) + hl(92, 106, 5, 16, 40, .3)
)

# ---------------------------------------------------------------- Kampung house
posts = ''.join('<rect x="%s" y="168" width="8" height="48" rx="2" fill="url(#ps)"/>' % x for x in (62, 96, 150, 186))
slats = ''.join('<rect x="%s" y="152" width="4" height="14" rx="1" fill="#F7D9A8"/>' % x for x in range(72, 118, 9)) + \
    ''.join('<rect x="%s" y="152" width="4" height="14" rx="1" fill="#F7D9A8"/>' % x for x in range(144, 190, 9))
ART['my-kampung'] = svg(
    SHADOW_DEF + BLUR
    + lg('wd', [(0, '#E7AA66'), (.6, '#C27A3C'), (1, '#8E5022')], 0, 0, 1, 0)
    + lg('rf', [(0, '#E86A45'), (.55, '#C2432A'), (1, '#86261A')], 0, 0, 1, 1)
    + lg('ps', [(0, '#8E5A2E'), (1, '#5A3417')], 0, 0, 1, 0)
    + lg('gr', [(0, '#8FDB62'), (1, '#3E9D45')])
    + lg('tk', [(0, '#B9895A'), (1, '#7A5230')], 0, 0, 1, 0)
    + lg('pm', [(0, '#7ED957'), (1, '#2B8A3E')], 0, 0, 1, 1)
    + lg('wn', [(0, '#3CC2A8'), (1, '#1B7F74')], 0, 0, 1, 0),
    # palm tree (behind)
    '<path d="M204 214c-2-50 4-100 18-136l7 2c-12 36-16 84-14 134z" fill="url(#tk)"/>'
    + '<g fill="url(#pm)"><path d="M225 78c-18-18-44-20-62-8c20-2 40 4 56 16z"/><path d="M225 78c4-24 22-38 40-36c-14 8-26 22-32 40z"/>'
    '<path d="M225 78c20-4 34 6 38 22c-10-10-22-14-36-14z"/><path d="M225 78c-8 18-22 30-38 34c10-12 22-24 30-38z"/><path d="M225 78c-14-18-16-38-6-52c0 16 4 32 12 48z"/></g>'
    + '<g fill="#8A5A2B"><circle cx="221" cy="84" r="5"/><circle cx="229" cy="86" r="5"/></g>'
    # ground
    + '<ellipse cx="128" cy="222" rx="112" ry="16" fill="url(#gr)"/>'
    + '<ellipse cx="128" cy="218" rx="80" ry="7" fill="#2E7A38" opacity=".35"/>'
    # stilts
    + posts
    # stairs
    + '<path d="M112 168l-10 48h8l10-48zM144 168l10 48h-8l-10-48z" fill="#7A4A22"/>'
    + '<g fill="#D79B5E"><rect x="106" y="182" width="44" height="4" rx="2"/><rect x="104" y="196" width="48" height="4" rx="2"/><rect x="102" y="208" width="52" height="4" rx="2"/></g>'
    # floor beam
    + '<rect x="50" y="162" width="156" height="10" rx="3" fill="#7A4A22"/>'
    # walls
    + '<path d="M60 100h136v64H60z" fill="url(#wd)"/>'
    + '<g stroke="#8E5022" stroke-opacity=".35" stroke-width="1.5">' + ''.join('<path d="M%s 102v60"/>' % x for x in range(70, 196, 10)) + '</g>'
    # windows & door
    + '<rect x="72" y="112" width="26" height="32" rx="3" fill="#4A2A12"/><rect x="158" y="112" width="26" height="32" rx="3" fill="#4A2A12"/>'
    + '<path d="M72 112h-10v32h10zM98 112h10v32H98zM158 112h-10v32h10zM184 112h10v32h-10z" fill="url(#wn)"/>'
    + '<g fill="#FFD36B" opacity=".9"><rect x="76" y="116" width="18" height="24" rx="2"/><rect x="162" y="116" width="18" height="24" rx="2"/></g>'
    + '<path d="M85 116v24M76 128h18M171 116v24M162 128h18" stroke="#8E5022" stroke-width="2"/>'
    + '<rect x="114" y="116" width="28" height="48" rx="3" fill="#6B3A16"/><rect x="118" y="120" width="20" height="44" rx="2" fill="url(#wn)"/>'
    + '<circle cx="134" cy="144" r="2" fill="#FFD36B"/>'
    # veranda rail
    + '<rect x="64" y="148" width="58" height="4" rx="2" fill="#F7D9A8"/><rect x="136" y="148" width="58" height="4" rx="2" fill="#F7D9A8"/>' + slats
    # roof
    + '<path d="M128 26L30 106q-2 6 6 6h184q8 0 6-6z" fill="url(#rf)"/>'
    + '<path d="M128 44l-62 54h124z" fill="#F6C98C"/>'
    + '<path d="M128 52l-46 40h92z" fill="url(#wd)"/>'
    + '<g fill="#8E5022" opacity=".55"><circle cx="128" cy="76" r="6"/><path d="M104 88h48v3h-48z"/></g>'
    + '<path d="M128 26l-18-16M128 26l18-16" stroke="#86261A" stroke-width="5" stroke-linecap="round"/>'
    + '<path d="M30 106l98-80 98 80" fill="none" stroke="#FFB28E" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" opacity=".7"/>'
    + hl(74, 78, 5, 26, 52, .45)
)

# ---------------------------------------------------------------- Ketupat
def weave(cx, cy, half, cell, gid_a, gid_b):
    k = int(half * 2 / cell)
    out = '<g transform="rotate(45 %s %s)">' % (cx, cy)
    for i in range(k):
        for j in range(k):
            x = cx - half + i * cell
            y = cy - half + j * cell
            out += '<rect x="%s" y="%s" width="%s" height="%s" rx="2" fill="url(#%s)"/>' % (
                n(x + .8), n(y + .8), n(cell - 1.6), n(cell - 1.6), gid_a if (i + j) % 2 else gid_b)
    return out + '</g>'


ART['my-ketupat'] = svg(
    SHADOW_DEF + BLUR
    + lg('ka', [(0, '#C9EE7A'), (.5, '#8FCB3E'), (1, '#5E9E27')], 0, 0, 1, 0)
    + lg('kb', [(0, '#A9DE5A'), (.5, '#6DB33A'), (1, '#3F8424')], 0, 0, 0, 1)
    + lg('ya', [(0, '#FFF0A6'), (.5, '#F5CF55'), (1, '#D69E2A')], 0, 0, 1, 0)
    + lg('yb', [(0, '#FBE282'), (.5, '#E9B940'), (1, '#BC8420')], 0, 0, 0, 1)
    + rg('ov', [(0, '#FFFFFF', .35), (.5, '#FFFFFF', 0), (1, '#0C3310', .45)], .3, .25, .9)
    + lg('rb', [(0, '#9BDB55'), (1, '#3F8E2B')], 0, 0, 1, 1)
    + '<clipPath id="c1"><path d="M128 64l76 76-76 76-76-76z"/></clipPath>'
    + '<clipPath id="c2"><path d="M196 130l40 40-40 40-40-40z"/></clipPath>',
    shadow(140, 222, 96, 12)
    # small yellow ketupat behind
    + '<path d="M196 170c6-16 18-24 34-22" fill="none" stroke="#C48A22" stroke-width="5" stroke-linecap="round"/>'
    + '<path d="M196 170l42 42-42 42-42-42z" fill="#B07A1A" transform="translate(0 -44)"/>'
    + '<g clip-path="url(#c2)">' + weave(196, 170, 28, 9.4, 'ya', 'yb') + '<path d="M196 172l40 40-40 40-40-40z" fill="url(#ov)" transform="translate(0 -42)"/></g>'
    # tails of the big one
    + '<path d="M128 66c-6-22-22-36-46-40c14 10 24 22 30 42z" fill="url(#rb)"/>'
    + '<path d="M130 66c4-24 18-40 40-46c-10 12-18 28-22 46z" fill="url(#rb)"/>'
    + '<path d="M86 30c14 8 22 20 26 34" fill="none" stroke="#D9F7A8" stroke-width="2" stroke-linecap="round" opacity=".8"/>'
    # big green ketupat
    + '<path d="M128 62l80 78-80 78-80-78z" fill="#3D7A1F"/>'
    + '<g clip-path="url(#c1)">' + weave(128, 140, 54, 13.5, 'ka', 'kb') + '<path d="M128 64l76 76-76 76-76-76z" fill="url(#ov)"/></g>'
    + '<path d="M128 64l-76 76" stroke="#E4FFB8" stroke-width="3" stroke-linecap="round" opacity=".7"/>'
    + hl(100, 112, 6, 20, 45, .5)
)

# ---------------------------------------------------------------- Shizhong panda mascot
ART['my-panda-mascot'] = svg(
    SHADOW_DEF + BLUR
    + rg('fw', [(0, '#FFFFFF'), (.7, '#F4F6F9'), (1, '#CDD5E0')], .38, .3, .75)
    + rg('fk', [(0, '#4A4F5E'), (.5, '#1E2029'), (1, '#0C0D12')], .35, .3, .75)
    + rg('ht', [(0, '#FF8A7A'), (.5, '#EE3B34'), (1, '#B81F24')], .35, .3, .75)
    + lg('sc', [(0, '#FFE066'), (.6, '#FFC61A'), (1, '#E89E0C')], 0, 0, 0, 1),
    shadow(128, 228, 72, 11)
    # body
    + '<ellipse cx="128" cy="186" rx="60" ry="42" fill="url(#fw)"/>'
    + '<ellipse cx="90" cy="214" rx="20" ry="13" fill="url(#fk)"/><ellipse cx="166" cy="214" rx="20" ry="13" fill="url(#fk)"/>'
    + '<g fill="#F4B6B6" opacity=".9"><ellipse cx="90" cy="214" rx="6" ry="4"/><ellipse cx="166" cy="214" rx="6" ry="4"/></g>'
    # ears
    + '<circle cx="72" cy="56" r="24" fill="url(#fk)"/><circle cx="184" cy="56" r="24" fill="url(#fk)"/>'
    + '<circle cx="74" cy="58" r="11" fill="#3A3E4B"/><circle cx="182" cy="58" r="11" fill="#3A3E4B"/>'
    # scarf
    + '<path d="M78 160q50 20 100 0l4 16q-54 22-108 0z" fill="url(#sc)"/>'
    + '<path d="M160 168l18 30l-16-2l-8 10l-6-32z" fill="#F5B20F"/>'
    # head
    + '<ellipse cx="128" cy="108" rx="72" ry="64" fill="url(#fw)"/>'
    + '<path d="M86 104c-6-16 8-30 22-26c10 4 10 22 0 34c-10 6-18 4-22-8z" fill="url(#fk)"/>'
    + '<path d="M170 104c6-16-8-30-22-26c-10 4-10 22 0 34c10 6 18 4 22-8z" fill="url(#fk)"/>'
    # wink (left) + open eye (right)
    + '<path d="M92 100q8-8 16 0" fill="none" stroke="#fff" stroke-width="4" stroke-linecap="round"/>'
    + '<circle cx="154" cy="98" r="8" fill="#fff"/><circle cx="155" cy="99" r="5" fill="#111"/><circle cx="157" cy="96" r="2" fill="#fff"/>'
    # nose & mouth
    + '<path d="M120 122q8-5 16 0q-2 8-8 9q-6-1-8-9z" fill="#1E2029"/>'
    + '<path d="M118 136q5 6 10 0q5 6 10 0" fill="none" stroke="#1E2029" stroke-width="2.6" stroke-linecap="round"/>'
    # blush
    + '<g fill="#FF6F6F" opacity=".75"><ellipse cx="82" cy="130" rx="11" ry="7"/><ellipse cx="174" cy="130" rx="11" ry="7"/></g>'
    # arms hugging a heart
    + '<path d="M128 214c-26-14-36-28-34-40c2-12 18-16 34-2c16-14 32-10 34 2c2 12-8 26-34 40z" fill="url(#ht)"/>'
    + '<path d="M108 176c4-4 10-4 14 0" fill="none" stroke="#fff" stroke-width="3.5" stroke-linecap="round" opacity=".85"/>'
    + '<path d="M72 170c10 20 24 30 38 32c6-6 4-14-4-18c-12-4-22-14-28-24z" fill="url(#fk)"/>'
    + '<path d="M184 170c-10 20-24 30-38 32c-6-6-4-14 4-18c12-4 22-14 28-24z" fill="url(#fk)"/>'
    # brand spark (from the logo)
    + '<g stroke="#E8352B" stroke-width="6" stroke-linecap="round"><path d="M210 40l8-14"/><path d="M220 58l16-6"/><path d="M200 30l-2-14"/></g>'
    + hl(92, 66, 8, 20, 50, .8)
)


# Per-piece fit (scale, tx, ty) so every drawing fills ~232px of the 256 frame, matching the
# visual weight of the Fluent 3D emoji it sits next to. Measured from a transparent Chrome render
# of the unfitted drawing (alpha > 24); re-measure if a drawing's extent changes.
FIT = {
    'my-teh-tarik': (1.132, -3.8, -19.7),  # measured bbox 32,28-201,233
    'my-nasi-lemak': (1.074, -9.5, -46.5),  # measured bbox 20,93-236,232
    'my-durian': (1.166, -32.3, -32.3),  # measured bbox 38,43-237,232
    'my-cendol': (1.215, -27.5, -39.0),  # measured bbox 58,42-198,233
    'my-satay': (1.094, -24.1, -9.9),  # measured bbox 46,20-232,232
    'my-petronas': (1.031, -4.0, 5.8),  # measured bbox 40,6-216,231
    'my-wau-bulan': (0.967, 4.3, 4.3),  # measured bbox 8,15-248,241
    'my-bunga-raya': (1.105, -14.5, -13.4),  # measured bbox 28,23-230,233
    'my-hornbill': (0.959, 4.3, -4.8),  # measured bbox 8,40-250,237
    'my-kampung': (0.932, -2.9, 13.8),  # true extent 16,7-265,238 (palm frond overflows the frame)
    'my-ketupat': (1.105, -30.0, -10.1),  # measured bbox 48,20-238,230
    'my-panda-mascot': (1.045, -22.0, -1.6),  # measured bbox 48,13-239,235
}


def main():
    os.makedirs(OUT, exist_ok=True)
    for k, v in ART.items():
        if k in FIT:
            sc, tx, ty = FIT[k]
            v = v.replace('</defs>', '</defs><g transform="matrix(%s 0 0 %s %s %s)">' % (sc, sc, tx, ty), 1)
            v = v[:-len('</svg>')] + '</g></svg>'
        with open(os.path.join(OUT, k + '.svg'), 'w', encoding='utf-8', newline='\n') as f:
            f.write(v + '\n')
        print('%-20s %6d bytes' % (k, len(v.encode('utf-8'))))


if __name__ == '__main__':
    main()
