import { defineAsyncComponent } from 'vue';

// 订单管理 — also holds the commerce strings shared by catalog / aftersales / merchants / shop / marketing (cm.*)
// and the console texts of every commerce API error (err.<code>).
export default {
  menu: 'orders',
  order: 30,
  icon: 'Tickets',
  title: { zh: '订单管理', en: 'Orders' },
  routes: [
    { path: '/orders', component: () => import('./OrderList.vue'), meta: { title: { zh: '订单列表', en: 'Orders' }, perm: 'orders.view' }, menu: true },
    { path: '/orders/:id', component: () => import('./OrderDetail.vue'), meta: { title: { zh: '订单详情', en: 'Order' }, perm: 'orders.view' } },
    {
      path: '/orders-settings',
      component: () => import('./OrderSettings.vue'),
      meta: { title: { zh: '下单与流转规则', en: 'Checkout rules' }, perm: 'system.config' },
      menu: true,
    },
  ],
  userTabs: [{ key: 'orders', title: { zh: '订单', en: 'Orders' }, perm: 'orders.view', component: defineAsyncComponent(() => import('./UserOrders.vue')) }],
  messages: {
    zh: {
      cm: {
        orders: '订单列表', shopOrders: '我的订单', orderQ: '订单号 / 内容 / 用户 / 手机 / 商家', orderNo: '订单号', content: '内容', category: '分类',
        flowLabel: '流程', merchant: '商家', payable: '实付', free: '免费', paidLabel: '付款', paid: '已付款', unpaid: '未付款', scheduled: '预约时间',
        withTickets: '有售后', hideDemo: '隐藏样例订单', demo: '样例', ticket: '售后', gmvLine: '共 {n} 单 · 成交额 {gmv}',
        subtotal: '小计', fee: '配送 / 服务费', discount: '优惠', refunded: '已退款', summary: '订单信息', commission: '抽成', payMethod: '支付方式',
        coupon: '优惠券', cancelFee: '取消违约金', autoConfirmAt: '预计自动确认', cancelReason: '取消原因', settlement: '结算单', adminNote: '备注',
        formData: '需求信息', items: '商品明细', price: '单价', qty: '数量', lineTotal: '小计', timeline: '时间线', aftersales: '售后工单', review: '评价',
        ledger: '资金流水', cancelHint: '取消后会通知用户。', cancelRefundHint: '取消后 {amount} 将原路退回用户的适中钱包，并通知用户。',
        cancelNote: '取消说明（会记录在时间线；商家取消必填）', refundAmount: '退款金额（最多 {max}）', full: '全额', refundedMsg: '已退款 {amount}',
        orderSettings: '下单与流转规则', orderSettingsSub: '费用表、支付方式、可预约时间、商家自动确认、取消与评价规则。修改后 App 立即生效。',
        status: { pending: '待确认', confirmed: '待服务', serving: '进行中', done: '已完成', cancelled: '已取消' },
        flow: { service: '预约服务', goods: '商品', topup: '话费充值', enquiry: '咨询', job: '求职投递', request: '发布需求' },
        pay: { wallet: '适中钱包', tng: 'TNG eWallet', duitnow: 'DuitNow', fpx: 'FPX', card: '银行卡', none: '无需付款' },
        act: { confirm: '确认订单', serve: '开始服务 / 配送', complete: '标记完成', cancel: '取消订单', refund: '退款', note: '添加备注', confirmAsk: '确定要{action}吗？' },
        ev: { refund: '退款', payment: '支付', note: '备注' },
        actor: { user: '用户', merchant: '商家', admin: '后台', system: '系统' },
        cancelReasons: { plans: '计划有变', mistake: '信息填错了', better: '找到更合适的', slow: '商家响应太慢', else: '其他原因', merchant: '商家取消', platform: '平台取消' },
        ticketStatus: { received: '待处理', processing: '处理中', resolved: '已处理', rejected: '已驳回' },
        asReason: { reschedule: '修改服务时间', refund: '取消或退款', quality: '服务质量问题', missing: '商品缺漏或损坏', misc: '其他问题' },
        reviewTag: { onTime: '准时守约', professional: '专业细致', value: '物有所值', friendly: '沟通友善', tidy: '干净整洁', again: '还会再约' },
        field: {
          date: '日期', time: '时间', slot: '送达时段', address: '地址', city: '城市', phone: '电话', number: '充值号码', candidate: '求职者', experience: '经验',
          people: '人数', language: '语言', from: '出发 / 取件', to: '到达 / 送达', flight: '航班', project: '需求', intent: '意向', salary: '期望薪资',
          budget: '预算', operator: '运营商', faceValue: '面额', serviceFee: '服务费', note: '备注',
        },
        noMerchant: '当前账号没有绑定店铺，请在「商家管理」为店铺创建后台账号后用该账号登录。',
      },
      err: {
        'address.addressRequired': '请填写详细地址', 'address.badPhone': '电话格式不正确', 'address.badPostcode': '请输入 5 位马来西亚邮编', 'address.nameRequired': '请填写联系人',
        'address.notFound': '地址不存在', 'address.tooMany': '地址数量已达上限',
        'aftersales.badReason': '售后原因不正确', 'aftersales.badStatus': '工单状态不正确', 'aftersales.exists': '该订单已有处理中的售后', 'aftersales.notFound': '工单不存在或不在你的数据范围内',
        'aftersales.textRequired': '请填写问题描述', 'cart.full': '购物车已满', 'cart.notGoods': '只有商品可以加入购物车',
        'catalog.badAction': '不支持的批量操作', 'catalog.badCategory': '分类不存在', 'catalog.badCategoryId': '分类编码只能是 2–24 位小写字母（且不能是 all）',
        'catalog.badColor': '颜色格式应为 #RRGGBB', 'catalog.badIcon': '图标名称只能是小写字母', 'catalog.badPrice': '价格不正确', 'catalog.badRating': '评分应在 0–5 之间',
        'catalog.badServiceId': '服务编码只能包含小写字母、数字和 -', 'catalog.badStock': '库存不正确', 'catalog.badType': '类型不正确',
        'catalog.categoryExists': '分类编码已存在', 'catalog.categoryInUse': '分类下还有服务，不能删除', 'catalog.categoryLocked': '内置分类不能删除（可以停用）',
        'catalog.categoryNotFound': '分类不存在', 'catalog.csvEmpty': 'CSV 文件没有数据', 'catalog.csvHeader': 'CSV 表头不正确（请先导出一份作为模板）', 'catalog.csvNumber': '数字格式不正确：{detail}',
        'catalog.imageInvalid': '图片地址不正确', 'catalog.nameRequired': '请填写名称', 'catalog.noSelection': '请先选择服务', 'catalog.notFound': '服务不存在或不在你的店铺',
        'catalog.reviewNotFound': '评价不存在', 'catalog.serviceExists': '服务编码已存在', 'catalog.tooLarge': '详情内容太长',
        'coupons.badAmount': '面额不正确', 'coupons.badCode': '编码只能是 2–32 位小写字母、数字或 -', 'coupons.badDays': '有效天数不正确', 'coupons.badMin': '使用门槛不正确',
        'coupons.badTarget': '发放对象不正确', 'coupons.cannotRevoke': '只能收回未使用的券', 'coupons.codeExists': '编码已存在', 'coupons.nameRequired': '请填写名称',
        'coupons.noUsers': '没有找到符合条件的用户', 'coupons.notFound': '优惠券模板不存在或已停用',
        'marketing.badAction': '跳转类型不正确', 'marketing.badDates': '结束时间要晚于开始时间', 'marketing.badUrl': '外部链接必须以 https:// 开头', 'marketing.bannerNotFound': 'Banner 不存在',
        'marketing.imageRequired': '请上传图片', 'marketing.titleRequired': '请填写标题',
        'merchants.accountNotFound': '账号不存在', 'merchants.agentCannotCreate': '你的代理账号不能开商家', 'merchants.applicationClosed': '申请已处理',
        'merchants.applicationNotFound': '申请不存在或不在你的数据范围内', 'merchants.applyClosed': '已关闭入驻申请', 'merchants.badAutoConfirm': '自动确认设置不正确',
        'merchants.badCategory': '分类不存在', 'merchants.badPhone': '电话格式不正确', 'merchants.badRate': '抽成比例应在 0–1 之间', 'merchants.fieldsRequired': '请填写完整',
        'merchants.nameRequired': '请填写商家名称', 'merchants.notFound': '商家不存在或不在你的数据范围内', 'merchants.replyRequired': '请填写回复', 'merchants.settlementNotFound': '结算单不存在',
        'merchants.settlementPaid': '结算单已标记打款', 'merchants.tooManyApplications': '申请太多',
        'orders.addressInvalid': '地址不存在', 'orders.addressRequired': '缺少地址', 'orders.alreadyReviewed': '已评价', 'orders.badBudget': '预算不正确', 'orders.badCategory': '分类不存在',
        'orders.badPhone': '电话格式不正确', 'orders.badQuantity': '数量不正确', 'orders.badSlot': '配送时段不正确', 'orders.badStars': '星级不正确', 'orders.badTime': '预约时间不在可选范围',
        'orders.badTransition': '订单当前状态不能进行这个操作', 'orders.cancelTooLate': '已过可取消时间', 'orders.cannotCancel': '当前状态不能取消', 'orders.cannotComplete': '当前状态不能完成',
        'orders.cannotReview': '不能评价', 'orders.couponCategory': '优惠券不适用', 'orders.couponInvalid': '优惠券不可用', 'orders.couponMin': '未达到优惠券门槛',
        'orders.fieldRequired': '缺少必填信息', 'orders.mixedItems': '只有商品可以合并结算', 'orders.mixedShops': '不同店铺需分开结算', 'orders.noItems': '没有商品',
        'orders.notFound': '订单不存在或不在你的数据范围内', 'orders.notPaid': '该订单没有付款，无法退款', 'orders.notPayable': '无需付款', 'orders.noteRequired': '请填写说明',
        'orders.outOfStock': '库存不足', 'orders.pastDate': '日期已过', 'orders.payMethodDisabled': '支付方式未开放', 'orders.payUnavailable': '支付方式暂不可用',
        'orders.priceChanged': '价格已变化', 'orders.reasonRequired': '请选择原因', 'orders.refundReason': '请填写退款原因', 'orders.refundTooMuch': '超过可退金额（最多 RM {max}）',
        'orders.reviewTooLong': '评价太长', 'orders.scheduleRequired': '缺少预约时间', 'orders.serviceUnavailable': '服务已下架', 'orders.tooFar': '预约时间太远', 'orders.tooManyItems': '商品太多',
        'orders.tooSoon': '预约时间太近', 'orders.tryAgain': '请重试', 'shop.noMerchant': '当前账号没有绑定店铺',
      },
    },
    en: {
      cm: {
        orders: 'Orders', shopOrders: 'My orders', orderQ: 'Order no. / item / member / phone / shop', orderNo: 'Order no.', content: 'Item', category: 'Category',
        flowLabel: 'Flow', merchant: 'Shop', payable: 'Paid', free: 'Free', paidLabel: 'Payment', paid: 'Paid', unpaid: 'Unpaid', scheduled: 'Scheduled',
        withTickets: 'With after-sales', hideDemo: 'Hide sample orders', demo: 'Sample', ticket: 'After-sales', gmvLine: '{n} orders · GMV {gmv}',
        subtotal: 'Subtotal', fee: 'Delivery / service fee', discount: 'Discount', refunded: 'Refunded', summary: 'Order', commission: 'commission', payMethod: 'Payment',
        coupon: 'Coupon', cancelFee: 'Cancellation fee', autoConfirmAt: 'Auto-confirms at', cancelReason: 'Cancel reason', settlement: 'Settlement', adminNote: 'Note',
        formData: 'Request details', items: 'Items', price: 'Price', qty: 'Qty', lineTotal: 'Total', timeline: 'Timeline', aftersales: 'After-sales', review: 'Review',
        ledger: 'Money movements', cancelHint: 'The member will be notified.', cancelRefundHint: '{amount} goes back to the member’s Shizhong wallet and they are notified.',
        cancelNote: 'Note (shown in the timeline; required for shops)', refundAmount: 'Amount (max {max})', full: 'Full', refundedMsg: 'Refunded {amount}',
        orderSettings: 'Checkout rules', orderSettingsSub: 'Fees, payment methods, bookable times, merchant auto-confirmation, cancellation and review rules. Changes apply to the app at once.',
        status: { pending: 'Pending', confirmed: 'Confirmed', serving: 'In progress', done: 'Completed', cancelled: 'Cancelled' },
        flow: { service: 'Booking', goods: 'Goods', topup: 'Top-up', enquiry: 'Enquiry', job: 'Job application', request: 'Request' },
        pay: { wallet: 'Shizhong wallet', tng: 'TNG eWallet', duitnow: 'DuitNow', fpx: 'FPX', card: 'Card', none: 'No payment' },
        act: { confirm: 'Confirm', serve: 'Start service / delivery', complete: 'Mark completed', cancel: 'Cancel order', refund: 'Refund', note: 'Add note', confirmAsk: '{action}?' },
        ev: { refund: 'Refund', payment: 'Payment', note: 'Note' },
        actor: { user: 'Member', merchant: 'Shop', admin: 'Console', system: 'System' },
        cancelReasons: { plans: 'Plans changed', mistake: 'Wrong details', better: 'Found a better option', slow: 'Shop too slow', else: 'Other', merchant: 'Cancelled by shop', platform: 'Cancelled by Shizhong' },
        ticketStatus: { received: 'New', processing: 'In progress', resolved: 'Resolved', rejected: 'Rejected' },
        asReason: { reschedule: 'Reschedule', refund: 'Cancel / refund', quality: 'Quality issue', missing: 'Missing or damaged', misc: 'Other' },
        reviewTag: { onTime: 'On time', professional: 'Professional', value: 'Good value', friendly: 'Friendly', tidy: 'Clean & tidy', again: 'Would book again' },
        field: {
          date: 'Date', time: 'Time', slot: 'Delivery slot', address: 'Address', city: 'City', phone: 'Phone', number: 'Top-up number', candidate: 'Candidate', experience: 'Experience',
          people: 'People', language: 'Language', from: 'From / pick-up', to: 'To / drop-off', flight: 'Flight', project: 'Request', intent: 'Intent', salary: 'Expected salary',
          budget: 'Budget', operator: 'Operator', faceValue: 'Face value', serviceFee: 'Service fee', note: 'Note',
        },
        noMerchant: 'This account is not linked to a shop. Create a console login for the shop under Merchants and sign in with it.',
      },
      err: {
        'address.addressRequired': 'Enter the address', 'address.badPhone': 'Invalid phone', 'address.badPostcode': 'Enter a 5-digit Malaysian postcode', 'address.nameRequired': 'Enter a name',
        'address.notFound': 'Address not found', 'address.tooMany': 'Too many addresses',
        'aftersales.badReason': 'Invalid reason', 'aftersales.badStatus': 'Invalid status', 'aftersales.exists': 'An after-sales request is already open', 'aftersales.notFound': 'Ticket not found or outside your scope',
        'aftersales.textRequired': 'Describe the problem', 'cart.full': 'Cart is full', 'cart.notGoods': 'Only goods can go in the cart',
        'catalog.badAction': 'Unsupported action', 'catalog.badCategory': 'Unknown category', 'catalog.badCategoryId': 'Category code: 2–24 lower-case letters (not "all")',
        'catalog.badColor': 'Colours look like #RRGGBB', 'catalog.badIcon': 'Icon names are lower-case letters', 'catalog.badPrice': 'Invalid price', 'catalog.badRating': 'Rating must be 0–5',
        'catalog.badServiceId': 'Service code: lower-case letters, digits and -', 'catalog.badStock': 'Invalid stock', 'catalog.badType': 'Invalid type',
        'catalog.categoryExists': 'Category code exists', 'catalog.categoryInUse': 'The category still has listings', 'catalog.categoryLocked': 'Built-in categories can only be disabled',
        'catalog.categoryNotFound': 'Category not found', 'catalog.csvEmpty': 'The CSV has no rows', 'catalog.csvHeader': 'Unexpected CSV header (export one as a template)', 'catalog.csvNumber': 'Invalid number: {detail}',
        'catalog.imageInvalid': 'Invalid image', 'catalog.nameRequired': 'Enter a name', 'catalog.noSelection': 'Select listings first', 'catalog.notFound': 'Listing not found or not in your shop',
        'catalog.reviewNotFound': 'Review not found', 'catalog.serviceExists': 'Service code exists', 'catalog.tooLarge': 'Details are too long',
        'coupons.badAmount': 'Invalid amount', 'coupons.badCode': 'Code: 2–32 lower-case letters, digits or -', 'coupons.badDays': 'Invalid validity', 'coupons.badMin': 'Invalid minimum spend',
        'coupons.badTarget': 'Invalid target', 'coupons.cannotRevoke': 'Only unused coupons can be revoked', 'coupons.codeExists': 'Code exists', 'coupons.nameRequired': 'Enter a name',
        'coupons.noUsers': 'No matching members', 'coupons.notFound': 'Template not found or disabled',
        'marketing.badAction': 'Invalid link type', 'marketing.badDates': 'End must be after start', 'marketing.badUrl': 'External links must start with https://', 'marketing.bannerNotFound': 'Banner not found',
        'marketing.imageRequired': 'Upload an image', 'marketing.titleRequired': 'Enter a title',
        'merchants.accountNotFound': 'Login not found', 'merchants.agentCannotCreate': 'Your agent can’t open merchants', 'merchants.applicationClosed': 'Already handled',
        'merchants.applicationNotFound': 'Application not found or outside your scope', 'merchants.applyClosed': 'Applications closed', 'merchants.badAutoConfirm': 'Invalid auto-confirm setting',
        'merchants.badCategory': 'Unknown category', 'merchants.badPhone': 'Invalid phone', 'merchants.badRate': 'Commission must be 0–1', 'merchants.fieldsRequired': 'Fill in all fields',
        'merchants.nameRequired': 'Enter a shop name', 'merchants.notFound': 'Shop not found or outside your scope', 'merchants.replyRequired': 'Enter a reply', 'merchants.settlementNotFound': 'Settlement not found',
        'merchants.settlementPaid': 'Already marked paid', 'merchants.tooManyApplications': 'Too many applications',
        'orders.addressInvalid': 'Address not found', 'orders.addressRequired': 'Address missing', 'orders.alreadyReviewed': 'Already reviewed', 'orders.badBudget': 'Invalid budget', 'orders.badCategory': 'Unknown category',
        'orders.badPhone': 'Invalid phone', 'orders.badQuantity': 'Invalid quantity', 'orders.badSlot': 'Invalid slot', 'orders.badStars': 'Invalid stars', 'orders.badTime': 'Time not bookable',
        'orders.badTransition': 'Not possible in the order’s current status', 'orders.cancelTooLate': 'Too late to cancel', 'orders.cannotCancel': 'Can’t cancel now', 'orders.cannotComplete': 'Can’t complete now',
        'orders.cannotReview': 'Can’t review', 'orders.couponCategory': 'Coupon not valid here', 'orders.couponInvalid': 'Coupon unavailable', 'orders.couponMin': 'Coupon minimum not met',
        'orders.fieldRequired': 'Required details missing', 'orders.mixedItems': 'Only goods can be combined', 'orders.mixedShops': 'Different shops are paid separately', 'orders.noItems': 'No items',
        'orders.notFound': 'Order not found or outside your scope', 'orders.notPaid': 'The order was not paid; nothing to refund', 'orders.notPayable': 'No payment needed', 'orders.noteRequired': 'Enter a note',
        'orders.outOfStock': 'Out of stock', 'orders.pastDate': 'Date in the past', 'orders.payMethodDisabled': 'Payment method disabled', 'orders.payUnavailable': 'Payment method unavailable',
        'orders.priceChanged': 'Price changed', 'orders.reasonRequired': 'Choose a reason', 'orders.refundReason': 'Enter a refund reason', 'orders.refundTooMuch': 'More than refundable (max RM {max})',
        'orders.reviewTooLong': 'Review too long', 'orders.scheduleRequired': 'Schedule missing', 'orders.serviceUnavailable': 'Listing unavailable', 'orders.tooFar': 'Too far ahead', 'orders.tooManyItems': 'Too many items',
        'orders.tooSoon': 'Too soon', 'orders.tryAgain': 'Please try again', 'shop.noMerchant': 'This account is not linked to a shop',
      },
    },
  },
};
