import UserFinance from './UserFinance.vue';

const T = (zh, en) => ({ zh, en });

export default {
  menu: 'finance',
  order: 50,
  icon: 'Money',
  title: T('财务', 'Finance'),
  routes: [
    { path: '/finance/transactions', component: () => import('./Transactions.vue'), meta: { title: T('资金流水', 'Ledger'), perm: 'finance.view' }, menu: true },
    { path: '/finance/deposits', component: () => import('./Deposits.vue'), meta: { title: T('加密货币充值', 'Crypto deposits'), perm: 'finance.view' }, menu: true },
    { path: '/finance/topups', component: () => import('./Topups.vue'), meta: { title: T('线下充值入账', 'Offline top-ups'), perm: 'finance.view' }, menu: true },
    { path: '/finance/withdrawals', component: () => import('./Withdrawals.vue'), meta: { title: T('提现审核', 'Withdrawals'), perm: 'finance.view' }, menu: true },
    { path: '/finance/addresses', component: () => import('./Addresses.vue'), meta: { title: T('收款地址与余额', 'Deposit addresses'), perm: 'finance.view' }, menu: true },
    { path: '/finance/income', component: () => import('./Income.vue'), meta: { title: T('收益概览', 'Earnings'), perm: 'finance.view' }, menu: true },
    { path: '/finance/commissions', component: () => import('./Commissions.vue'), meta: { title: T('代理佣金', 'Agent commission'), perm: 'finance.view' }, menu: true },
    { path: '/finance/reconciliation', component: () => import('./Reconciliation.vue'), meta: { title: T('对账报表', 'Reconciliation'), perm: 'finance.view' }, menu: true },
    { path: '/finance/crypto', component: () => import('./CryptoSettings.vue'), meta: { title: T('加密货币设置', 'Crypto settings'), perm: 'finance.deposits' }, menu: true },
    { path: '/finance/settings', component: () => import('./Settings.vue'), meta: { title: T('充值与提现设置', 'Top-up & withdrawal rules'), perm: 'finance.settings' }, menu: true },
  ],
  userTabs: [{ key: 'finance', title: T('充值与提现', 'Top-ups & withdrawals'), perm: 'finance.view', component: UserFinance }],
  messages: {
    zh: {
      fin: {
        q: '昵称 / 手机 / 用户ID', currency: '账户', kind: '类型', direction: '方向', in: '收入', out: '支出', sumIn: '收入合计', sumOut: '支出合计',
        rm: '余额 RM', bean: '金豆', income: '收益 RM', balanceAfter: '变动后', title: '说明', method: '方式', ref: '关联', note: '备注',
        kinds: {
          recharge: '充值（人工/线下）', crypto: '加密货币充值', withdraw: '提现', order: '订单', refund: '退款', grant: '注册赠送', adjust: '调账',
          checkin: '签到（已停用）', task: '任务', gift: '礼物', 'live-gift': '直播礼物', exchange: '兑换', envelope: '红包', transfer: '转账', call: '通话', income: '收益',
        },
        network: '网络', asset: '币种', amount: '数量', tx: '交易哈希', status: '状态', confirmations: '确认数', credit: '入账', rate: '汇率', fee: '手续费',
        simulated: '模拟', manual: '补单', onlySimulated: '只看模拟', onlyReal: '只看真实', attention: '待处理（低于最低/未识别/人工）',
        dep: { detected: '已检测', confirming: '确认中', credited: '已入账', belowMinimum: '低于最低额', unknown: '未识别', review: '人工审核', closed: '已关闭' },
        reason: {
          unknownToken: '未识别的代币', assetDisabled: '币种已停用', belowMinimum: '低于最低充值额', rateUnavailable: '暂无汇率', tooLarge: '超过自动入账上限',
          tooSmall: '金额太小', manual: '手动补单',
        },
        sumCredited: '入账合计', detail: '充值详情', from: '转出地址', to: '收款地址', contract: '合约', block: '区块', rawAmount: '原始数量', decimals: '精度',
        marketRate: '市场价', rateSource: '汇率来源', reviewer: '处理人', detectedAt: '检测时间', creditedAt: '入账时间', ledger: '钱包流水', commission: '代理佣金',
        recheck: '重新查询', recheckDone: '已刷新：{status}（{n}/{m}）', creditBtn: '入账', creditTitle: '手动入账', creditRm: '入账金额 RM（留空按当前汇率）',
        closeBtn: '关闭', closeTitle: '关闭（不入账）', reasonLabel: '原因（会记入操作日志）', manualBtn: '手动补单', manualTitle: '手动补单（链上交易未被检测到时）',
        user: '用户（ID / 手机 / 用户ID）', userId: '用户内部 ID', simulate: '模拟充值（测试）', simulateTitle: '模拟一笔加密货币充值',
        simulateHint: '仅用于测试：不会查询区块链，记录会标记为「模拟」。确认数每几秒增加一次，达到后自动入账。', instant: '立即达到确认数',
        simulateDone: '已创建模拟充值 #{id}（{status}）', credited: '已入账 {money}',
        wd: { pending: '待审核', paid: '已打款', rejected: '已驳回', cancelled: '用户撤回' },
        source: '来源', sourceWallet: '余额', sourceIncome: '收益', net: '实付', account: '收款账户', payRef: '打款凭证', approve: '通过并标记已打款',
        reject: '驳回', approveTitle: '确认已线下打款', referenceLabel: '打款凭证号 / 交易哈希', rejectTitle: '驳回提现（金额退回用户）', sumAmount: '申请合计',
        sumNet: '实付合计', memberBalance: '余额 {b} · 收益 {i}',
        tp: { pending: '待审核', credited: '已入账', rejected: '已驳回', cancelled: '用户撤回' }, receipt: '凭证', reference: '转账参考号',
        approveTopup: '核对无误，入账', approveTopupTitle: '线下充值入账', creditAmount: '入账金额 RM', rejectTopupTitle: '驳回线下充值',
        commissionOff: '代理佣金目前是关闭的（在下方规则中开启）。开启后，名下用户每笔加密货币/线下充值入账时按比例记录佣金。',
        commissionOn: '代理佣金已开启：默认比例 {rate}，代理单独设置的比例优先。', unpaid: '未结算', paid: '已结算', void: '作废', markPaid: '标记已结算',
        payTitle: '标记 {n} 笔佣金已结算', agent: '代理', base: '充值金额', ratio: '比例', byAgent: '按代理汇总', selectFirst: '请先勾选未结算的佣金',
        held: '当前资金存量', balance: '用户余额', frozen: '提现冻结', beans: '金豆', incomeHeld: '可提现收益', incomePending: '待结算收益',
        byKind: '按类型汇总', daily: '按日明细', day: '日期', count: '笔数', earned: '累计收益', withdrawn: '已提现', inReview: '提现审核中',
        chain: '链', index: '序号', path: '推导路径', received: '已入账', chainBalance: '链上余额（最近读取）', lastViewed: '最近打开充值页', readBalance: '读取链上余额',
        balanceRead: '已读取', explorer: '浏览器', addressQ: '用户 / 地址', summary: '汇总', creditedAll: '已入账（真实）', heldOnChain: '地址上的余额（最近读取）',
        sweepHint: '归集：用持有助记词的钱包，把这些地址上的币转到你的总钱包；地址按「推导路径」依次排列。',
        crypto: {
          status: '运行状态', enabled: '加密货币充值', on: '已开启', off: '已关闭', rates: '汇率', mode: '模式', market: '市场价', fixed: '固定',
          used: '入账汇率', lastError: '最近错误', refresh: '刷新汇率', networks: '网络', provider: '接口', key: '公钥', watched: '监听地址', open: '确认中',
          lastRun: '最近查询', tip: '最新区块', scan: '立即查询区块链', scanDone: '查询完成', keys: '收款钱包扩展公钥', keysWarn:
            '只填写扩展公钥（xpub / zpub）。绝对不要在这里填写助记词或私钥——系统会拒绝。在你自己的电脑上断网运行离线工具 server/tools/XpubTool 从助记词生成扩展公钥，并对照钱包 App 里的前几个地址。',
          current: '当前', notSet: '未设置', keyId: '公钥 ID', depth: '层级', depthWarn: '层级不是 3，请确认导出的是账户级扩展公钥（{path}）', first: '前 3 个地址',
          replace: '更换扩展公钥', preview: '预览地址', save: '保存', clear: '清除', saved: '已保存。新用户地址将从这个公钥推导；旧地址继续监听 {days} 天。',
          changeWarn: '更换公钥后，用户会拿到新的收款地址。旧地址上的资金仍在旧钱包里，请自行归集。确定更换吗？', assets: '币种与网络',
          minDeposit: '最低充值', feePct: '手续费 %', sort: '排序', priceId: '行情 ID', stable: '稳定币', available: '可用', addAsset: '新增币种',
          coin: '币种代码', saveRow: '保存', rules: '检测与汇率规则', apis: '区块链接口', needKey: '未填写 Etherscan API Key（下方「区块链接口」）',
        },
        settingsSub: '充值档位与限额、充值方式开关、线下转账说明、提现规则。',
        tab: { addresses: '收款地址', deposits: '加密货币充值', withdrawals: '提现', topups: '线下充值', accounts: '收款账户', claims: '奖励领取' },
      },
      err: {
        'crypto.xpubMissing': '请填写扩展公钥', 'crypto.mnemonicRejected': '不能填写助记词，请只填写扩展公钥（xpub / zpub）', 'crypto.xpubInvalid': '扩展公钥格式不正确',
        'crypto.privateKeyRejected': '这是私钥，不能填写，请只填写扩展公钥', 'crypto.xpubWrongType': '比特币请填写 zpub 或 xpub', 'crypto.notConfigured': '尚未配置扩展公钥',
        'crypto.disabled': '加密货币充值已关闭', 'crypto.unavailableOnPlatform': '该平台不支持', 'crypto.assetUnavailable': '币种不存在或未启用',
        'crypto.depositNotFound': '充值记录不存在或不在你的数据范围内', 'crypto.amountInvalid': '金额不正确', 'crypto.notOpen': '这笔充值不在确认中',
        'crypto.providerMissing': '该网络没有接口', 'crypto.providerFailed': '区块链接口请求失败，请稍后再试', 'crypto.alreadyCredited': '这笔充值已入账',
        'crypto.creditFailed': '入账失败（可能没有汇率或金额无效），请填写入账金额', 'crypto.txInvalid': '交易哈希格式不正确', 'crypto.txExists': '这笔交易已有记录', 'crypto.chainInvalid': '不支持的链',
        'crypto.networkInvalid': '不支持的网络', 'crypto.coinInvalid': '币种代码只能是 2–12 位大写字母或数字', 'crypto.codeInvalid': '编码应为「币种-网络」，例如 USDT-TRC20',
        'crypto.contractInvalid': '合约地址格式不正确', 'crypto.decimalsInvalid': '精度应为 0–30', 'crypto.addressNotFound': '地址不存在',
        'topup.notPending': '这笔申请已处理', 'topup.notFound': '申请不存在或不在你的数据范围内', 'topup.disabled': '线下充值已关闭', 'topup.amountRange': '金额超出范围',
        'topup.proofRequired': '缺少转账凭证', 'topup.receiptInvalid': '凭证无效', 'topup.tooManyPending': '待审核的申请太多',
        'withdraw.notFound': '提现不存在或不在你的数据范围内', 'withdraw.notPending': '这笔提现已处理', 'withdraw.referenceRequired': '请填写打款凭证号或交易哈希',
        'withdraw.disabled': '提现已关闭', 'withdraw.demoLocked': '体验账号不能提现', 'withdraw.sourceDisabled': '该来源不能提现', 'withdraw.belowMin': '低于最低提现金额',
        'withdraw.accountRequired': '缺少收款账户', 'withdraw.dailyCount': '超过每日次数', 'withdraw.dailyAmount': '超过每日额度', 'withdraw.tooManyAccounts': '收款账户太多',
        'withdraw.kindInvalid': '收款方式不正确', 'withdraw.providerRequired': '缺少银行/钱包/网络', 'withdraw.nameRequired': '缺少收款人', 'withdraw.bankNoInvalid': '银行账号不正确',
        'withdraw.phoneInvalid': '手机号不正确', 'withdraw.networkInvalid': '网络不正确', 'withdraw.addressInvalid': '地址不正确',
        'finance.reasonRequired': '请填写原因', 'finance.nothingSelected': '请先选择记录', 'finance.commissionNotOpen': '这笔佣金已处理',
        'tasks.unknown': '任务不存在', 'tasks.notDone': '任务未完成',
        'member.disabled': '会员已关闭', 'member.already': '已领取',
      },
    },
    en: {
      fin: {
        q: 'Name / phone / member ID', currency: 'Account', kind: 'Type', direction: 'Direction', in: 'In', out: 'Out', sumIn: 'Total in', sumOut: 'Total out',
        rm: 'Balance RM', bean: 'Beans', income: 'Earnings RM', balanceAfter: 'After', title: 'Description', method: 'Method', ref: 'Reference', note: 'Note',
        kinds: {
          recharge: 'Top-up (manual/offline)', crypto: 'Crypto top-up', withdraw: 'Withdrawal', order: 'Order', refund: 'Refund', grant: 'Sign-up grant', adjust: 'Adjustment',
          checkin: 'Check-in (discontinued)', task: 'Task', gift: 'Gift', 'live-gift': 'Live gift', exchange: 'Exchange', envelope: 'Red packet', transfer: 'Transfer', call: 'Call', income: 'Earnings',
        },
        network: 'Network', asset: 'Asset', amount: 'Amount', tx: 'Tx hash', status: 'Status', confirmations: 'Confirmations', credit: 'Credited', rate: 'Rate', fee: 'Fee',
        simulated: 'Simulated', manual: 'Manual', onlySimulated: 'Simulated only', onlyReal: 'Real only', attention: 'Needs attention',
        dep: { detected: 'Detected', confirming: 'Confirming', credited: 'Credited', belowMinimum: 'Below minimum', unknown: 'Unrecognised', review: 'Manual review', closed: 'Closed' },
        reason: {
          unknownToken: 'Unknown token', assetDisabled: 'Asset disabled', belowMinimum: 'Below minimum', rateUnavailable: 'No rate', tooLarge: 'Above auto-credit limit',
          tooSmall: 'Too small', manual: 'Manual entry',
        },
        sumCredited: 'Total credited', detail: 'Deposit', from: 'From', to: 'To', contract: 'Contract', block: 'Block', rawAmount: 'Raw amount', decimals: 'Decimals',
        marketRate: 'Market price', rateSource: 'Rate source', reviewer: 'Handled by', detectedAt: 'Detected', creditedAt: 'Credited at', ledger: 'Ledger', commission: 'Commission',
        recheck: 'Re-check', recheckDone: 'Refreshed: {status} ({n}/{m})', creditBtn: 'Credit', creditTitle: 'Credit manually', creditRm: 'RM to credit (empty = current rate)',
        closeBtn: 'Close', closeTitle: 'Close without crediting', reasonLabel: 'Reason (kept in the audit log)', manualBtn: 'Manual entry', manualTitle: 'Record a missed on-chain deposit',
        user: 'Member (ID / phone / member ID)', userId: 'Member internal ID', simulate: 'Simulate deposit (test)', simulateTitle: 'Simulate a crypto deposit',
        simulateHint: 'Testing only: no blockchain involved, the record is flagged “simulated”. Confirmations grow every few seconds and it is credited when complete.', instant: 'Confirm instantly',
        simulateDone: 'Simulated deposit #{id} created ({status})', credited: 'Credited {money}',
        wd: { pending: 'To review', paid: 'Paid', rejected: 'Rejected', cancelled: 'Cancelled by member' },
        source: 'Source', sourceWallet: 'Balance', sourceIncome: 'Earnings', net: 'Payout', account: 'Payout account', payRef: 'Payment ref', approve: 'Approve & mark paid',
        reject: 'Reject', approveTitle: 'Confirm the payout was made', referenceLabel: 'Payment reference / tx hash', rejectTitle: 'Reject (amount returned)', sumAmount: 'Requested',
        sumNet: 'Payout total', memberBalance: 'Balance {b} · earnings {i}',
        tp: { pending: 'To review', credited: 'Credited', rejected: 'Rejected', cancelled: 'Withdrawn by member' }, receipt: 'Receipt', reference: 'Reference',
        approveTopup: 'Credit', approveTopupTitle: 'Credit offline top-up', creditAmount: 'RM to credit', rejectTopupTitle: 'Reject offline top-up',
        commissionOff: 'Agent commission is off (turn it on in the rules below). When on, each crypto / offline top-up of an agent’s members records a commission.',
        commissionOn: 'Agent commission is on: default rate {rate}; an agent’s own rate takes precedence.', unpaid: 'Unpaid', paid: 'Paid', void: 'Void', markPaid: 'Mark paid',
        payTitle: 'Mark {n} commissions paid', agent: 'Agent', base: 'Top-up', ratio: 'Rate', byAgent: 'By agent', selectFirst: 'Select unpaid commissions first',
        held: 'Funds held now', balance: 'Member balances', frozen: 'Frozen (withdrawals)', beans: 'Gold beans', incomeHeld: 'Withdrawable earnings', incomePending: 'Pending earnings',
        byKind: 'By type', daily: 'By day', day: 'Day', count: 'Count', earned: 'Earned', withdrawn: 'Withdrawn', inReview: 'In review',
        chain: 'Chain', index: 'Index', path: 'Path', received: 'Credited', chainBalance: 'On-chain balance (last read)', lastViewed: 'Last opened', readBalance: 'Read balance',
        balanceRead: 'Balance read', explorer: 'Explorer', addressQ: 'Member / address', summary: 'Summary', creditedAll: 'Credited (real)', heldOnChain: 'Held on addresses (last read)',
        sweepHint: 'Sweeping: with the wallet that holds the recovery phrase, move these funds to your main wallet; addresses are listed in derivation order.',
        crypto: {
          status: 'Status', enabled: 'Crypto top-up', on: 'On', off: 'Off', rates: 'Rates', mode: 'Mode', market: 'Market', fixed: 'Fixed',
          used: 'Rate used', lastError: 'Last error', refresh: 'Refresh rates', networks: 'Networks', provider: 'API', key: 'Key', watched: 'Watched', open: 'Confirming',
          lastRun: 'Last run', tip: 'Latest block', scan: 'Scan the chains now', scanDone: 'Scan finished', keys: 'Wallet extended public keys', keysWarn:
            'Enter extended PUBLIC keys (xpub / zpub) only. Never enter a recovery phrase or private key here — it is refused. Run the offline tool server/tools/XpubTool on your own computer, offline, and compare the first addresses with your wallet app.',
          current: 'Current', notSet: 'Not set', keyId: 'Key ID', depth: 'Depth', depthWarn: 'Depth is not 3: make sure this is the account-level key ({path})', first: 'First 3 addresses',
          replace: 'Replace key', preview: 'Preview', save: 'Save', clear: 'Clear', saved: 'Saved. New member addresses come from this key; old addresses stay watched for {days} days.',
          changeWarn: 'Members will get new deposit addresses. Funds on old addresses stay in the old wallet — sweep them yourself. Continue?', assets: 'Coins & networks',
          minDeposit: 'Minimum', feePct: 'Fee %', sort: 'Order', priceId: 'Price ID', stable: 'Stablecoin', available: 'Available', addAsset: 'Add asset',
          coin: 'Coin', saveRow: 'Save', rules: 'Detection & rate rules', apis: 'Blockchain APIs', needKey: 'Etherscan API key missing (Blockchain APIs below)',
        },
        settingsSub: 'Top-up presets and limits, methods on/off, bank transfer instructions, withdrawal rules.',
        tab: { addresses: 'Addresses', deposits: 'Crypto', withdrawals: 'Withdrawals', topups: 'Offline top-ups', accounts: 'Payout accounts', claims: 'Rewards' },
      },
      err: {
        'crypto.xpubMissing': 'Enter the extended public key', 'crypto.mnemonicRejected': 'Never enter a recovery phrase; extended public keys only', 'crypto.xpubInvalid': 'Invalid extended public key',
        'crypto.privateKeyRejected': 'That is a private key; enter the public key only', 'crypto.xpubWrongType': 'Bitcoin needs a zpub or xpub', 'crypto.notConfigured': 'No extended public key set',
        'crypto.disabled': 'Crypto top-up is off', 'crypto.unavailableOnPlatform': 'Not available on this platform', 'crypto.assetUnavailable': 'Unknown or disabled asset',
        'crypto.depositNotFound': 'Deposit not found or outside your data scope', 'crypto.amountInvalid': 'Invalid amount', 'crypto.notOpen': 'This deposit is not confirming',
        'crypto.providerMissing': 'No API for this network', 'crypto.providerFailed': 'The blockchain API failed. Try again later', 'crypto.alreadyCredited': 'Already credited',
        'crypto.creditFailed': 'Crediting failed (no rate or invalid amount); enter the RM amount', 'crypto.txInvalid': 'Invalid tx hash', 'crypto.txExists': 'This transaction is already recorded', 'crypto.chainInvalid': 'Unsupported chain',
        'crypto.networkInvalid': 'Unsupported network', 'crypto.coinInvalid': 'Coin code: 2–12 capital letters or digits', 'crypto.codeInvalid': 'The code must be COIN-NETWORK, e.g. USDT-TRC20',
        'crypto.contractInvalid': 'Invalid contract address', 'crypto.decimalsInvalid': 'Decimals must be 0–30', 'crypto.addressNotFound': 'Address not found',
        'topup.notPending': 'Already handled', 'topup.notFound': 'Request not found or outside your data scope', 'topup.disabled': 'Offline top-up is off', 'topup.amountRange': 'Amount out of range',
        'topup.proofRequired': 'Proof missing', 'topup.receiptInvalid': 'Invalid receipt', 'topup.tooManyPending': 'Too many pending requests',
        'withdraw.notFound': 'Withdrawal not found or outside your data scope', 'withdraw.notPending': 'Already handled', 'withdraw.referenceRequired': 'Enter the payment reference or tx hash',
        'withdraw.disabled': 'Withdrawals are off', 'withdraw.demoLocked': 'The demo account cannot withdraw', 'withdraw.sourceDisabled': 'Source disabled', 'withdraw.belowMin': 'Below the minimum',
        'withdraw.accountRequired': 'Payout account missing', 'withdraw.dailyCount': 'Daily count exceeded', 'withdraw.dailyAmount': 'Daily amount exceeded', 'withdraw.tooManyAccounts': 'Too many payout accounts',
        'withdraw.kindInvalid': 'Invalid payout method', 'withdraw.providerRequired': 'Bank / wallet / network missing', 'withdraw.nameRequired': 'Holder name missing', 'withdraw.bankNoInvalid': 'Invalid account number',
        'withdraw.phoneInvalid': 'Invalid phone', 'withdraw.networkInvalid': 'Invalid network', 'withdraw.addressInvalid': 'Invalid address',
        'finance.reasonRequired': 'Enter a reason', 'finance.nothingSelected': 'Select records first', 'finance.commissionNotOpen': 'Commission already handled',
        'tasks.unknown': 'Unknown task', 'tasks.notDone': 'Task not done',
        'member.disabled': 'Membership is off', 'member.already': 'Already claimed',
      },
    },
  },
};
