#!/usr/bin/env node
/*
 * Demo-content translation pipeline, step 3: assemble.
 *
 *   node tools/l10n/assemble.js <locale>
 *
 * Merges .l10n-work/<locale>/glossary.out.json and out/*.json ({ key: translation }) and writes
 * data/i18n/<locale>/<chunk>.js files that call SZ_I18N.addContent(locale, kind, records).
 * Strings without a translation are left out (the app falls back to the original text) and
 * listed in .l10n-work/<locale>/missing.json so another pass can fill them.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const locale = process.argv[2];
if (!locale) {
  console.error('usage: node tools/l10n/assemble.js <locale>');
  process.exit(1);
}
const workArg = process.argv.indexOf('--work');
const WORK = path.join(ROOT, '.l10n-work', workArg > 0 ? process.argv[workArg + 1] : locale);
const OUT = path.join(ROOT, 'data', 'i18n', locale);
const CJK = /[㐀-鿿]/;

const tr = {};
const read = f => {
  try {
    return JSON.parse(fs.readFileSync(f, 'utf8'));
  } catch (e) {
    console.warn('skip unreadable', path.relative(ROOT, f), e.message);
    return {};
  }
};
if (fs.existsSync(path.join(WORK, 'glossary.out.json'))) Object.assign(tr, read(path.join(WORK, 'glossary.out.json')));
for (const f of fs.existsSync(path.join(WORK, 'out')) ? fs.readdirSync(path.join(WORK, 'out')) : [])
  if (f.endsWith('.json')) Object.assign(tr, read(path.join(WORK, 'out', f)));

const refs = JSON.parse(fs.readFileSync(path.join(WORK, 'refs.json'), 'utf8'));
const chunks = new Map(); // chunk -> kind -> id -> fields
const missing = new Set();
for (const r of refs) {
  const value = tr[r.k];
  // Reject empty or still-untranslated values (leftover source text is worse than the fallback).
  if (typeof value !== 'string' || !value.trim() || CJK.test(value)) {
    missing.add(r.k);
    continue;
  }
  if (!chunks.has(r.chunk)) chunks.set(r.chunk, new Map());
  const kinds = chunks.get(r.chunk);
  if (!kinds.has(r.kind)) kinds.set(r.kind, {});
  const records = kinds.get(r.kind);
  const rec = (records[r.id] = records[r.id] || {});
  if (r.index == null) rec[r.field] = value.trim();
  else {
    rec[r.field] = rec[r.field] || [];
    rec[r.field][r.index] = value.trim();
  }
}
fs.mkdirSync(OUT, { recursive: true });
let files = 0;
for (const [chunk, kinds] of chunks) {
  let body = `/* ${locale} translations of demo content (${chunk}). Generated by tools/l10n/assemble.js — edit the .l10n-work sources or this file directly. */\n`;
  for (const [kind, records] of kinds) body += `SZ_I18N.addContent(${JSON.stringify(locale)}, ${JSON.stringify(kind)}, ${JSON.stringify(records)});\n`;
  fs.writeFileSync(path.join(OUT, chunk + '.js'), body);
  files++;
}
fs.writeFileSync(path.join(WORK, 'missing.json'), JSON.stringify([...missing], null, 1));
const total = new Set(refs.map(r => r.k)).size;
console.log(`${locale}: wrote ${files} files to data/i18n/${locale}/ — ${total - missing.size}/${total} strings translated, ${missing.size} missing (see .l10n-work/${locale}/missing.json)`);
console.log('chunks:', [...chunks.keys()].join(', '));
